### ISSUE TITLE
Thumbs Up and YouTube Buttons Overlap in Mini Player

### ISSUE THREAD

**Issue by collinjackson93** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#145] opened 2016-01-13 17:26 UTC
Title pretty much sums it up. I attached a screenshot below to illustrate. The issue occurs in the bottom left corner.
![image](https://cloud.githubusercontent.com/assets/5580739/12301926/3664915e-b9e8-11e5-992c-0caf8379d748.png)

**Comment by MarshallOfSound** [comment] 2016-01-13 17:29
Youtube button....
I have never seen that... Ever.... :thought_balloon: 

In what scenario does that button appear

**Comment by collinjackson93** [comment] 2016-01-13 22:00
I am a YouTube Red/Google Play Premium subscriber. Maybe that's why it comes up?

**Comment by MarshallOfSound** [comment] 2016-01-13 22:11
Ahhh, youtube red... Well, this might be hard to fix cos I can't see the button so I can't put it in the right place.  You're actually really lucky it ended up in a not so bad place....  Could have been worse :P

**Comment by collinjackson93** [comment] 2016-01-14 03:07
Agreed! It's not a huge deal to me, and if it doesn't bother other people, I'm fine with it staying where it is. I'd hate for you to spend a lot of time fixing a small bug that only affects a couple of people.

**Comment by MarshallOfSound** [comment] 2016-01-14 06:46
Not even sure where I would move it to TBH, I would probably just hide it...

**Comment by JoshuaGarrison27** [comment] 2016-01-18 11:53
Could you have it hover in the middle of the Album art? That that is what Google does on the web version.

**Comment by seeb0h** [comment] 2016-01-21 13:47
I have a overlap problem but different :
![miniplayer](https://cloud.githubusercontent.com/assets/4989990/12482061/be5de5ea-c04d-11e5-83e0-ac8b84c6971d.png)

windows 7 64bits, GPMDP 2.0.2

**Comment by seeb0h** [comment] 2016-01-22 08:22
As I had another bug (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/149) I tried the beta version.

I couldn't reproduce the bug with the beta.

**Comment by blueswag80** [comment] 2016-01-23 16:42
I think I have found the element that causes this little problem. 

class="now-playing-actions  has-youtube"

When I have hid this element on the webpage the youtube button and menu are gone. Problem is, it has been a long time since I have coded anything for the web. Marshall can you tell me where I have to go in the code to hide this element?

**Comment by MarshallOfSound** [comment] 2016-01-23 23:52
The mini player functionality is actually in a separate repository.  You probably want to add a CSS rule to this stylesheet.

https://github.com/MarshallOfSound/gmusic-mini-player.js/blob/master/lib/override.css

Let me know how it goes or if you need help setting up a dev environment

**Comment by blueswag80** [comment] 2016-01-24 16:35
Hey Marshall, I have forked that other repo and have been looking at it. Sadly, I might need to get that help setting up the dev environment. I have been looking at grunt and believe I have installed all the dependencies however, I run grunt and it appears to finish just fine but nothing seems to happen. Is grunt supposed to compile everything into gmusic-mini-player.min.js?

**Comment by MarshallOfSound** [comment] 2016-01-24 18:37
@blueswag80 Try running `grunt build`

**Comment by blueswag80** [comment] 2016-01-25 04:43
Okay I think I got it now. I may have also gotten rid of the up and down thumbs so let me know what you think of it right now. If need be, I can put the thumbs back (Not sure how, but I will :-) ) . When I have this sorted out you want me to commit the change to the mini player correct? Apologies ahead of time, this could be my first pull and I might screw it up.

![notube](https://cloud.githubusercontent.com/assets/1497489/12542631/b88f2572-c2f3-11e5-861c-4a9bcecd5e87.jpg)

**Comment by MarshallOfSound** [comment] 2016-01-25 05:08
The thumb up / down button should appear when you play a radio station, could you test that they still do?

Once you've done that, commit to master on your fork and make a PR and I'll take a look at it :)

**Comment by blueswag80** [comment] 2016-01-25 15:02
Ah that was it thank you. I am at work however, I managed to get a little time to build and check and I saw that the thumbs do appear when it is a station. When I get home I will commit my changes and submit the request. Thanks for all the help, it is really appreciated.

**Comment by MarshallOfSound** [comment] 2016-01-27 18:55
Closing as fixed in correct repo

**Closed by MarshallOfSound** 2016-01-27 18:55 UTC
Labels: help wanted
