### ISSUE TITLE
loading music... (nothing happens)

### ISSUE THREAD

**Issue by Herchi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3667] opened 2019-11-07 09:24 UTC
**OS:** W10 64bits

**GPMDP Version:** 4.6.1

**Issue Descriptions:** loading music... (nothing happens)

**Steps to Reproduce:** open the app (I had tried it in two computers that it works before)

DEBUG INFO:
{"level":"info","message":"Application started.","timestamp":"2019-11-07T09:09:58.678Z"}
{"level":"info","message":"Application exiting...","timestamp":"2019-11-07T09:18:31.544Z"}
{"level":"info","message":"Application started.","timestamp":"2019-11-07T09:18:50.993Z"}

**Comment by AverageMaker** [comment] 2019-11-07 10:21
I have the same issue. Tried running as administrator and enabling some of the settings which mentioned W10 services, but still stuck.

**Comment by reduckted** [comment] 2019-11-07 10:27
See #3660.

**Comment by AverageMaker** [comment] 2019-11-07 10:34
That fixed it for me (Windows 10) - I just downloaded and ran the file here: https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/artifacts

**Comment by XLave** [comment] 2019-11-08 14:42
> That fixed it for me (Windows 10) - I just downloaded and ran the file here: https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/build/artifacts

That worked for me!! THX!

**Comment by armandsperduti** [comment] 2019-11-09 05:38
That fixed the same problem I had on multiple systems. Thank you.

**Comment by chdrummer** [comment] 2019-11-10 17:27
Thanks, fixed for me as well!!

**Comment by shaneg8514** [comment] 2019-11-11 16:50
I am having this issue as well, but I am running the Ubuntu version of the package. Is there an App Veyor for Ubuntu?

**Comment by jostrander** [comment] 2019-11-11 17:00
The artifacts for ubuntu are under CircleCI. You can find the artifact links in the readme near the top.

**Comment by jostrander** [comment] 2019-11-11 17:00
Also, this is a duplicate of #3660.

**Closed by jostrander** 2019-11-11 17:00 UTC

**Comment by shaneg8514** [comment] 2019-11-11 17:10
I'm sorry--- It isn't clear to me as to how to pull the update out of there :-/ Sorry if this is a dense question.

**Comment by shaneg8514** [comment] 2019-11-11 17:13
Err scratch last. I just got it to work by following the links in #3660. I appreciate your help!
