### ISSUE TITLE
Request: Add Alarm Feature

### ISSUE THREAD

**Issue by mark8547** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#211] opened 2016-03-05 18:48 UTC
Adding an alarm feature would be awesome! I'd love to have this app wake me up by fading in a song, radio station, playlist, etc. at a set time.

**Comment by SicariusNoctis** [comment] 2016-03-14 16:28
Sounds like something your phone should be able to do. There's a number of apps: the ones I have used are "Sleep as Android" and "I Can't Wake Up".

**Comment by mark8547** [comment] 2016-03-14 23:55
I do have the same feature on my phone alarms, but I use my computer as a backup.

**Comment by juschu** [comment] 2016-05-13 12:07
Yes, there are Apps that can wake you up with music.
But I'm sure they all need those old fashioned local files and they can't access music from Google Play Music.

**Comment by MarshallOfSound** [comment] 2016-06-21 07:02
/cc @fkrauthan

> The music player Songbird used to have a extension that automatic fades music after a certain time and then executes a command.

> This was perfect to just listen for e.g. 30min to music and then the music slowly fades out (or it waits until the current song is finished) and then turns off my computer. I would love to see something like that integrated here.

**Comment by ChrisB9** [comment] 2016-06-21 07:16
Yesterday i started to implement the alarm and sleep-mode feature

**Comment by MarshallOfSound** [comment] 2016-06-21 07:19
@ChrisB9 Woo hoo 👍

**Comment by MarshallOfSound** [comment] 2016-09-09 19:23
This issue has been added to the `4.0.0` milestone.

**What does this mean?**
It means that the next major release *should* contain this feature / bugfix.  If you are responsible for this issue please ensure that it is fully up to date to give me the best change of implementing / fixing what needs to be done.

**What do you need to do?**
If the issue is tagged with "Awaiting Response" it means that I need something from you, be that more information or in some cases a PR with the issue resolution 👍 .  Just do whatever you can to help me sort it out.

**So when will this glorious `4.0.0` release come out?**
Who knows... 😆  The major component of `4.0.0` is a rewrite of **ALL** the renderer process code and logic into a React based toolkit that I am creating from scratch over in #1581 .  Subscribe there for more updates as `4.0.0` will not be released until that is merged.

**Closed** 2016-09-15 15:38 UTC
Labels: Easy First Issue, enhancement

**Comment by fkrauthan** [comment] 2016-11-09 06:52
Quick question I thought with the Alarm feature you also implement the sleep feature (after a certain time interval and after a song finished to shutoff the computer). But the new feature is just to start playing music at a certain time correct? Or did I miss something? Should I open a new bug report/feature request for this?
