### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by macgrver** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#534] opened 2016-03-12 22:24 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Sat Mar 12 2016 16:24:07 GMT-0600 (Central Standard Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\Samuel Pester\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\Samuel Pester\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-12 22:36
Closing this automatically reported issue as a duplicate of #470

**Closed by GPMDP-Magical-Unicorn** 2016-03-12 22:36 UTC
Labels: Automatic-Issue-Report
