### ISSUE TITLE
Feature request: Option to set language manually.

### ISSUE THREAD

**Issue by BalzGuenat** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1414] opened 2016-08-05 15:25 UTC
I'm on Windows 10. I live in Switzerland and all region/format settings are set accordingly except display language and keyboard layout because I like an English UI. For unknown reasons, the Desktop Player displays in German and I would like to change that.

**Comment by MarshallOfSound** [comment] 2016-08-05 15:26
@BalzGuenat We detect your language through Chromium.  Funky that we pick it up as German

**Comment by jostrander** [comment] 2016-08-05 15:29
Where in the code is this @MarshallOfSound?

**Comment by MarshallOfSound** [comment] 2016-08-05 15:29
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/_locales/_provider.js#L29

**Comment by BalzGuenat** [comment] 2016-08-05 15:39
I admit my languauge setup might be a bit funky. Chrome also gets served the German page at play.google.com/music/listen and I'm not sure why, as the display language of Chrome is also set to English. This is why a simple manual option would be nice.

**Comment by Kun2210** [comment] 2016-08-06 20:21
@BalzGuenat language at play.google.com/music/listen is based on your Google account settings, not Chrome's display language.

**Comment by daishi424** [comment] 2016-08-26 14:04
I'm not sure whether it should be filed as a new issue or is relevant to this one, but here's another language problem.

Google Play Music serves tracks in your set language, which in my case is Russian. Then **Last.FM** scrobbles that track as it is -- with artist's name localized in Russian, and that, of course, appears in your Last.FM library as a separate artist.

Example: [Stan Bush](http://www.last.fm/ru/music/Stan+Bush) and [Стэн Буш](http://www.last.fm/ru/music/%D0%A1%D1%82%D1%8D%D0%BD+%D0%91%D1%83%D1%88) - different artists, different results.

Can this issue be fixed without involving Google account language change? May be some kind of reverse tag lookup based on track's title? Both options seem a bit too extreme.

**Comment by MarshallOfSound** [comment] 2016-09-09 19:22
This issue has been added to the `4.0.0` milestone.

**What does this mean?**
It means that the next major release *should* contain this feature / bugfix.  If you are responsible for this issue please ensure that it is fully up to date to give me the best change of implementing / fixing what needs to be done.

**What do you need to do?**
If the issue is tagged with "Awaiting Response" it means that I need something from you, be that more information or in some cases a PR with the issue resolution 👍 .  Just do whatever you can to help me sort it out.

**So when will this glorious `4.0.0` release come out?**
Who knows... 😆  The major component of `4.0.0` is a rewrite of **ALL** the renderer process code and logic into a React based toolkit that I am creating from scratch over in #1581 .  Subscribe there for more updates as `4.0.0` will not be released until that is merged.

**Closed** 2016-10-14 07:37 UTC
Labels: Bug, Enhancement
