### ISSUE TITLE
Uncaught Exception: dns service error: unknown

### ISSUE THREAD

**Issue by vexii** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1151] opened 2016-06-05 18:50 UTC
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Sun Jun 05 2016 20:55:00 GMT 0200 (CEST)

#### Error:
*dns service error: unknown*
```js
Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:64:10)
    at enableAPI (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:60:25)
    at EventEmitter.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:132:7)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (/usr/share/google-play-music-desktop-player/resources/electron.asar/browser/api/web-contents.js:130:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-06-05 18:55
Closing this automatically reported issue as a duplicate of #1048

**Closed by GPMDP-Magical-Unicorn** 2016-06-05 18:55 UTC
Labels: Automatic-Issue-Report
