### ISSUE TITLE
Feature request: Send likes to lastfm when "Thumbs up" was clicked.

### ISSUE THREAD

**Issue by shynkevich-alex** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1599] opened 2016-09-08 07:50 UTC
@MarshallOfSound  
App sends only played songs.
I suggest option when we can select send likes or not.

**Comment by MarshallOfSound** [comment] 2016-09-09 19:22
This issue has been added to the `4.0.0` milestone.

**What does this mean?**
It means that the next major release *should* contain this feature / bugfix.  If you are responsible for this issue please ensure that it is fully up to date to give me the best change of implementing / fixing what needs to be done.

**What do you need to do?**
If the issue is tagged with "Awaiting Response" it means that I need something from you, be that more information or in some cases a PR with the issue resolution 👍 .  Just do whatever you can to help me sort it out.

**So when will this glorious `4.0.0` release come out?**
Who knows... 😆  The major component of `4.0.0` is a rewrite of **ALL** the renderer process code and logic into a React based toolkit that I am creating from scratch over in #1581 .  Subscribe there for more updates as `4.0.0` will not be released until that is merged.

**Comment by berryelectronics** [comment] 2016-09-19 19:21
@MarshallOfSound Just asking if i get it: gmusic only sends an emitter event if the current playing song has been liked, but not if something else has been liked, or? F.Ex. liking a song in a playlist which isnt played doesnt sends an event.

**Comment by jostrander** [comment] 2016-09-19 23:12
Correct. Only currently playing tracks send information to last.fm.

**Comment by berryelectronics** [comment] 2016-09-20 14:15
so thats a problem i guess.

**Closed** 2016-09-27 11:34 UTC
Labels: Enhancement
