### ISSUE TITLE
Uncaught Exception: dns service error: unknown

### ISSUE THREAD

**Issue by Fallon9111** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1065] opened 2016-05-11 17:21 UTC
On Arch Linux, not sure what this error means, but it happens on every startup of GPMDP and media keyboard keys no longer work (although they often haven't in the past either...)

#### Error Report:
An uncaught exception was reported.  

#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Wed May 11 2016 18:18:40 GMT 0100 (BST)

#### Error:
*dns service error: unknown*
```js
Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:64:10)
    at enableAPI (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:60:25)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:142:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-05-11 17:27
Closing this automatically reported issue as a duplicate of #1048

**Closed by GPMDP-Magical-Unicorn** 2016-05-11 17:27 UTC
Labels: Automatic-Issue-Report

**Comment by BrianAllred** [comment] 2016-05-11 18:23
Is this using the stable or unstable package?
