### ISSUE TITLE
Uncaught Exception: listen EADDRINUSE 0.0.0.0:5672

### ISSUE THREAD

**Issue by Hiewxt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1078] opened 2016-05-14 21:39 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.2.4
**Time:** Sat May 14 2016 15:38:21 GMT-0600 (Mountain Daylight Time)

#### Error:
*listen EADDRINUSE 0.0.0.0:5672*
```js
Error: listen EADDRINUSE 0.0.0.0:5672
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by jostrander** [comment] 2016-05-14 21:43
The Magical Unicorn is going to close this, but why are we still getting this error? I thought there was an error exception to catch this?

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-05-14 21:43
Closing this automatically reported issue as a duplicate of #325

**Comment by MarshallOfSound** [comment] 2016-05-15 01:48
@jostrander Because I forgot that a WSS is an emitter so a try { } catch () {} doesn't help

**Closed** 2016-05-15 01:47 UTC
Labels: Automatic-Issue-Report
