### ISSUE TITLE
Couldn't sign you in

### ISSUE THREAD

**Issue by crollison** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3703] opened 2019-12-06 14:14 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**  Windows 10

**GPMDP Version:**  4.6.1

**Issue Descriptions:**  Can not sign in to Google Play Music, or Youtube.  After entering Google Account name, immediately goes to a page "You are trying to sign in from a browser or app that doesn't allow us to keep your account secure.  Try using a different browser"  Do not get to a password field.

**Steps to Reproduce:**  Try signing in.

DEBUG_INFO did not produce a zip file.

**Comment by crollison** [comment] 2019-12-06 14:16
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3932531/debug_info.zip)


Finally produced zip file.

**Comment by Glench** [comment] 2019-12-06 17:38
I have this too. Can't use GPMDP at all until it's fixed unfortunately.

**Comment by jostrander** [comment] 2019-12-06 17:39
Duplicate of #3545

**Closed by jostrander** 2019-12-06 17:39 UTC
