### ISSUE TITLE
Program hang

### ISSUE THREAD

**Issue by hailthesmoot** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3713] opened 2019-12-09 06:47 UTC
**OS:**
Windows 10.0.18362 Build 18362

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
Starting today, whenever I open the program it just gets stuck on loading music library. I'm able to open the desktop along with interact with some of the options while right clicking on the icon for it. There I was able to notice that it wasn't recognizing any of my audio playback devices. I tried performing an uninstall/reinstall to no avail. Before today, everything worked fine. No changes have been made, software or hardware, prior to the issues starting.

**Steps to Reproduce:**
Open the program

I've included screen shots of what I can access.

**NOTE** None of the "fixes" in #3660 do anything at all.

![Untitled](https://user-images.githubusercontent.com/3710190/70413285-a356c280-1a1c-11ea-8fdb-e5b1d2075122.png)
![Untitled2](https://user-images.githubusercontent.com/3710190/70413292-a6ea4980-1a1c-11ea-9fc4-a1ca8207564e.png)
![Untitled3](https://user-images.githubusercontent.com/3710190/70413618-6e973b00-1a1d-11ea-9bcc-07260d8b7052.png)

**Comment by v1adko** [comment] 2019-12-09 06:53
I can double this, same issue on MacOS. Issue since Saturday morning.

MacOS Mojave 10.14.6
GPMDP Version: 4.6.1

**Comment by JadenSed** [comment] 2019-12-09 07:36
I've also been having this problem on GPMDP Ver 4.6.1, Windows 10 Home 64-bit Build 17134

**Comment by matthuisman** [comment] 2019-12-09 07:37
Same here

**Comment by josh-unwin** [comment] 2019-12-09 08:48
Same here with MacOS Mojave and 4.6.1

**Comment by DonMorr** [comment] 2019-12-09 08:57
Also seeing this issue on MacOS 10.15.1 (19B88) and 4.6.1

@matthuisman, is there a latest master build for MacOS available for download?

**Comment by AndrazP** [comment] 2019-12-09 09:40
Duplicate of #3660

**Comment by adancedwin** [comment] 2019-12-09 09:47
@DonMorr you can already build one yourself with the latest mater - it works on macOS.

[built by me (macOS)](https://drive.google.com/file/d/1mgZDKpZDAHnMDpQNmHyS4wLZENMAYkQa/view?usp=sharing)

**Comment by v1adko** [comment] 2019-12-09 09:53
Thank you, didn't see the "pinned" issues.

**Comment by DonMorr** [comment] 2019-12-09 09:54
@adancedwin - excellent, thank you.

**Closed** 2019-12-09 12:24 UTC

**Comment by hailthesmoot** [comment] 2019-12-09 14:52
> Thank you, didn't see the "pinned" issues.
> You can download it also [directly from CI artifacts](https://app.circleci.com/jobs/github/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/3744/artifacts)

That link is broken and it does not fix anything as stated in the original post.
