### ISSUE TITLE
Uncaught Exception: dns service error: unknown

### ISSUE THREAD

**Issue by slowbro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1064] opened 2016-05-11 16:18 UTC
An uncaught exception was reported.  
#### Info:
**OS:** Arch Linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Wed May 11 2016 09:17:53 GMT-0700 (PDT)

#### Error:
*dns service error: unknown*
```js
Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:64:10)
    at enableAPI (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:60:25)
    at Object.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:142:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by slowbro** [comment] 2016-05-11 16:19
Seems to work just fine after this error popped up, FYI.

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-05-11 16:27
Closing this automatically reported issue as a duplicate of #1048

**Closed by GPMDP-Magical-Unicorn** 2016-05-11 16:27 UTC
Labels: Automatic-Issue-Report, duplicate

**Comment by MarshallOfSound** [comment] 2016-05-11 16:36
/cc @BrianAllred 

This is due to your install not fetching the latest dependencies.  I think it was fixed by @BrianAllred but you might have to reinstall ?

**Comment by BrianAllred** [comment] 2016-05-11 18:26
@MarshallOfSound 

My stable package just unpacks the deb file you provide and repackages it for an Arch system. If these guys are on stable, I have no idea what's up here. 

If you're on the unstable package, @slowbro, do a reinstall. The pkgbuild has changed to pull new and updated dependencies during the build process.

**Comment by slowbro** [comment] 2016-05-11 18:47
@BrianAllred unstable being google-play-music-desktop-player-git?

**Comment by slowbro** [comment] 2016-05-11 18:53
@BrianAllred I added a comment to the AUR page about an error I am getting on rebuild.

**Comment by MarshallOfSound** [comment] 2016-05-12 02:08
@BrianAllred I think they are all on unstable :cry: 

The dependency they all need though is this

`libavahi-compat-libdnssd-dev`

**Comment by BrianAllred** [comment] 2016-05-12 02:47
Yeah, I've got that as a dependency (actually just the Arch `avahi` package, but Arch installs dev files for most packages by default). And it worked for a while. I also saw the CircleCI builds are failing, so I'll wait until those are fixed before I keep investigating.

**Comment by MarshallOfSound** [comment] 2016-05-12 02:48
@BrianAllred They are failing due to an Upstream issue in electron-rebuild.  We're working on it :+1:
