### ISSUE TITLE
Windows 10 media integration not working

### ISSUE THREAD

**Issue by des2say** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2386] opened 2017-03-28 04:13 UTC
Windows10

Google-Play-Music-Desktop-Player-4.2.0

Clean install of windows 10 on a new atom x5 cherry Trail based windows tablet and installed Google-Play-Music-Desktop-Player-4.2.0 and the Windows 10 media widget the shows up when adjusting the volume does show up when using Google-Play-Music-Desktop-Player-4.2.0, and it is also not on the lock screen. I have verified it works with other media programs such as Spotify and Microsoft Groove. I have Google-Play-Music-Desktop-Player-4.2.0 installed on a windows 10 laptop with an i7 with no issues. Seems to be only the tablet. Not sure if it is windows connected stand by causing the issue or the atom chip set. I have disabled connected stand by and uninstalled and reinstalled Google-Play-Music-Desktop-Player-4.2.0 with no change. I have enabled media integration in settings with no change and restarted the computer with no change.

**Comment by MarshallOfSound** [comment] 2017-03-28 04:17
Duplicate of your own issue?  Please post updates on that thread and i will reopen if appropriate

**Closed by MarshallOfSound** 2017-03-28 04:17 UTC
