### ISSUE TITLE
Cannot interact with JSON API using curl due to "upgrade required" message

### ISSUE THREAD

**Issue by ryanpatrickmckenna** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3924] opened 2021-03-25 00:23 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content
* [x] I have checked the FAQ and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** 
Windows 10

**GPMDP Version:** 
4.7.1

**Issue Descriptions:** 
When I attempt to interact with the JSON API I get a message that says _Upgrade Required_. This happens using curl in PowerShell and also when I navigate to _http://localhost:5672_ in a web browser. I noticed that in the log files, it is trying to start Bonjour but fails. I tried installing Bonjour from Apple's website and restarting the app but that did not seem to help. Full disclosure I am new to programming and may just be doing this wrong. I have attempted to follow the WebSocket API guidelines in the Wiki. Also note that ws://localhost:5672 did not work so I used the http prefix instead. It appears to connect but then fails because of the aforementioned error message.

**Steps to Reproduce:**

1. Create JSON file with this info in the directory:
`{
  "namespace": "connect",
  "method": "connect",
  "arguments": ["MS190725W"]
}`
2. Run the following from a PowerShell terminal:
` curl -uri http://localhost:5672 -body .\connect.json -method post`
3. The terminal with output with the following:
`
curl : Upgrade required
At line:1 char:1
 curl -uri http://localhost:5672 -body $file -method post
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

I have also tried PUT and other methods as well. 

Any info you have is helpful thank you!!

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/6201171/debug_info.zip)

**Comment by jostrander** [comment] 2021-03-25 02:10
I don't know of a way to use Powershell and Websockets, but there is no HTTP interface other than through WebSocket. The way WebSockets are usually initiated is through HTTP. The response you are getting is from the HTTP server trying to tell the client to "upgrade" the protocol to WebSocket, thus dropping the connection and continuing on another channel. For what it's worth, bonjour is only needed for Chromecast and other discovery related tasks. 

It appears you _can_ use Powershell and WebSockets as seen [here](https://stackoverflow.com/questions/40257671/how-to-use-a-websocket-client-to-open-a-long-lived-connection-to-a-url-using-po), but I've never tried it before.

I'm going to close this as it's not a bug per se but feel free to keep the conversation going.

**Closed as completed by jostrander** 2021-03-25 02:10 UTC

**Comment by ryanpatrickmckenna** [comment] 2021-03-26 01:48
Thank you so much for that info! Could you tell me what the preferred way of interacting with WebSockets is? I'm trying to automate playing and pausing music at a set time each day. My initial thought was to make a PS script or batch file and use Windows scheduler. I'm familiar enough with Python and looks like there's some libraries for WebSocket but I was just curious is there is a standard way that everyone likes.

Thanks for your help
