### ISSUE TITLE
Uncaught Exception: listen EADDRINUSE 0.0.0.0:5672

### ISSUE THREAD

**Issue by rameezv** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#926] opened 2016-04-09 20:25 UTC
FYI: GPMDP can't find any audio devices and won't play any songs.

An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.1.0
**Time:** Sat Apr 09 2016 14:24:26 GMT-0600 (Canada Central Standard Time)

#### Error:
*listen EADDRINUSE 0.0.0.0:5672*
```js
Error: listen EADDRINUSE 0.0.0.0:5672
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:476:9)
    at process._tickCallback (node.js:382:17)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-04-09 20:40
Closing this automatically reported issue as a duplicate of #325

**Closed by GPMDP-Magical-Unicorn** 2016-04-09 20:40 UTC
Labels: Automatic-Issue-Report, duplicate
