### ISSUE TITLE
Media keys does not work when in fullscreen

### ISSUE THREAD

**Issue by olback** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1253] opened 2016-06-29 23:36 UTC
**OS:** Windows 10 64-bit

**Issue Descriptions:** Title says it all, but here is some more info. I use a Corsair K70 RGB.

Firmware: http://puu.sh/pKNBy/c145e129a2.jpg
Software: https://puu.sh/pKNJa/476255314e.png

**Steps to Reproduce:** Open any Fullscreen app, i tested with both Grand Theft Auto 5 and CS:GO.

**Comment by MarshallOfSound** [comment] 2016-06-30 00:04
@olback This is interesting as I play both those games and the hotkeys and media keys work correctly.  Possibly a keyboard / driver specific issue.

Can you attempt to confirm using a different keyboard or a different media player.

**Comment by joergi77** [comment] 2016-06-30 09:02
They are not working on Linux (Ubuntu 14.04 64 Bit ) with a thinkpad keyboard 
(In Spotify I have to press FN and  right/left arrow for last/next song, FN + Down Arrow for play/pause, and FN + Up Arrow for stop - as written on my keyboard)

**Comment by MarshallOfSound** [comment] 2016-06-30 09:32
@joergi77 The linux issue is known and will be fixed in the next release.  It was a regression caused by the `3.2.5` update

**Comment by olback** [comment] 2016-06-30 10:22
@MarshallOfSound It works with Spotify just fine. I will test it with another keyboard as well.

**Comment by olback** [comment] 2016-06-30 10:35
@MarshallOfSound Got cs:go to work just by restarting my pc.
Tested with another keyboard. Still not working in GTA. This isn't a huge problem. Don't bother fixing if I'm the only one having this issue.

Also, i love the program, you guys did a great job on it :)

**Comment by joergi77** [comment] 2016-06-30 11:07
@MarshallOfSound - allright. I managed it know with selfconfiguration of some other hotkeys....  just wanted to let you know

**Closed** 2016-06-30 22:37 UTC
