### ISSUE TITLE
Uncaught Exception: UNKNOWN: unknown error, open 'C:\Users\Conor\AppData\Roaming\Google Play Music Desktop Player\json_s

### ISSUE THREAD

**Issue by conordb** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1150] opened 2016-06-05 11:24 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.2.4
**Time:** Sun Jun 05 2016 21:24:31 GMT 1000 (AUS Eastern Standard Time)

#### Error:
*UNKNOWN: unknown error, open 'C:\Users\Conor\AppData\Roaming\Google Play Music Desktop Player\json_s*
```js
Error: UNKNOWN: unknown error, open 'C:\Users\Conor\AppData\Roaming\Google Play Music Desktop Player\json_store\playback.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1234:33)
    at PlaybackAPI._save (C:\Users\Conor\AppData\Local\GPMDP_3\app-3.2.4\resources\app\build\main\utils\PlaybackAPI.js:101:22)
    at PlaybackAPI._setTime (C:\Users\Conor\AppData\Local\GPMDP_3\app-3.2.4\resources\app\build\main\utils\PlaybackAPI.js:170:12)
    at EventEmitter.<anonymous> (C:\Users\Conor\AppData\Local\GPMDP_3\app-3.2.4\resources\app\build\main\utils\PlaybackAPI.js:56:15)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (C:\Users\Conor\AppData\Local\GPMDP_3\app-3.2.4\resources\electron.asar\browser\api\web-contents.js:130:25)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by jostrander** [comment] 2016-06-05 16:09
I think this might be caused by the same thing that caused #1142. The stack traces look identical. Error `122` in the other thread I think is labeled something to the effect of `quota reached` but it varies based on the kernel in use. Maybe were writing too fast to the playback API file?

**Comment by MarshallOfSound** [comment] 2016-06-06 11:39
This error I have seen before on Windows machines due to strange installation permissions.  I.e. Someone installing the program as Admin and then running as a standard user.

I'm closing this for now because #1142 will track it if it is a write issue and if it isn't then it's the permissions thing mentioned above

**Closed by MarshallOfSound** 2016-06-06 11:39 UTC
Labels: Automatic-Issue-Report
