### ISSUE TITLE
Fails to start on Fedora 29

### ISSUE THREAD

**Issue by SpacemanPete** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3416] opened 2018-11-08 01:57 UTC
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

GPMDP fails to start on Latest Fedora 29. Seems to be a segfault complaining that package isn't signed with the proper key. See the attached output of journalctl.

**OS:**
Fedora 29 64-bit
Kernel : 4.18.16-300.fc29.x86_64

**GPMDP Version:**
4.6.1.x86_64.rpm

**Issue Descriptions:**
Installed ok using terminal, but application will not start.  I greped thru the journalctl file and found reference to the application not being signed with the proper key. I'm unable to start the app in order to generate the debug zip log as per FAQ instructions.

**Steps to Reproduce:**
On a Fedora 29 64-bit system with kernel 4.18.16-300.fc29:
  - download google-play-music-desktop-player-4.6.1.x86_64.rpm.
  - in terminal run: `sudo dnf localinstall google-play-music-desktop-player-4.6.1.x86_64.rpm`
  - Try to open th application using the Gnome Application menu
  - in terminal run: `journalctl -b | grep 'google-play-mus'` to find the resulting error messages attached here: [gpmdp_journalctl.log](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/2559967/gpmdp_journalctl.log)

Hopefully, I provided all the relevant info y'all need. Great work on the app guys! Let me know what else I can provide to help this issue along.

**Comment by MarshallOfSound** [comment] 2018-11-08 02:39
>  I have checked that there are no issues with similar or the same content

GitHub has a wonderful new feature to help prevent you making duplicate issues 😄 

![image](https://user-images.githubusercontent.com/6634592/48174337-b69be800-e35b-11e8-8404-c7dd133de828.png)

Duplicate of #3408

**Closed by MarshallOfSound** 2018-11-08 02:39 UTC

**Comment by SpacemanPete** [comment] 2018-11-10 03:19
Hi @MarshallOfSound, thanks for the reply. 

I did do a search and read through those issues. I created a new one because the cause of the segfault error (_complaining that package isn't signed with the proper key_) appears to be a new problem not previously mentioned in the other bug reports. Perhaps I was not as clear in my wording, sorry for that.

**Comment by zerkz** [comment] 2018-11-12 18:06
@SpacemanPete i fixed this already --- it was present in my ubuntu 18.10 installation but the same fix should fix the segfault in fedora 29. https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3413
