### ISSUE TITLE
Keyboard Media Keys Stop working after a while? [OS X 10.11.4][3.4.0]

### ISSUE THREAD

**Issue by jwmann** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1433] opened 2016-08-09 14:42 UTC
This has happened to me a few times but I thought it was an anomaly because I've never had this issue since it first came out. It happens consistently now, even after some computer restarts.

I'm not sure the exact amount of time it takes for them to stop working because I leave my computer on when I go to bed. When I wake up, the media keys (Pause, Play, Next, Previous) don't trigger anything. If I Quit GPMDP and start it again, the media keys work perfectly fine.

Very strange behaviour. How would you even go about troubleshooting this?

**Comment by MarshallOfSound** [comment] 2016-08-09 15:11
Can you try opening the app.  Manually sleeping your computer.  Waiting about 5 minutes and waking it up again.

That should test if it is time based (garbage collection) or sleep based

**Comment by jwmann** [comment] 2016-08-09 15:19
I actually have sleep disabled on my computer. The only thing that changes is my display turns off after 10 minutes but that doesn't seem to affect it.
http://jwm.d.pr/E7Lm/4IYXkupH

**Comment by spiliopoulos** [comment] 2016-08-09 17:28
@jwmann Did you open chrome or any other app that might be intercepting the media keys event?
@MarshallOfSound I could spend some time looking for this, but I would appreciate a brief (if it takes more than 5 minutes of your time skip it) description of how you handle media keys in Mac OS.

**Comment by spiliopoulos** [comment] 2016-08-09 17:35
@jwmann If you open chrome and you happen to have the Google Play Music Player plugin installed, you are probably the victim of Chrome intercepting your media player keys. Do not despair! You can just go to the extensions tab, press keyboard shortcuts on the bottom right and select for each media key to be active only when chrome is focused.

**Comment by jwmann** [comment] 2016-08-09 17:50
It's certainly _possible_ that GPM extension hijacked the media keys but I've always had this extension installed and have never had an issue until the last couple weeks or so. My chrome remains open and untouched throughout the night.

That being said, I removed the extension just in case and will let you know if the problem persists.

**Comment by MarshallOfSound** [comment] 2016-08-09 22:13
@jwmann @spiliopoulos It's certainly possible that upon "waking up" that their is a race condition to get those media hotkeys and Chrome is winning every time 😢 

I'll mark this as unconfirmed and we'll see how you go 👍

**Comment by MarshallOfSound** [comment] 2016-08-11 07:53
@jwmann Any update?  Has it happened since you got rid of the extension?

**Comment by CS-5** [comment] 2016-08-11 21:03
I noticed this issue as well (on Windows 10), I am aware of the key hijacking bug, but I removed the Google Play music chrome app and there was no change. I did not have this issue previously.

**Comment by purag** [comment] 2016-08-17 21:16
I had this issue as well. Fixed by unassigning the keyboard shortcuts for the Play Music extension:

![](http://i.imgur.com/YdISREz.png).

Make sure you do this for any GPM extension. I also had Prime Player that was capturing the media keys globally.

**Comment by MarshallOfSound** [comment] 2016-08-19 05:46
Confirmed as being a race condition between Chrome and GPMDP.  Uninstall the GPM Chrome Extension to fix this issue.

**Closed by MarshallOfSound** 2016-08-19 05:46 UTC
Labels: awaiting response, OS X, Unconfirmed

**Comment by skypanther** [comment] 2017-06-30 14:17
I see now that this is in your FAQ. Though, I've never come to this repo till today when I got so frustrated about my media keys working, then not working. I never made the connection till I read this thread.

If I launched/restarted Chrome after GPMDP, then Chrome would grab the media key bindings. If I launched GPMDP after Chrome, the keys worked. So my "fix" when there were issues has been to quit/re-open GPMDP. Now I know why that "fixed" the problem.

The issue and solution should be more prominently displayed in the app's UI. I'm going to guess a lot of your users don't think to find your GitHub page and its FAQ or even fewer would dig through closed Issues to find the solution.

How about a banner / div in the UI that shows up when the media keys aren't under this app's control? Of course, that presumes you could grab them back without restarting the app. Or, an alert or toast (desktop notification) when GPMDP loses control of the media keys? Something, just not buried here please.
