### ISSUE TITLE
Slack Integration breaks switching from YTM to GPM, "null - null" displays in YTM

### ISSUE THREAD

**Issue by rileym94** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3898] opened 2020-10-14 15:33 UTC
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** Windows 10, v. 1909

**GPMDP Version:** 4.7.1

**Issue Descriptions:** When Slack integration shows what is playing in your status through YTM, the text comes across as "null - null"

**Steps to Reproduce:** With existing slack integration, switch to YTM, play a song, wait for slack status to update. 
![YTM displays null](https://user-images.githubusercontent.com/28606370/96010147-1a13d780-0e07-11eb-8c58-72e5cca3a04f.png)
If you switch to GPM, the artist and title will display. If you switch back, it will still display the artist and title from GPM, even after stopping, changing the song, etc.
![Showing GPM song](https://user-images.githubusercontent.com/28606370/96010141-197b4100-0e07-11eb-8f30-a2b8993c923b.png)

**Comment by jostrander** [comment] 2020-10-14 15:36
Duplicate of #3888, that is the root cause and is fixed in master but not released.

**Closed by jostrander** 2020-10-14 15:36 UTC
