### ISSUE TITLE
Issue: Stuck in "Improve Your Recommendations" page

### ISSUE THREAD

**Issue by aexley** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2393] opened 2017-03-29 23:32 UTC
**OS:**
Windows 10 Pro Build 14393

**Issue Descriptions:**
Went in to Google Play's "Improve Your Recommendations" section to select the genres and artists I like. After finishing this and pressing the "Finish" button it just stays at the same page. There is no exit capability. Even going "back" or closing the app you are still stuck at this page.

**Steps to Reproduce:**
click on hamburger
Go to "Settings/General/Improve Your Recommendations"

**Comment by MarshallOfSound** [comment] 2017-03-31 08:42
Cannot reproduce on any device I own (macOS / linux VM's / windows), it was probably a temporary issue on googles side of things and you got unlucky 😆 

Closing out as unreproducible / fixed.  If you still have this issue please comment below 👍

**Closed by MarshallOfSound** 2017-03-31 08:42 UTC
