### ISSUE TITLE
Uncaught Exception: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Joel-T** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1290] opened 2016-07-08 16:13 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.3.0
**Time:** Fri Jul 08 2016 12:12:46 GMT-0400 (Eastern Daylight Time)

#### Error:
*Cannot read property '1' of null*
```js
TypeError: Cannot read property '1' of null
    at Request._callback (C:\Users\Joel\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\main\features\core\lyrics\source_lyricsFreak.js:9:1201)
    at Request.self.callback (C:\Users\Joel\AppData\Local\GPMDP_3\app-3.3.0\resources\app\node_modules\request\request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Joel\AppData\Local\GPMDP_3\app-3.3.0\resources\app\node_modules\request\request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Joel\AppData\Local\GPMDP_3\app-3.3.0\resources\app\node_modules\request\request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-07-08 16:25
Closing this automatically reported issue as a duplicate of #1281

**Closed by GPMDP-Magical-Unicorn** 2016-07-08 16:25 UTC
Labels: Automatic-Issue-Report
