### ISSUE TITLE
Cinnamon sound applet low res album art and missing progress bar

### ISSUE THREAD

**Issue by wengole** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#919] opened 2016-04-08 09:46 UTC
Thanks for your help so far.

Two (relatively) minor things wrong with what the cinnamon applet shows is a lack of track progress bar, and the album art is low res.

The former I believe is another case of incorrect typing of the track length, as #906 had snippets of dbus data sent from Banshee and GPMDP and there was a definite discrepancy in the type.

I'm not sure the latter is even fixable, unless Google provides multiple image sizes.

**Comment by jostrander** [comment] 2016-04-08 10:58
The progress bar showing up is an issue with the applet itself. If you don't mind, take a look into the JS for the applet.
The one I'm familiar with is here:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/sound%40cinnamon.org/applet.js#L25
but yours may be different.
Currently it looks like there is a whitelist for players that support the progress bar, and its hard coded. Can you check this out on your system? The path might be similar.

However the progress bar once whitelisted doesn't work, so it probably does need a datatype adjustment. I'll look into that.

The latter can probably be fixed. What size would you need? I can probably safely provide around 1024x1024px, but I'd prefer to keep in in the middle around 512x512 to keep the size low. Currently I believe its 100px;

**Comment by wengole** [comment] 2016-04-08 11:00
I'll look into the progress bar issue.

Image size, I think 512px would indeed be best, at least double what it is now though.

**Comment by jostrander** [comment] 2016-04-10 00:38
Added 300px album art, 512 seemed a bit excessive.

**Comment by jostrander** [comment] 2016-04-10 01:18
As far as the track length, unfortunately it looks like there's no way to marshall into int64 from Javascript as Javascript doesn't support 64 bit integers natively.

**Comment by MarshallOfSound** [comment] 2016-04-10 01:23
@jostrander That 64bit integer thing should probably be handled by a c++ native module (node-dbus) probably.

**Comment by jostrander** [comment] 2016-04-10 01:38
v8 doesn't support checking for 64 bit integers it appears, so even a native module won't work in this case, but maybe I'm wrong as I don't play with C++ too much.

http://bespin.cz/~ondras/html/classv8_1_1Value.html

**Comment by MarshallOfSound** [comment] 2016-04-10 01:42
I'm pretty sure that `Integer::Value()` returns a 64bit integer in V8

**Comment by jostrander** [comment] 2016-04-10 02:26
The issue is that the marshaller in node-dbus doesn't support 64 bit integers because as far as I can tell the v8::Value object has no method to check for 64 bit integers. See https://github.com/Shouqun/node-dbus/blob/master/src/encoder.cc#L34

First check is for Uint32, then Int32, then Number, which returns type Double. If I put a 64 bit integer it returns a double.

**Comment by wengole** [comment] 2016-04-12 10:24
@jostrander Turns out that's the exact applet I am using, and that whitelist is identical to what it's showing on github. Don't know if that helps.

**Comment by jostrander** [comment] 2016-04-19 16:20
Upstream issue: https://github.com/Shouqun/node-dbus/issues/126

**Comment by MarshallOfSound** [comment] 2016-05-03 02:23
@jostrander @wengole Just going through the issues, what is the situation for this issue.  Fixed / WIP / Not Touched?

**Comment by jostrander** [comment] 2016-05-03 02:25
WIP, I need to update node-dbus to only use 64bit auto marshalling I think, which means we will only be able to use our branch for future use.

**Comment by MarshallOfSound** [comment] 2016-06-30 05:58
@jostrander @wengole Follow up on this, is there actually a valid solution we can implement and use

**Comment by jostrander** [comment] 2016-06-30 22:59
Album art is fixed, track progress is not. Track progress will take a bit more work, if it will work at all. I haven't been able to test and implement a fix. Technically its an upstream issue, and we can probably close it as such.

**Comment by MarshallOfSound** [comment] 2016-06-30 23:05
Yay, issue clean up for the win

**Closed by MarshallOfSound** 2016-06-30 23:05 UTC
Labels: Linux
