### ISSUE TITLE
YTM only : Problem with audio device after restart.

### ISSUE THREAD

**Issue by tstocchetti** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3366] opened 2018-09-24 19:20 UTC
### **OS:**
W10 / x64

### **GPMDP Version:**
4.6.1

### **Issue Descriptions:**

_**Bad audio device source**_
- On restart application, the last audio device selected its not using. The application use default device on windows sound.
- In the options, the audio device is nice selected, you must select him again for ear the sound on the good device.

--- 

_**Audio device menu is loading**_

- After application restart, if you launch a music, the minimize menu tray for audio device display message "Loading Device....".
![audio_device](https://user-images.githubusercontent.com/43551176/45973218-1bb2ad00-c03e-11e8-87ab-13a7ee5913f7.png)

### **Steps to Reproduce:**
_**Bad audio device source**_
Just close application and restart.

--- 

_**Audio device menu is loading**_
On minimize menu tray, click  "Desktop settings" and close it, now the "Audio device"  on minimize menu tray display all device.

### **More informations :GPMDP behavior vs YTMDP**
- In GPMDP after application restart, the correct audio source is use. 
- In GPMDP , the audio device menu display all device just after the music playing.

PS : It's possible to have labels "GPMDP" and "YTMDP" for improve filtering on issues ?

🥇 Best regards, and congratulation for this nice app.

**Comment by MarshallOfSound** [comment] 2019-04-23 03:04
Duplicate of #3504

**Closed by MarshallOfSound** 2019-04-23 03:04 UTC
