### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by Dazag** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#815] opened 2016-03-28 17:17 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Mon Mar 28 2016 19:16:52 GMT 0200 (Hora de verano romance)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\david\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\david\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\david\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\main\features\core\controlBar.js:10:45)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\david\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\api\lib\web-contents.js:134:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by Dazag** [comment] 2016-03-28 17:20
if you need any other information I can provide, just let me know. It always appear everytime I resize the app size, but I can't see any problem. Actually, I find it very uncomfortable that I can't close the error message... It stays at the bottom left corner of the screen forever, unless I click on it.

**Comment by Dazag** [comment] 2016-03-28 17:26
Not showing anymore. I did marked the option Use system windows borders > Restart app. Unclick option > Restart app again. Everything works just perfect

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-28 17:27
Closing this automatically reported issue as a duplicate of #470

**Closed by GPMDP-Magical-Unicorn** 2016-03-28 17:27 UTC
Labels: Automatic-Issue-Report, duplicate
