### ISSUE TITLE
Fail to load music library on mac os

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3743] opened 2019-12-20 18:22 UTC
**Checklist:**

* [ x ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ x ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ x ] I have double checked and can reproduce the issue

**OS:**
Mac OS
**GPMDP Version:**
4.6.1 distributed on homebrew

**Issue Descriptions:**
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3989636/debug_info.zip)
After logging in to the google account, it shows "loading music library" and freezes.
<img width="1199" alt="Screen Shot 2019-12-20 at 1 22 19 PM" src="https://user-images.githubusercontent.com/40440788/71281400-c4c48200-232b-11ea-8a0b-9fc95a745509.png">

**Steps to Reproduce:**
Install using homebrew
login google account

**Comment by JohnRThomas** [comment] 2019-12-20 18:40
" I have checked that there are no issues with similar or the same content"
No offense, I don't think that's true:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3741
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3660
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3610

Looks like a duplicate of these issues.

**Closed** 2019-12-20 18:43 UTC
