### ISSUE TITLE
Windows 10 media key skips multiple tracks

### ISSUE THREAD

**Issue by jcaw** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3061] opened 2018-03-22 22:06 UTC
Windows 10 Build 1709

4.5.0

Pressing the "Next Song" key in Windows 10 skips multiple tracks.

1) Launch App
2) Play song
3) Use physical key to skip song
4) ERROR: Skips two songs

**Comment by alexknuckles** [comment] 2018-03-24 13:46
They know about it, it's oddly just not a priority. #2364

**Comment by MarshallOfSound** [comment] 2018-03-24 14:08
Closing as duplicate of #2364 

@alexknuckles To be realistic, I have many priorities and unfortunately nowadays GPMDP isn't at the top of my list.  If someone PR's in a fix for this I will gladly review and release it but no one seems to be willing to do it 😄 I can't really spend time fixing an issue I don't have 😆

**Closed by MarshallOfSound** 2018-03-24 14:08 UTC

**Comment by sudomann** [comment] 2018-09-19 06:50
Wait, so @MarshallOfSound somehow this is not happening to you? How so??? I have been using GPDMP since version 4.0 or so, and have had skipping issues all the way through a surface book 1, surface book 1 with performance base, surface book 2 13 inch, and now surface book 2 15 inch. I have been through various keyboards during that time as well, it has persisted. 

On a side note, these buggers thumbing down your reply can f right off. Like you're supposed to spend all your time fixing up things for them, while they use it free.

**Comment by MarshallOfSound** [comment] 2018-09-19 06:53
@sudomann I don't know, maybe I'm really lucky.  But my keyboard media controls only ever jump one song, I actually spent a significant amount of time last year trying to repro this with multiple keyboards across all the windows machine I had at the time, didn't see it on any of them.

> On a side note, these buggers thumbing down your reply can f right off. Like you're supposed to spend all your time fixing up things for them, while they use it free.

I super appreciate this 😄 🎉

**Comment by jespersh** [comment] 2018-09-19 12:03
The surface book not coming with a skip song button on its own keyboard, then I'd ask what keyboard(s) you are using?

**Comment by sudomann** [comment] 2018-09-23 03:51
@jespersh  Corsair k70, corsair straffe, razer blackwidow, dell `somethingSomething` and a couple of other forgotten makers of membrane keyboards. All having media control keys and exhibiting the same behavior. I dont keyboard cause the issue. I only mentioned the surface book to indicate i'd experienced the issue on multiple computers accross multiple versions. I don't know anything about windows development, but I can only imagine its something with the way media service is implemented in GPMDP. When I have media in Hulu & Spotify, i can click arrow on the media pop up to hop between controlling either program. The same holds true if I launch some media in `Movies & T.V.`. I wonder how they implemented that so nicely. I've also noted VLC player allows you to control playback with media control buttons when the window is active in the foreground and ignores it otherwise. One would think its straightforward to implement, but i guess not.

**Comment by Nightwielder1** [comment] 2020-07-23 18:23
I fixed this issue by disabling the option to have media displayed in windows volume media controls. Had to switch back from YTM to change the settings. (I like GPM better, but since it's dying...)
