### ISSUE TITLE
Linux Version Notifications showing up as pop up windows.

### ISSUE THREAD

**Issue by neltnerb** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1620] opened 2016-09-09 23:05 UTC
Ubuntu 16.04
Chrome Version 53.0.2785.92 (64-bit) unless you packaged it with the desktop app. I'm assuming you're using the default installed version of Chrome, so this is what normal chrome displays in about.

Since a week or two ago, song changes produce a full on pop up window that I have to exit by clicking rather than the integrated short notifications as before.

It takes focus from the program I'm working in at the time, so is pretty annoying. I couldn't find a way to just disable desktop notifications on song changes in the settings, but that would suffice for now if it were doable.

So I guess the feature request would be having one for disable desktop notifications. And the bug would be that the behavior changed recently.

**Comment by MarshallOfSound** [comment] 2016-09-10 04:48
@neltnerb What version of the app do you have installed?  This issue was fixed upstream in Electron a loooong time ago.

Also we do package Chromium with the application

**Comment by MarshallOfSound** [comment] 2016-09-10 06:13
>  I couldn't find a way to just disable desktop notifications on song changes in the settings, but that would suffice for now if it were doable.

The desktop notifications are controlled from Google Play Music settings (not the app settings).  I'm closing this out as I just tried on Ubuntu 16.04 and I can't reproduce the popups, I get proper notifications.

@jostrander Can you try this out just to double confirm

**Closed by MarshallOfSound** 2016-09-10 06:13 UTC
Labels: awaiting response, Unconfirmed

**Comment by neltnerb** [comment] 2016-09-14 05:34
Eventually found the version in /usr/share/google-play-music-desktop-
player/version which contained the string v0.36.7

Not entirely sure if that's a typo or if it's just an old version. I
did find notification settings upstream in the core google settings and
managed to disable them entirely. I'll download the current one and see
if it changes.

Thanks,
Brian

**Comment by MarshallOfSound** [comment] 2016-09-14 05:43
>  v0.36.7

That is an ancient version, like almost 7 months old.  The bug was fixed since then, updating should resolve your issue 👍

**Comment by neltnerb** [comment] 2016-09-14 05:50
Ah. Do you actually host a repository to automatically keep it up to
date? It's been a while since I had to manually update packages so I
forgot entirely that it was a thing that might be needed.

For what it's worth, I installed the new version and now it just fails
silently when I run it either from the launcher or from a terminal. I
tried putting --help and --verbose but these switches didn't have an
effect. I tried killing chrome to make sure it was a fresh session, and
that wasn't quite enough to make it launch.

Maybe just needs a reboot though, so probably not worth reading much
into since it might fix itself.

Somewhat curious how it managed to work properly and then stop working
when I wasn't updating it! The vagaries of software I suppose. Must
have been some upstream API change that happened to coincide with the
issue becoming apparent to me.

**Comment by MarshallOfSound** [comment] 2016-09-14 05:55
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/Installation_On_Debian.md

We do have an apt repo 👍

**Comment by neltnerb** [comment] 2016-09-14 05:59
Thanks! Great work =)
