### ISSUE TITLE
Windows Multimedia Keys on 4.1.1 

### ISSUE THREAD

**Issue by ellsclytn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2107] opened 2017-01-15 10:56 UTC
**OS:** Windows 10 Pro 64-bit

**Issue Descriptions:** Multimedia track navigation keys misbehaving.

**Steps to Reproduce:** Pressing forward (on the keyboard) will result in two tracks skipped. Pressing previous (on keyboard) a few times may entirely freeze the application UI (I'm not certain on the steps to cause the previous track lockup behaviour).

This has been occurring ever since the Windows Media overlay integration was brought in.

**Comment by MarshallOfSound** [comment] 2017-01-15 10:59
Kind of a duplicate but I'll let it slide as it was more an off-topic discussion in #2100 but I'll post my idea / response here.

> I'm thinking as a solution to the "double hit" issue I can detect to commands in a short interval, and if it happens 3 times in a row pop up a warning that allows users to disable the global media hotkeys but retain the windows service keys. Will look into it more at some point

**Comment by PazerOP** [comment] 2017-01-17 02:11
In addition, it's now impossible for me to pause/unpause via my keyboard's media keys, as it just instantly pauses then unpauses.

**Comment by Oreonipples** [comment] 2017-01-17 06:29
I am experiencing the same thing with 4.1.1 Play and pause seem to double, skip doubles as well. If the GMPDP window is primary it sometimes behaves normally. The remote app has no issues at all.

**Comment by kbrohkahn** [comment] 2017-01-17 13:15
That's odd, play/pause works fine for me but skips are doubled. 4.1.1

**Comment by PazerOP** [comment] 2017-01-17 18:03
Interesting, the behavior seems to be semi-random. If it matters at all, I was playing Fullscreen Team Fortress 2 while GPMDP was on my second monitor.

**Comment by michael-hart** [comment] 2017-01-21 16:12
I have found that play/pause is fine, but skipping forwards/backwards consistently double skips. I've also found that the system crashes, but I've yet to identify what causes it - too many tracks skipping? Skipping a track while the Windows interface pops up?

**Comment by Tommy544** [comment] 2017-01-23 00:57
I have the same problem. When GPMDP is in focus, the play/pause button works as expected. If the window looses focus, pressing play/pause seems to be registered twice and so the song is paused and immediately resumed. I am however able to pause the track by either pressing the pause button multiple times or long pressing it. It doesn't work consistently though. The skip forward button skips 2 tracks regardless of the window focus.
Everything worked fine before Windows Media overlay integration.

**Comment by KrofDrakula** [comment] 2017-01-23 10:11
I can confirm the same thing @Tommy544 reported; when I skip songs without the Windows Media overlay appearing, it works fine, but using media keys after the WM overlay appears, it consistently locks up the player and it doesn't respond to user interaction, but the current track keeps playing. I have to manually kill the process and restart for it to work until the next occurence.

**Comment by KytechN24** [comment] 2017-01-24 06:38
I'm also experiencing this issue. Play/Pause works fine, but skipping forward or back jumps two tracks.

**Comment by MarshallOfSound** [comment] 2017-01-24 06:50
Guys I'm going to be locking this issue as a solution has already been implemented pending release and all the "me too" comments simply fill up my inbox 👍 

Watch out for `v4.1.2`

**Comment by MarshallOfSound** [comment] 2017-01-29 08:24
Actually... this has been fixed 😆 Closing out

**Closed by MarshallOfSound** 2017-01-29 08:24 UTC
Labels: Bug, Windows
