### ISSUE TITLE
Window controls have strange issue - Windows 7 64bit

### ISSUE THREAD

**Issue by SourceCode** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#137] opened 2016-01-08 17:00 UTC
I just installed the latest build and for some reason the interface buttons in the top right corner want to pop-out the original default windows controls over the skin.  They also pop-out strangely.

![gmpifacebug](https://cloud.githubusercontent.com/assets/55036/12203867/095db9ac-b5e6-11e5-81c8-b52d3a0b280e.jpg)

**Comment by MarshallOfSound** [comment] 2016-01-08 20:11
Duplicate of #31

**Closed by MarshallOfSound** 2016-01-08 20:11 UTC
