### ISSUE TITLE
Album art crashes player on 4k display

### ISSUE THREAD

**Issue by SourceCode** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1502] opened 2016-08-20 17:24 UTC
**OS:** Windows 10

**Issue Descriptions:** Album art crashes player on 4k display when clicking it in the bottom right corner to display it fullscreen in app.

**Steps to Reproduce:** 
- Setup 4k display
- Load a track with album art
- Set the album art to fullscreen
- Let it do its minor animation
- Within 5-60 seconds the player will stop playing , the screen goes black, and becomes unresponsive.
- The Windows window around the app is still responsive with minimize, quit, etc.  It is just the contents of the app that go away.  (Assuming this is some sort of electron style app which makes that possible vs the entire application locking up)

I am using 2x Nvidia 1080's in SLI with HB Bridge on x99 chipset. (EVGA X99 FTW) with Acer Predator 4k displays.  No other graphical issues in other programs. 

This is also a fully fresh install of windows 10, new video cards, monitors, etc all during that install.  So there are no weird lingering driver issues.

Unfortunately I only have a single machine with 4k setup so I can't reproduce it elsewhere, it seems to work fine at 1080p.

Thank you for your help in advance.

**Comment by MarshallOfSound** [comment] 2016-08-21 15:14
This will be a Chromium rendering issue which is out of our control.

Hopefully it's on their radar and will be fixed in an upcoming chromium release (which will then filter its way back to us)

**Closed by MarshallOfSound** 2016-08-21 15:14 UTC

**Comment by SourceCode** [comment] 2016-08-21 17:01
Awesome - I appreciate the follow up.  I'm actually pretty familiar with Chromium bug reporting so I'll head over there and review/report if needed.  Thank you again for your hard work on this project.

**Comment by MarshallOfSound** [comment] 2016-08-21 17:07
@SourceCode Thanks

The other issue might be that two 1080's only equals 2160.  Which isn't 4K.  😆

**Comment by MarshallOfSound** [comment] 2016-08-21 17:07
*That comment was intended to be a joke please don't take it seriously*

**PLEASE**
