### ISSUE TITLE
Taskbar title shows wrong artist

### ISSUE THREAD

**Issue by ajmeese7** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3425] opened 2018-11-22 14:56 UTC
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:** Windows 10

**GPMDP Version:** 4.6.1

**Issue Descriptions:** The application title on the Windows taskbar shows the artist of the previous song rather than the current artist (for YouTube Music). This happened after I disliked a song on the playlist.

**Steps to Reproduce:** Listen to a playlist and look at the taskbar name. You have to dislike a song on the playlist for it to happen.

For example, this shows Sheck Wes as the artist instead of Ellie Goulding:

![image](https://user-images.githubusercontent.com/17814535/48909595-51ec8d00-ee33-11e8-83a8-4b0b895d051c.png)

After I clicked back up a song, it did the same thing, except it showed Ellie instead of Sheck:

![image](https://user-images.githubusercontent.com/17814535/48909714-99731900-ee33-11e8-828f-7382b63a37c4.png)

**Comment by dangbee** [comment] 2018-11-23 10:32
The API also has this issue.

**Comment by IotaSpencer** [comment] 2018-12-24 01:57
I'm making a mpris dbus controller for linux via a rubygem, and I'd really love for this to be fixed so that the current/np command is actually right, because right now only the title is right, the artist is always the last played artist instead of the current. so please.

**Comment by MarshallOfSound** [comment] 2018-12-24 02:00
Duplicate of #3180

**Closed by MarshallOfSound** 2018-12-24 02:00 UTC
