### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by jcacosta25** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#847] opened 2016-03-30 16:59 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.1.0
**Time:** Wed Mar 30 2016 10:46:47 GMT-0600 (Central Standard Time (Mexico))

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\juank\AppData\Local\GPMDP_3\app-3.1.0\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:18:9.
    at BrowserWindow.callIntoRenderer (C:\Users\juank\AppData\Local\GPMDP_3\app-3.1.0\resources\atom.asar\browser\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by MarshallOfSound** [comment] 2016-03-30 20:40
OK @jcacosta25 how did you make this one appear?

Do you remember exactly what you did before the error popped up?

**Comment by nilsjha** [comment] 2016-04-05 14:39
@MarshallOfSound In my case, at issue #861 (a duplicate of this issue) the problem occurs when I'm adjusting the audio level with the volume keys on my HP multimedia keyboard (model KB 38211). The level adjusts accordlingly in Windows ( as normal ), but the UI for GPMDP reports an uncaught exception if the window of GPMDP is selected in Windows..

The problem is not really a problem, but more sort of annoying as the error message shows every single time I'm adjusting the volume with the keyboard.

**Closed** 2016-04-08 01:24 UTC
Labels: Automatic-Issue-Report
