### ISSUE TITLE
Uncaught Exception: listen EADDRINUSE 0.0.0.0:5672

### ISSUE THREAD

**Issue by diegomelo182** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1140] opened 2016-06-01 23:57 UTC
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.0.1
**Time:** Wed Jun 01 2016 20:56:46 GMT-0300 (BRT)

#### Error:
*listen EADDRINUSE 0.0.0.0:5672*
```js
Error: listen EADDRINUSE 0.0.0.0:5672
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:476:9)
    at process._tickCallback (node.js:382:17)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-06-02 00:07
Closing this automatically reported issue as a duplicate of #325

**Closed by GPMDP-Magical-Unicorn** 2016-06-02 00:07 UTC
Labels: Automatic-Issue-Report
