### ISSUE TITLE
Character Error Portuguese (pt-br)

### ISSUE THREAD

**Issue by BrMBr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1518] opened 2016-08-23 15:33 UTC
**OS:** Windows 10

**Issue Descriptions:** See attached image. Accented characters not properly showing.

**Steps to Reproduce:** n/a
![ashampoo_snap_2016 08 23_12h23m42s_001_chrome legacy window](https://cloud.githubusercontent.com/assets/21200866/17898221/5361357e-692d-11e6-815b-205320a20053.png)

**Comment by MarshallOfSound** [comment] 2016-08-23 15:34
This appears to be an issue with your system fonts?  Do other programs (in particular chrome) support / render these characters correctly.

**Comment by BrMBr** [comment] 2016-08-23 15:45
Nope. This only happens when using GPMDP.

**Comment by MarshallOfSound** [comment] 2016-08-23 15:49
Ah, looks like I need to pull in an extended verson of Roboto to get these characters

**Comment by m45t3r** [comment] 2016-09-08 19:02
Happens in Linux too:

![tela copiada como 2016-09-08 16-00-58](https://cloud.githubusercontent.com/assets/844343/18362785/91502d60-75dd-11e6-9c7e-cb7007199291.png)

Note that it only happens in the strings from gmpdp itself, the strings from Google Play Music webpage shows fine.

**Comment by MarshallOfSound** [comment] 2016-09-09 19:22
This issue has been added to the `4.0.0` milestone.

**What does this mean?**
It means that the next major release *should* contain this feature / bugfix.  If you are responsible for this issue please ensure that it is fully up to date to give me the best change of implementing / fixing what needs to be done.

**What do you need to do?**
If the issue is tagged with "Awaiting Response" it means that I need something from you, be that more information or in some cases a PR with the issue resolution 👍 .  Just do whatever you can to help me sort it out.

**So when will this glorious `4.0.0` release come out?**
Who knows... 😆  The major component of `4.0.0` is a rewrite of **ALL** the renderer process code and logic into a React based toolkit that I am creating from scratch over in #1581 .  Subscribe there for more updates as `4.0.0` will not be released until that is merged.

**Closed** 2016-10-08 01:59 UTC
Labels: Bug, Hacktoberfest
