### ISSUE TITLE
No sound after pausing for more than a few seconds.

### ISSUE THREAD

**Issue by tubes42024** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2418] opened 2017-04-10 16:24 UTC
I did a quick search I didn't see anyone having the same problem that I am having.  When I pause the player for more that 20sec & then start playing again, it will start playing but there is no sound.  I have to close than resart it to regain sound.

-->

**OS:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by ma-git-me** [comment] 2017-04-10 16:36
I am seeing the same issue. It is not entirely consistent (sometimes the sound works when I resume after a long pause).
Windows 7 64-bit. All other sounds on the PC still work, and restarting to app restores functionality.

**Comment by MarshallOfSound** [comment] 2017-04-10 17:02
Can either of you replicate this behavior in Google Chrome?

**Comment by ma-git-me** [comment] 2017-04-10 17:30
I've never seen it happen in Chrome, and I used Chrome to listen to GPM for a long time (months) before I started using the Desktop Player a few weeks ago.

**Comment by ma-git-me** [comment] 2017-04-10 17:38
More info:
The last time the problem occurred (earlier today), I looked at the Windows Volume Mixer to see if maybe the volume for this app was too low or something.  The app did not appear in the mixer at all at that time.
After restarting the player, the player app does appear in the volume mixer (and the sound works again).

**Comment by tubes42024** [comment] 2017-04-10 18:04
No just tested it.  Had it paused for a few minutes hit play & the sound
came right back.

**Comment by MarshallOfSound** [comment] 2017-04-10 23:08
Can you guys try switch audio output device when the sound stops working, just toggle between devices and see if it comes back 👍

**Comment by tubes42024** [comment] 2017-04-12 12:49
Doesn't do a thing. Even tried plugging my headphones didn't change a thing.
One thing I did notice, I kept my "Volume Mixer" open and I could keep it
open pause & play to full extent but once I closed it paused it for a
little, no sound.  Reopen the mixer GPMDP is not shown. Close GPMDP reopen
pops back up in the mixer & has sound.

**Comment by ma-git-me** [comment] 2017-04-12 12:57
I have not been able to reproduce the issue since posting (it has always been intermittent for me, so this doesn't prove anything).
I had it paused overnight and this morning, before I started playing music again, I checked the mixer and GPMDP was not there.  I hit play, the music played (working properly) and the app showed in the mixer again.
Just trying to provide more info for troubleshooting.

**Comment by tubes42024** [comment] 2017-04-12 13:01
I've even uninstalled & reinstalled same problem.

**Comment by MarshallOfSound** [comment] 2017-04-12 14:06
Of course I can't find the comments now, but I saw reports for this issue in regular browsers on Reddit as well so I don't think this is limited to this player.  Probably some GPM A/B testing that went horribly wrong 👍 

Closing out until it becomes clear this is an us problem

**Closed by MarshallOfSound** 2017-04-12 14:06 UTC

**Comment by codingcarpenter** [comment] 2017-09-20 15:23
I am able to reproduce this by pausing the music playing, then trying to play anything with any sort of audio in Firefox. Especially Youtube videos. The app disappears completely from the mixer and no longer allows audio until it is restarted.
