### ISSUE TITLE
the program do crash always after the last update

### ISSUE THREAD

**Issue by BrunoMR** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3489] opened 2019-02-11 18:19 UTC
Three days ago, the GPMD always crashing while i to listening any music. It show up the message that not responding on windows 10. So i to need kill the process in task bar to it return to work it.

**Comment by jostrander** [comment] 2019-02-11 18:20
Duplicate of #3483

**Closed by jostrander** 2019-02-11 18:20 UTC
