### ISSUE TITLE
Can't use media keys when using Youtube Music

### ISSUE THREAD

**Issue by bitojoe** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3571] opened 2019-05-28 15:10 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Mac OS 10.14.4

**GPMDP Version:**
GPMDP 4.7

**Issue Descriptions:**
Recently ran into an issue where media keys don't work when using youtube music through the app. The media keys were working just fine at one point. I'm not sure if the keys stopped working when updating to 4.7 or if it was a server-side change from google that borked it. 

Also should note that the media keys work aye-okay while using Google Play Music.

**Steps to Reproduce:**
Mac menu bar > Youtube Music > play on a song.
While the song is playing, pressing the media keys do not pause, skip or rewind a track.

**Comment by kir4h** [comment] 2019-05-29 12:55
FYI: Working fine for me on macOS 10.14.5 with GPMDP 4.6.1. Using Logitech MK850.

**Comment by bitojoe** [comment] 2019-05-29 16:51
I'm on a 2014 macbook pro w/ built-in keys. I'll try updating to 10.14.5 and report back!

**Comment by pkoenig10** [comment] 2019-05-29 19:10
I think this is a duplicate of #3510

**Comment by bitojoe** [comment] 2019-05-29 20:03
Or did 4.7 (released April 23) include the necessary Electron update? I see that thread was closed April 22nd

I'll try completely uninstalling & re-installing and updating MacOS a little later.

**Comment by bitojoe** [comment] 2019-05-29 20:06
@pkoenig10 I should mention that I saw a lot of linux users comment about experiencing media keys not working but wasn't sure if it applied for mac users

**Comment by jostrander** [comment] 2019-05-29 20:07
That (pre)-release is broken altogether and should be taken down IMO. There were a bunch of modules that didn't compile correctly, at least on the linux side, and I assume other things are broken too such as this.

**Comment by kir4h** [comment] 2019-05-30 07:54
@bitojoe Just tried today with built-in media keys (Macbook Pro 2015) and also working

**Comment by pkoenig10** [comment] 2019-05-30 13:23
@kir4h I think the issue is only on (10.14) Mojave. My media keys were working correctly before upgrading and haven't worked since I upgraded. Are you on an older version of MacOS?

**Comment by kir4h** [comment] 2019-05-30 13:52
Nope, I'm on Mojave (latest patch though [10.14.5])

**Comment by bitojoe** [comment] 2019-05-30 17:27
Welp, I have no clue what the issue is...

Just updated to MacOS 10.14.5, Completely deleted the app (libraries, cache, everything), emptied trash, restarted, re-installed the app (4.7), and still having the issue where pause/play buttons specifically on Youtube Music do not work. 

The buttons do however work on Google Music! - I'm a little stumped

**Comment by kir4h** [comment] 2019-05-31 08:09
Maybe rolling back to 4.6.1 to see if that helps? (that's the version working for me)

**Comment by jostrander** [comment] 2019-06-01 16:42
@bitojoe does 4.6.1 work for you with YTM?

**Comment by bitojoe** [comment] 2019-06-04 15:38
@kir4h @jostrander - On 4.6.1, the media keys do indeed work! Now remind me, aren't there lyric / crashing issues on this version?

**Comment by jostrander** [comment] 2019-06-04 15:51
I believe so, yes. As a temporary fix you can use this workaround: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3483#issuecomment-462037350

**Comment by jostrander** [comment] 2019-06-13 00:52
Fixed by #3586

**Closed by jostrander** 2019-06-13 00:52 UTC
