### ISSUE TITLE
zooming out

### ISSUE THREAD

**Issue by godey4me** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2647] opened 2017-07-18 23:54 UTC
**OS:**
Windows 7 and windows 10 (GPMDP from windows store)
**Issue Descriptions:**
Elements on the page zooms out when you navigate Google play music
![2017-07-18_17-45-36](https://user-images.githubusercontent.com/19440061/28344619-f43b68d6-6be1-11e7-8448-e95b21206d9d.jpg)

**Steps to Reproduce:**
Lunch GPMDP. Use it for a couple of minutes. after a while page zooms out. Use Ctrl+0 to reset. Navigate, and repeat.

**Comment by jostrander** [comment] 2017-07-21 14:52
I can't reproduce this issue unfortunately. I don't even know that ctrl + 0 actually effects zoom in this application, unless I missed that update.

**Comment by MarshallOfSound** [comment] 2017-07-22 06:28
>  ctrl + 0 actually effects zoom in this application

It was implemented in the `4.0` series I think with the + and - shortcuts.  Regardless this is a non-issue (zoom on navigate glitches were fixed in an Electron update a while back)

**Closed by MarshallOfSound** 2017-07-22 06:28 UTC
Labels: Unconfirmed

**Comment by godey4me** [comment] 2017-07-22 14:14
Hmmm. I guess I will have to leave wit it. I am having this behavior on two systems, windows 10 at home and a windows 7 at work. Very strange.

**Comment by Nabla128k** [comment] 2018-02-08 08:57
Well I have zoom issue on win 7 with mini player. When I accidentally clicked "cascade windows" or one of these win manipulations in taskbar context menu - it resized miniplayer and miniplayer content zoomed in. Cannot find how to zoom out. Or at least reset the preferences! Help please.
See attachment
![clipboard01](https://user-images.githubusercontent.com/5609151/35963861-6787a316-0cb6-11e8-8413-51a0b5ea8e46.png)
