### ISSUE TITLE
Application closing at startup (3.0.0, x64) under Win7 x64 - Root Cause Russian Language

### ISSUE THREAD

**Issue by Namynnuz** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#200] opened 2016-03-05 13:43 UTC
Hello.
There's a bug. Inasmuch as this app has some really odd PE name:
Google%20Play%20Music%20Desktop%20Player.exe
There's no way to work with this properly under user profile (after loading a library, app suddenly minimizes to tray and the exits). Under admin it's fine (maybe cause of quotation of app path, thus %20, which is space symbol in percent encoding, might bring some pain on a system like Windows). Btw, the workaround is pretty simple: just rename a copy of PE without %20 symbol, like gpmdp.exe.
Hope this helps.

**Comment by MarshallOfSound** [comment] 2016-03-05 13:57
I'm sorry but that doesn't make much sense.  You shouldn't be launching that app.  You should be launching "Update.exe" with the correct parameters.  It should be making you desktop shortcuts and start menu shortcuts.  Use those

**Comment by Namynnuz** [comment] 2016-03-05 14:05
This is how it looks:
%LOCALAPPDATA%\GPMDP_3\Update.exe --processStart Google%20Play%20Music%20Desktop%20Player.exe
And it closes just fine, as I explained it. Even with quotation of PE. Small names works correctly. I could record a video, it you like.

**Comment by MarshallOfSound** [comment] 2016-03-05 14:06
Please do, because I really don't understand what you mean :+1:

**Comment by Namynnuz** [comment] 2016-03-05 14:33
Here it is. Sorry, I was kinda nervous: https://youtu.be/x-U85HNjcNE

**Comment by MarshallOfSound** [comment] 2016-03-05 14:37
OK, thanks for the video that was really clear and now I know what the issue is.

It is almost certainly to do with the language of your system being set to Russian.  Quite possibly due to how "%" signs are handled.  I'm going to pass this issue on to `electron-packager` as I believe it is an issue that they should be fixing.  (The %20 symbols are ridiculous, I would never put them there

**Comment by Namynnuz** [comment] 2016-03-05 14:40
Good to know. Thanks! Nice program, btw.

**Comment by MarshallOfSound** [comment] 2016-03-09 15:41
Electron bug so closing (forgot to do this)

**Closed by MarshallOfSound** 2016-03-09 15:41 UTC
Labels: bug, Electron Bug
