### ISSUE TITLE
Google Play Music Desktop with Vivaldi

### ISSUE THREAD

**Issue by NIchoUnited** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3740] opened 2019-12-19 00:11 UTC
- Download at https://www.googleplaymusicdesktopplayer.com/
- Open up and it opens to Google Play Music option.
- Top right corner is the option to switch to YouTube Music (Beta)
- Fails with an error message.
-  'Sorry, YouTube Music is not optimised for your browser. Check for updates or try Google Chrome.' There is then an option to Get Chrome.
- Google Play Music side of things works fine. Just not the YouTube Music option.

**Comment by Iowerth** [comment] 2019-12-20 09:43
> 
> 
>     * Download at https://www.googleplaymusicdesktopplayer.com/
> 
>     * Open up and it opens to Google Play Music option.
> 
>     * Top right corner is the option to switch to YouTube Music (Beta)
> 
>     * Fails with an error message.
> 
>     * 'Sorry, YouTube Music is not optimised for your browser. Check for updates or try Google Chrome.' There is then an option to Get Chrome.
> 
>     * Google Play Music side of things works fine. Just not the YouTube Music option.

Last version of Vivaldi (2.10) now [uses next UserAgent](https://vivaldi.com/ru/blog/vivaldi-2-10-no-strings-attached-2/) - `Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.94 Safari/537.36` for prevent from such issues. Please update your Vivaldi.

**Comment by NIchoUnited** [comment] 2019-12-20 19:41
First thing I checked when I downloaded 2.10. Still doesn't work.

**Comment by jostrander** [comment] 2019-12-31 22:09
I'm not sure what the actionable item is here, as I'm not familiar with Vivaldi. This should be fixed with the user agent fix that was pushed to master, if the issue is the message on YouTube music.

**Closed by jostrander** 2019-12-31 22:09 UTC
