### ISSUE TITLE
Can't login: browser not safe

### ISSUE THREAD

**Issue by pdario** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3722] opened 2019-12-12 10:00 UTC
Hello, after I was stuck on "loading music library", I signed out of Google and tried to sign in again; now Google says I can't because my browser is not safe.

I tried installing v4.7 but nothing changed, apart from the visuals of the message.

What can I do?

**Comment by mrjameshamilton** [comment] 2019-12-12 10:20
Same problem here.

**Comment by NiborIS** [comment] 2019-12-12 10:23
Same problem here

Google Play Music Desktop Player v4.6.1
Windows 10.0.19037.1

Thanks.

**Comment by pellomik** [comment] 2019-12-12 10:27
Two days with the same issue. 
Version: 4.6.1
Ubuntu 18.04

**Comment by tauil** [comment] 2019-12-12 10:35
Same problem

**Comment by jespersh** [comment] 2019-12-12 10:56
Is it just Google Play Music that isn't working? Mine doesn't load either, but YouTube Music (which I switched to few months ago) works

**Comment by tauil** [comment] 2019-12-12 10:57
Google Play Music for me.

**Comment by nebojsac** [comment] 2019-12-12 10:59
Same problem here

**Comment by gonzalomarcote** [comment] 2019-12-12 11:37
Seems that this is a common issue since 2 days ago regardless the distro. Google could have changed something to login from his side. 
Same problem using Debian 10 Buster and install Google Play Music with flatpak

**Comment by Vusys** [comment] 2019-12-12 11:42
Same. macOS 10.14.6.

I tried logging out then logging in. I don't get a browser not safe message, but I do get hanging on "Loading music library..."

**Comment by sidle21** [comment] 2019-12-12 11:43
'Browser not safe' message for me, using the latest windows version

**Comment by inacionery** [comment] 2019-12-12 12:07
Google Play Music for me, Youtube Music is working.

**Comment by cosmincrihan** [comment] 2019-12-12 12:24
Same issue both on Debian and Windows

**Comment by ajithhub** [comment] 2019-12-12 12:44
Win10, I was having the "Loading music library..." issue, then I uninstalled and deleted all the %APPDATA%.  Now I can't sign in.

I tried youtube Music and it lets me switch, but I'm still not able to log in.   The YT interface has stuff I can play without signing in.

**Comment by jostrander** [comment] 2019-12-12 13:05
Duplicate of #3545

**Closed by jostrander** 2019-12-12 13:05 UTC
