### ISSUE TITLE
App hangs in Windows 10 on "Loading Music Library"

### ISSUE THREAD

**Issue by roryhewitt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3726] opened 2019-12-12 22:16 UTC
**Checklist:**

* [X ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X ] I have double checked and can reproduce the issue

**OS:**

Windows 10 (1803 17134.1130)

**GPMDP Version:**

4.6.1

**Issue Descriptions:**

I've been using GPMDP for a couple of years with almost no issues. However, just since yesterday, I started GPMDP, and it starts loading, and then just hangs on the "Loading Music Library" screen. I haven't made any changes to my music library of changed my Google password or anything like that - it's a bit weird.

I checked on open/recent issues and saw issue #3688 which looks similar (even though I'm not trying to install. However, I followed the instructions in https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3688#issuecomment-561965300, but no good - still hangs.

**Steps to Reproduce:**

Start GPMDP.

**Comment by chpoit** [comment] 2019-12-12 22:32
Same thing happens under ubuntu 19.04 when installing via snap (might do the same for others, didn't try)

**Comment by GioDinoMan** [comment] 2019-12-12 22:40
I think this may have happened after the most recent Windows update. I am having the same issue.

**Comment by purajit** [comment] 2019-12-12 22:46
This has been happening on Mac OS X Mojave as well over the last week or so.

**Comment by magneticflux-** [comment] 2019-12-12 22:46
Same issue here.
I'm running Windows 10 Version 2004, Build 19041.1.

**Comment by jostrander** [comment] 2019-12-12 22:48
Duplicate of #3660

**Closed by jostrander** 2019-12-12 22:48 UTC
