### ISSUE TITLE
Uncaught Exception: Error processing argument -1.

### ISSUE THREAD

**Issue by jakelauer** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#944] opened 2016-04-15 17:12 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.0
**Time:** Fri Apr 15 2016 10:12:20 GMT-0700 (Pacific Daylight Time)

#### Error:
*Error processing argument -1.*
```js
TypeError: Error processing argument -1.
    at TypeError (native)
    at EventEmitter.<anonymous> (C:\Users\jlauer\AppData\Local\GPMDP_3\app-3.0.0\resources\app\build\main\features\core\keyboardShotcuts.js:47:56)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\jlauer\AppData\Local\GPMDP_3\app-3.0.0\resources\atom.asar\browser\api\lib\web-contents.js:120:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-04-15 17:13
Closing this automatically reported issue as a duplicate of #326

**Closed by GPMDP-Magical-Unicorn** 2016-04-15 17:13 UTC
Labels: Automatic-Issue-Report
