### ISSUE TITLE
Couldn't sign you in

### ISSUE THREAD

**Issue by tsbartle** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3744] opened 2019-12-20 19:01 UTC
Running arch, built from the AUR fine, when attempting to sign in with my google credentials I receive the following warning:

> Couldn't sign you in
xxxxxxxx@gmail.com
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

This appears to be a relatively new issue but the only recommendation is to try a different browser which isn't an option with gpmdp.

**Comment by AhoyLemon** [comment] 2019-12-20 19:05
This is happening to me as well. App wouldn't launch, so I deleted everything in `%APPDATA% as described in issue #2548 

However, then when trying to launch it again, it asks me to sign in.

When I try, I get this:
![image](https://user-images.githubusercontent.com/3413200/71284849-5bdc0a80-2329-11ea-9f09-23f810407336.png)

**Comment by jostrander** [comment] 2019-12-20 19:11
Duplicate of #3545

**Closed by jostrander** 2019-12-20 19:11 UTC
