### ISSUE TITLE
Orange accent in 3.2.1

### ISSUE THREAD

**Issue by RodolfoSan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#967] opened 2016-04-19 12:50 UTC
OS: Windows 8/10.

Issue Descriptions: The orange accent is still present even when changing the theme to custom. Is there any way to fix this?

**Comment by jostrander** [comment] 2016-04-19 12:54
Duplicate of #953

**Comment by RodolfoSan** [comment] 2016-04-19 13:00
@jostrander It may be, thanks for the help.

**Comment by jostrander** [comment] 2016-04-19 13:06
If I could reproduce I'd try to help further, but it appears it only happens occasionally. It may already be fixed in master however.

**Comment by MarshallOfSound** [comment] 2016-04-19 14:33
@jostrander It comes down to load speed of the webview compared to load speed of the local DOM.  There is a race condition that was introduced in electron `0.37.4+` and fixed in master a few days ago

**Closed** 2016-04-19 15:39 UTC
