### ISSUE TITLE
Windows window frame overlapping

### ISSUE THREAD

**Issue by Javierdsv** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#31] opened 2015-11-06 13:49 UTC
The minimize, maximize and close buttons are being overlapped by the Windows window frame controls on Windows 7 Enterprise. Attached a little screenshot on how it looks like. 
![capture](https://cloud.githubusercontent.com/assets/12553183/10998463/e5bceba6-845a-11e5-8ad3-6f69637da22e.PNG)

**Comment by MarshallOfSound** [comment] 2015-11-06 15:34
I cannot replicate this on any of the OS's I have access to (7 Home, 8, 8 Pro and 10).  Can you please provide a list of the .NET packages you have installed and a list of the Visual C++ redists you have installed.

Thanks

**Comment by Javierdsv** [comment] 2015-11-06 22:06
Sure, here is a screenshot out of the control panel of this machine:

![capture](https://cloud.githubusercontent.com/assets/12553183/11009859/19f1f80e-84a0-11e5-8d9e-e368d4a51e1a.PNG)

It may be just a missing redist indeed.  For the record, this is not happening with the previous release, only the 1.7.0 version.  Uninstalled it, deleted the %APPDATA% folder and reinstalled it and keeps happening. (Not on other versions)

**Comment by MarshallOfSound** [comment] 2015-11-08 09:53
Can you try specifically installed `.NET 4.0` and `Visual C++ 2012 x86`.

Other than that I have no idea...

**Comment by MarshallOfSound** [comment] 2015-11-09 12:13
Try as I might i can not replicate this issue, do you have any custom windows themes installed on your PC or something like that?

Can you try running as admin / in compatability mode.  Somethings messing it up at your end and I can't replicate what :smile:

**Comment by LordTowers** [comment] 2015-11-16 18:47
I get the exact same issue (screenshot is exactly what i experience) and i didn't have the issue with any previous version (i have not uninstalled 1.7.0 and installed an older version though). Using Windows 7 (on a Thinkpad) using the most up to date windows and Lenovo updates.

**Comment by Javierdsv** [comment] 2015-11-16 19:15
I have tried to leave just specific Net Framework and Visual C++ versions and the problem keeps happening. It looks like Windows is trying to force their actual "aero" frame regardless of the custom orange/black the app uses.   I use the basic Windows 7 theme to keep my GPU healthy,  at first I thought this was the problem, but even when changing to the default Windows themes it keeps happening. Re-installing, deleting the cache folder, or launching it as admin/compatibility does not help. Re-installing the older version makes it work perfectly tho.  

I aim to believe it has to do with the part "Window now works with aero snap" from the changelog of this version.

**Comment by LordTowers** [comment] 2015-11-16 19:34
I was also starting to get strange .Net crashes and other weirdness with the 1.7 version (totally unhelpful i realize for troubleshooting since i didn't pull screenshots), i uninstalled and went back to 1.6 and it seems like it's back to its proper working order.

**Comment by MarshallOfSound** [comment] 2015-11-16 22:36
Untill I can replicate this on a machine I have access to (I am still trying) I have no idea how to fix this or what is even going on.  I'm trying to source a Windows 7 machine as that seems to be the linking factor between you two.

**Comment by MarshallOfSound** [comment] 2015-11-17 01:08
OK so progress update, I got my hands on a windows 7 PC and replicated the issue.  After a bit of mucking around and some nasty hacks (which I am not proud of :cry: ) I think I have a build that fixes this issue.  Can you guys please test this debug build ASAP

https://mega.nz/#!SIcEQDIB!gLbu0dRzhRG4J10FVgbCUFce3_-sNs_RvggbvFe8gVc

**Comment by Javierdsv** [comment] 2015-11-17 15:02
I unzip that file, run it from the unzipped folder and even though it prompts "A new update is available" I click Not Now, and it works perfectly fine.  The problem is gone.

**Comment by LordTowers** [comment] 2015-11-17 16:11
Same as Javier above, ran from unzipped folder and the minimize/full screen/close overlay looks good again. When i was first clicking around there was what looked like the windows overlay for the minimize button poking through but it seems to be gone now (didn't do anything besides wait) and it hasn't thrown any .net errors or anything either. I'll post another update if anything goes awry

**Comment by MarshallOfSound** [comment] 2015-11-26 11:44
@LordTowers @Javierdsv `1.8.0` didn't happen to fix this for you guys by any chance *hopes*

**Comment by Javierdsv** [comment] 2015-11-26 13:36
The problem persists in 1.8.0 :(

**Comment by FISHunderscore** [comment] 2015-11-30 01:28
Similar issue: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/66

**Comment by LordTowers** [comment] 2015-11-30 16:42
i didn't install the newest version but if you are ok with me assuming its broken here too (since Javier and me have been in lockstep) i'll just wait and test the next version

**Comment by ngramste** [comment] 2015-11-30 16:56
Yup, I have checked with the newest version (1.9.1) and the problem still exists.

**Comment by LordTowers** [comment] 2015-12-11 16:11
still exists in 1.9.2 as well

**Comment by LordTowers** [comment] 2016-01-05 16:28
i know you're probably tired of hearing it but the issue persists in the 2.0.0 version as well

**Comment by MarshallOfSound** [comment] 2016-01-06 03:11
Details screenshots #129

**Comment by Talor-A** [comment] 2016-01-06 06:42
would it be possible to use the system window frame, and on Windows versions that support it, change the window frame color to orange/black?

**Comment by MarshallOfSound** [comment] 2016-01-06 07:09
I don't think so, not without massive code duplication.  Currently the window is themed due to a specific class "extends".  And you can't conditionally " extend" a class

**Comment by LordTowers** [comment] 2016-01-06 15:20
Since it seems to be Aero related would a 'first fix' be a toggle switch to turn it on or off so we can still enjoy the newer versions while this is getting resolved (or become the permanent Windows 7 fix if you can't?

**Comment by Talor-A** [comment] 2016-01-06 15:51
@MarshallOfSound I don't know Visual Studio, but can't you use the standard window frame on all platforms, and then on windows 8/10 simply set the color to orange? This wouldn't involve code duplication.

**Comment by MarshallOfSound** [comment] 2016-01-11 01:13
I have struggled with this for far too long....
Gonna ask for some help @IgnaceMaes <-- He wrote the Material Skin originally

Any ideas ^^

**Comment by MarshallOfSound** [comment] 2016-01-11 11:05
@Javierdsv @LordTowers @FISHunderscore @FuzzAU @ngramste @Talor-A 

Hey guys,
Can some of you please try this latest beta build off AppVeyor  

[32 Bit ZIP](https://ci.appveyor.com/api/buildjobs/rltkupfy9rohar9a/artifacts/Google%20Play%20Music/bin/x86/GPMDP.Beta.x86.zip)
[64 Bit ZIP](https://ci.appveyor.com/api/buildjobs/x3yxvn4cme2d0esp/artifacts/Google%20Play%20Music/bin/x64/GPMDP.Beta.x64.zip)

I'm pretty confident I have fixed it, just need confirmation so I can close this issue

**Comment by FuzzAU** [comment] 2016-01-11 12:45
I haven't been able to reproduce sorry. I only have Windows 10 machines. Tried 150% scaling on my 3440x1440 and the buttons all operate ok.

This is a screenshot of the previous beta you sent in the above configuration:
<img width="859" alt="before" src="https://cloud.githubusercontent.com/assets/1161763/12233754/5615562c-b8bd-11e5-8730-c686dc20abe9.png">

and this is a screenshot of the latest from above:
<img width="651" alt="after" src="https://cloud.githubusercontent.com/assets/1161763/12233766/6a6b9078-b8bd-11e5-9825-53cbcdf68609.png">

The default scaling seems to be different. Was that to be expected?

**Comment by MarshallOfSound** [comment] 2016-01-11 18:55
Hmmmm, @FuzzAU Does it scale like that on `2.0.2`?

**Comment by LordTowers** [comment] 2016-01-11 22:45
Looks like the x64 debug version fixed the issue for me! The program runs super sluggishly though but I assume that's just because this is a debug version

**Comment by MarshallOfSound** [comment] 2016-01-11 22:47
@LordTowers Not sure why it would run slower than normal, possibly just a placebo affect or something?

This is technically a release build

**Closed** 2016-01-12 10:16 UTC
Labels: bug, help wanted

**Comment by LordTowers** [comment] 2016-01-12 16:04
Possibly, i've also been running v1.6 up to now (last ver w/o the issue) so perhaps the newer/fancier versions load and run just a tad slower

**Comment by Javierdsv** [comment] 2016-01-13 14:44
Just passed by to say Thank You. 
The zips you attached had a solid fix to the issue,  it is completely gone.   
No slowing issues here though, working as intended :100:
