### ISSUE TITLE
Freeze on Sign in Ubuntu 15.04 64-bit

### ISSUE THREAD

**Issue by mccore** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#283] opened 2016-03-06 20:08 UTC
As soon as I click any of the Sign In buttons on the start up page the program freezes and the screen looks like the following: 
![image](https://cloud.githubusercontent.com/assets/15894670/13556656/48f6a214-e3ad-11e5-9d15-36366f8bb90d.png)

**Comment by Maccer1** [comment] 2016-03-06 20:55
Also happening in elementary OS Freya, based in Ubuntu 14.04 LTS 64 bit.

In my case I get the login window but when I press enter to log in it freezes and I just see a white background with some black squares.

**Comment by MarshallOfSound** [comment] 2016-03-06 22:35
Duplicate of #281  ?

Please raise rendering issues against `atom/electron`

**Closed by MarshallOfSound** 2016-03-06 22:35 UTC

**Comment by ToucheSir** [comment] 2016-03-06 22:46
As a stopgap measure, you can pass the chrome/electron flag `--disable-gpu` on startup to disable hardware rendering.

**Comment by MarshallOfSound** [comment] 2016-03-06 22:46
@ToucheSir I'll add that to the FAQ i'm writing atm
