### ISSUE TITLE
Proxy requires authentication

### ISSUE THREAD

**Issue by adamkrol93** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3292] opened 2018-07-25 07:04 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
MacOS High Sierra 10.13.5

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
I used to listen music by this application but few days ago our company introduced proxy for us. Since then I am not able to run application. I am getting 401 - Unauthorized: Access is denied due to invalid credentials.
<img width="1198" alt="proxy_error" src="https://user-images.githubusercontent.com/6851171/43184629-88946eca-8fe9-11e8-88ca-efd14eed0a1b.png">

Do you think that it is possible to either show proxy log in page or use the one which is stored in chrome?

**Steps to Reproduce:**
Just use proxy which requires authentication.

**Comment by thvd** [comment] 2018-09-10 10:52
I think this is a duplicate of https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3151

**Comment by MarshallOfSound** [comment] 2018-10-23 08:40
Merging into #3151

**Closed by MarshallOfSound** 2018-10-23 08:40 UTC
