### ISSUE TITLE
Uncaught Exception: The request timed out.: (null)

### ISSUE THREAD

**Issue by anderspollack** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#595] opened 2016-03-14 20:00 UTC
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Mon Mar 14 2016 15:00:38 GMT-0500 (CDT)

#### Error:
*The request timed out.: (null)*
```js
Error: The request timed out.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-14 20:07
Closing this automatically reported issue as a duplicate of #235

**Closed by GPMDP-Magical-Unicorn** 2016-03-14 20:07 UTC
Labels: Automatic-Issue-Report
