### ISSUE TITLE
Audio Device resets to system default at system restart

### ISSUE THREAD

**Issue by SolarLiner** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#696] opened 2016-03-20 20:40 UTC
**Issue Descriptions:**
The app redirects sound to the primary sound card after system restart, independently of the selected audio device.
![723c2ee79d22cd72ae060490e4dd49d8](https://cloud.githubusercontent.com/assets/4302963/13906965/a91c0b7a-eee3-11e5-95fb-dc4017c4bfaf.png)
(Using VoiceMeeter as a virtual mixer, shows that sound is getting out to "VoiceMeeter Input" (the system default), while selected in the option is the second, "VoiceMeeter Aux Input" card.)
![cd001649af99832cf43355ba78022c1f](https://cloud.githubusercontent.com/assets/4302963/13906984/ec7eb7c8-eee3-11e5-8f52-012a192bd4b7.png)

**OS:** Windows

**Steps to Reproduce:** Select a non-default soundcard in the Audio options, and restart computer. Audio should now be played back from the default soundcard.

Unrelated note: With the port to Electron, I now have seamless playback of continuous albums, which is top notch and is the only place where it plays that way (even the GPM app on my phone has a hard time playing albums seamlessly)  
So thank you :)

**Comment by MarshallOfSound** [comment] 2016-03-21 00:54
This seems to be a strange situation (The audio device you set it to is "fake")

Can you please ensure that the audio device (VoiceMeeter Input) is available when the application is started?

Also that second picture seems to imply it is working (The sound is being sent to the "Aux" channel?

**Comment by SolarLiner** [comment] 2016-03-21 06:11
Yes, those are software cards, but are available at system start as they're
registered as drivers.
The second picture show it works, because I chose the correct soundcard
again in the settings and works as expected.

But just in cae it's a VoiceMeeter soundcard issue, I'll report after using
hardware outputs.

Le lun. 21 mars 2016 01:54, Samuel Attard <notifications@github.com> a
écrit :

**Comment by MarshallOfSound** [comment] 2016-03-21 06:14
I use a USB DAC, SPDIF and 3.5mm output and they all correctly save / resume between restarts of the player so I'm at a loss to explain it.  Interested to hear whether there is a specific case that causes the issue or does it happen all the time

**Comment by SolarLiner** [comment] 2016-03-21 19:36
Indeed, after trying reproducing the issue on hardware outputs, everything worked fine. And when trying on the software outputs again, it still was working correctly.
This is weird, indeed, as it was happening to me with each system restart before.

**Comment by MarshallOfSound** [comment] 2016-03-21 22:04
Maybe user error in some way??? Or maybe the virtual audio devices were being updated when you opened GPMDP?

A number of things could be the cause but if it's all working now I guess I'll close it :+1: :smile:

**Closed by MarshallOfSound** 2016-03-21 22:04 UTC
Labels: awaiting response
