### ISSUE TITLE
Thumbs Up Current Song hotkey invalid behavior

### ISSUE THREAD

**Issue by TBXin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1118] opened 2016-05-26 10:54 UTC
**OS:** Windows

**Issue Descriptions:** "Thumbs Up Current Song" hotkey removing "like" if song was already liked.
Can this behavior be removed? Or for what reason there are two hotkeys: Thumbs Up/Down?

**Steps to Reproduce:** Use hotkey twice on the same track.

**Comment by Smashman** [comment] 2016-05-26 13:18
Are you saying that pushing the 👍  button removes the 👍  from a track that already had one?
If so, that is normal Google Music behaviour. Allowing the 👍  to be removed means that a track can be left in the default state, rather than locking the user into favouring or disliking the track.

If you are not saying that, please could you describe the issue in more detail?

Thank you.

**Comment by jostrander** [comment] 2016-05-26 13:31
@TBXin is specifically looking to make sure the hot key to add a thumbs up is not removing the thumbs up. Since the UI is not visible it would be hard for a user to discern that the song is not already liked, therefore removing the thumbs up from an existed "liked" song. I understand the concern here, should be simple to fix, maybe I'll make a PR for it if its feasible in the code.

**Comment by TBXin** [comment] 2016-05-26 14:51
Thanks for the fast reply.
Sorry for my english :)

@Smashman, yes, this is normal behavior when you clicked :+1: button on the song list item, but not normal for hotkey eg when player window is minimized.

@jostrander, It would be great if you can implement this behavior.
In my regular usage of the player, main window is minimized. When listening a new album or artist, I just want to press the hotkey and do not think that i can :+1: this song earlier and now it will be :-1:.

**Comment by Smashman** [comment] 2016-05-27 10:43
Perhaps some feedback could be implemented so you know what you've just done?

**Comment by thedeany** [comment] 2016-05-28 16:20
I can't replicate this. I configured a hotkey, played a song, minimized the window, pressed the hotkey, pressed it again, and the thumbs up was still selected.

**Comment by MarshallOfSound** [comment] 2016-05-28 16:25
@thedeany Your comment prompted me to actually check the issue as well (I just assumed the report was accurate and the people commenting had kind of verified it)

:egg: 

After some analysis of the code and setting up my own hotkey I can't replicate the report and I don't think the report is even possible.

The relevant code is here https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/src/inject/GPMWebView/playback/controller.js#L35

As you can see we aren't toggling, rather setting.  I don't know what you are doing @TBXin but you are making the code do something that is physically impossible :laughing: 

Closing as it apparently is a mis-report

**Comment by TBXin** [comment] 2016-05-28 17:59
I dont know what version your are using, but in the 3.2.4 i successfully reproduced issue on my work and home pc's.

Just open "My favorites" playlist, start listening any track, press hotkey: :+1: song, and now this song is removed from "My favorites" and :+1: is gone...

**Comment by jostrander** [comment] 2016-05-28 18:06
I actually can't produce either, running 3.2.4 on windows, originally I thought it may have been a possibility but didn't have time to check over the code, but it appears to not be possible to do. What keyboard shortcut are you using? 

Even the gmusic.js library checks the thumb status before trying to click it:

https://github.com/gmusic-utils/gmusic.js/blob/master/lib/main.js#L288

**Comment by TBXin** [comment] 2016-05-28 18:09
![](http://i.imgur.com/UScHhrc.png)
Ctrl+Alt+A - and this is only one hotkey that i configure.

**Comment by jostrander** [comment] 2016-05-28 18:10
Do you still receive the "You liked..." notification when you use the shortcut? "Undoing" the thumbs manually doesn't remove the song from the playlist, only doing a thumbs down does from just testing it.

**Comment by TBXin** [comment] 2016-05-28 18:12
Yes, every time i press hotkey notification comes and every time "You liked..."
"Undoing" :+1:  or :-1: removed track from the playlist "My favorites", from other playlist not.

**Comment by jostrander** [comment] 2016-05-28 18:14
Is that an Auto Playlist or a playlist you created? I don't have a "My Favorites" playlist, only a "Thumbs Up" playlist.

**Comment by TBXin** [comment] 2016-05-28 18:16
![](http://i.imgur.com/YrzZOMm.png)

I mean autogenerated playlist, that is formed from songs you ever :+1:

**Comment by jostrander** [comment] 2016-05-28 18:18
Oh boy. I think I might have realized what the issue is. The GPM library is using the title attribute to pick  up whether or not its already selected.. `title="Undo thumb-up"`. I might have to change my language (!!) but I think that title might be a translated property, causing the check to fail. I'll check and report back.

**Comment by jostrander** [comment] 2016-05-28 18:22
@TBXin can you hover over the thumbs up icon while its selected and tell me if its in your native language? I can't get google to think I'm russian :8ball: ...

**Comment by TBXin** [comment] 2016-05-28 18:23
Yes, on my own.

![](http://i.imgur.com/H3JOKmT.png)

![](http://i.imgur.com/vKpaZc1.png)

**Comment by MarshallOfSound** [comment] 2016-05-28 18:35
> The GPM library is using the title attribute to pick up whether or not its already selected.. title="Undo thumb-up"

Please tell me you're joking...

>  @MarshallOfSound can you reopen and mark as an upstream issue?

It's moments like this that make me cry inside... :cry:

**Comment by jostrander** [comment] 2016-05-28 18:40
There's nothing in the DOM other than the language based title attribute that shows whether or not the thumb is marked. This is going to require a bit of digging.

**Comment by MarshallOfSound** [comment] 2016-05-28 18:45
@jostrander We will probably have to do a length comparison / check on the SVG d path

https://www.diffchecker.com/trwvwkcj

Left is SVG for neutral thumb
Right is SVG for filled in thumb

**Comment by jostrander** [comment] 2016-05-28 18:49
![image](https://cloud.githubusercontent.com/assets/760989/15629292/4f2cd5be-24e3-11e6-8b50-fc9a1b3bbf0e.png)

The iron-icon element has a __data__ JS prop (not sure if it can be accessed outside of $0 in chrome) that has different properties. Maybe this would be a better solution?

**Comment by jostrander** [comment] 2016-05-28 18:53
```
document.querySelector(".rating-container paper-icon-button iron-icon").__data__.icon
```

Seems to work, maybe we can use something like that, or the equivalent code?

**Comment by MarshallOfSound** [comment] 2016-05-28 18:53
@jostrander You can access `__data__` from a `HTMLElement` anyway in JS so if that `icon` value is updating as it appears in your screenshot that could be our saving grace :+1:

**Comment by jostrander** [comment] 2016-05-28 18:58
You want to push it upstream or do you want me to?

**Comment by MarshallOfSound** [comment] 2016-05-28 18:58
I'm already trying to push through 2 PR's upstream.  You can give it a go if you want otherwise I'll do it :+1:

**Comment by jostrander** [comment] 2016-05-28 19:12
Upstream: https://github.com/gmusic-utils/gmusic.js/pull/39

**Comment by MarshallOfSound** [comment] 2016-05-29 10:08
With gmusic-utils/gmusic.js#39 merged I'm closing this issue

**Closed by MarshallOfSound** 2016-05-29 10:08 UTC
Labels: bug, Upstream
