### ISSUE TITLE
Quitting the app takes a while

### ISSUE THREAD

**Issue by curtisblackwell** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1071] opened 2016-05-12 08:21 UTC
**OS:**
Mac OS X El Capitan 10.11.4

**Issue Descriptions:**
When I quit the app, it takes ~30s (just an estimate) to actually quit.

Fairly confident it's not just my computer lagging, because:

- My computer is less than a year old.
- I have a 2.8GHz processor and 16 GB of RAM.
- It only happens with this app.

**Steps to Reproduce:**
1. Use the app all day.
2. Hit `cmd` + `q`.
3. Wait a while before the app actually quits.

This has happened to me a number of times. I'm guessing this is tough to track down, but if there's something I can do to help, let me know.

**Comment by MarshallOfSound** [comment] 2016-05-12 11:49
When you say "doesn't quit".  Do you mean the music keeps playing?  Or the app physically is still present on the screen?

**Comment by curtisblackwell** [comment] 2016-05-12 19:21
The app is still present on the screen, the music keeps playing, and the cursor turns into a spinning beach ball.

**Comment by MCManuelLP** [comment] 2016-05-12 22:44
Can confirm that this also occurs on linux, built from source at: d6fa481

**Comment by MarshallOfSound** [comment] 2016-05-12 23:36
This is probably an issue with electron.  Hopefully it is fixed in an updated version, I'll keep this open to track

**Comment by curtisblackwell** [comment] 2016-05-13 00:23
If it was an issue with Electron, wouldn't I also have this problem with other apps? I use Slack and Postman, neither of which has this issue.

**Comment by MarshallOfSound** [comment] 2016-05-13 00:25
@curtisblackwell It might be something to do with the WebAudio API's.  I've noticed for a while that on windows the app closes but the music keeps playing for a while.  It could have been a memory / GC issue inside chromium

**Comment by curtisblackwell** [comment] 2016-05-13 00:27
Got it. Well, I'll update the thread if I have any new info. Thanks!

**Comment by jostrander** [comment] 2016-05-27 13:26
I can confirm this issue exists, happens on both linux and windows, and is more than likely a bug with electron. In my case however the audio plays on for ~20 seconds before the process is actually killed. The reason slack and postman don't have the issue is because they are using pretty old versions of electron.

**Comment by MarshallOfSound** [comment] 2016-06-10 17:25
This appears to have magically stopped as of Electron `1.2.2`.  I'm going to *optimistically* close this issue 😀

**Closed by MarshallOfSound** 2016-06-10 17:25 UTC
Labels: Upstream
