### ISSUE TITLE
Playlist Link Color

### ISSUE THREAD

**Issue by Xedecimal** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#443] opened 2016-03-10 18:57 UTC
**OS:**

Windows 10

**Issue Descriptions:**

Playlist link color does not get themed I believe. When I turn the theme off the color stays dark and looks proper. When turning theme on the color stays the dark color against the dark background and becomes difficult to see.

**Steps to Reproduce:**

Not sure what brought this about. Just started today, maybe a change in the GMusic interface happened today. Screenshot attached showing selected, playing, normal and hover colors.

![google 20play 20music 20desktop 20player_2016-03-10_10-53-13](https://cloud.githubusercontent.com/assets/99204/13680721/b489eabe-e6ae-11e5-9455-b6915f13f00e.png)

**Comment by Zer0t3ch** [comment] 2016-03-10 19:32
Just came here to report this, looks like you beat me by 30 minutes. :+1: 

I can confirm this is happening to me as well. If I had to assume, it's probably a small oversight in whatever CSS the program overrides.

**Comment by chrismou** [comment] 2016-03-10 22:07
This has been fixed in the theming repo: https://github.com/gmusic-utils/gmusic-theme.js/pull/16 -- I'm told it should be included in the next release.

Seems like Google may be rolling out a minor update.

**Comment by MarshallOfSound** [comment] 2016-03-10 23:39
Will befixed in the next release.  It has already been patched in the theming library

**Closed by MarshallOfSound** 2016-03-10 23:39 UTC
