### ISSUE TITLE
Add option to turn off auto-update

### ISSUE THREAD

**Issue by SirDufus** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3248] opened 2018-07-11 15:54 UTC
**OS:**
Windows 10

**GPMDP Version:**
Trying to use 4.5 but keeps auto updating to 4.6

**Issue Descriptions:**
Current version has the 'back' feature broken and when I downgrade to 4.5 so I can use that feature, the software automatically updates itself to the new broken version. I just want the back feature to work and until the new patch is released, using the older version is good enough for me.

Please add an option to turn off auto update.

**Steps to Reproduce:**
I just installed an old version and it automatically updated itself without proper permission.

**Comment by jostrander** [comment] 2018-07-11 16:02
Duplicate of #3176

**Comment by jostrander** [comment] 2018-07-11 16:02
Actually, it's a duplicate of a different issue, but this is primarily targeting #3176. This issue has been raised before.

**Closed by jostrander** 2018-07-11 16:02 UTC

**Comment by SirDufus** [comment] 2018-07-11 16:11
Was not reporting the issue of the back button being broken!? Was asking to have auto update an option *because* the feature is broken and I want to use an older version. How do you guys not understand this?

**Comment by jostrander** [comment] 2018-07-11 16:16
I understand that. The issue of turning off auto-update has _also_ been brought up before, and has been turned down before. If you _really_ want to disable auto updates you can probably put an entry in your hosts file to localhost for the update server.
