### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by philippthiele** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#646] opened 2016-03-17 13:58 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Thu Mar 17 2016 14:58:47 GMT 0100 (Mitteleuropäische Zeit)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\tietz_000\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\tietz_000\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
    at BrowserWindow.<anonymous> (C:\Users\tietz_000\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\main\features\core\controlBar.js:24:18)
    at emitOne (events.js:77:13)
    at BrowserWindow.emit (events.js:169:7)
    at EventEmitter.<anonymous> (C:\Users\tietz_000\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\main\features\core\controlBar.js:17:43)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (C:\Users\tietz_000\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\api\lib\web-contents.js:134:25)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by philippthiele** [comment] 2016-03-17 14:03
I don't really know how this happened but I wanted to upload Music using your Player. Is it possible atm? Google asked me to install something but it stays on the "Google Play Music is being configured" page (or so I think it has to be translated to english from german).

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-17 14:05
Closing this automatically reported issue as a duplicate of #470

**Closed by GPMDP-Magical-Unicorn** 2016-03-17 14:05 UTC
Labels: Automatic-Issue-Report, duplicate
