### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by slipperydippery** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#890] opened 2016-04-04 12:15 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Mon Apr 04 2016 14:15:17 GMT 0200 (West-Europa (zomertijd))

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\JellyFish\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\JellyFish\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-04-04 12:15
Closing this automatically reported issue as a duplicate of #470

**Closed by GPMDP-Magical-Unicorn** 2016-04-04 12:15 UTC
Labels: Automatic-Issue-Report

**Comment by MarshallOfSound** [comment] 2016-04-04 12:18
Please restart the app and accept the update.  The latest version is `3.1.0`.  This issue has been fixed

**Comment by MarshallOfSound** [comment] 2016-04-04 16:59
@slipperydippery Could you please also upload the file found at `%LOCALAPPDATA%\GPMDP_3\SquirrelSetup.log` on your computer.  I am trying to determine why some users aren't updating

**Comment by slipperydippery** [comment] 2016-04-05 21:17
Sorry for the late response. 
Hope this helps, love the app!


[SquirrelSetup.log.txt](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/205368/SquirrelSetup.log.txt)

**Comment by jostrander** [comment] 2016-04-05 22:20
Server error translated:

The remote server returned an error: (403) Not allowed .

@marshallfsound, can you check k server logs or do you see anything
obviously wrong with the request?

**Comment by MarshallOfSound** [comment] 2016-04-06 01:29
@slipperydippery Do you use a proxy of any kind?

@jostrander That was only the first error and has since been fixed server side, as you can see in the logs an update succeeded after those errors.  The new error translated is `The remote name could not be resolved` which is the same as all the others who can't update.  The current theory is a proxy getting in the way

**Comment by slipperydippery** [comment] 2016-04-06 11:44
@MarshallOfSound I sometimes use a VPN, but it's currently off. If I try restarting the app, the error persists. Should I try reinstalling manually?
