### ISSUE TITLE
Support for Windows 10 taskbar jumplist

### ISSUE THREAD

**Issue by jessehouwing** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1587] opened 2016-09-06 15:25 UTC
**OS:**
Windows 10 Anniversary Edition

**Issue Descriptions:**
The task tray has a nice list of actions, but on the Windows 10 icon there is zero interaction options. Plus the icon is named "Update.exe" instead of a proper application title. 

<img width="382" alt="image" src="https://cloud.githubusercontent.com/assets/4173387/18279628/83570c98-7456-11e6-99be-c8ab570b7656.png">

I did fid the mini-player which shows after hovering over the icon a while. That already seems to integrate a bit better, though it doesn't show the album art in the tile, it shows a mini-version of the window, which in itself isn't very useful:
<img width="201" alt="image" src="https://cloud.githubusercontent.com/assets/4173387/18279692/bb05b180-7456-11e6-95ad-14dd4d48b041.png">

**Expected behavior:**

I'd love to see:

 * Shortcuts to recently played playlists
 * Play / Pause
 * Shuffle / Repeat

on the jump list

**Comment by MarshallOfSound** [comment] 2016-09-06 15:37
> Play / Pause

These are already thumbbar buttons as you can see in your screenshot

> Shuffle / Repeat

These are conditional and only do anything when you aren't listening to a radio station.  As such adding them to the thumbbar buttons makes little sense as it can be confusing to have a button that does nothing.

> Shortcuts to recently played playlists

I have a branch somewhere that does this.  But the problem is, some people will want recent artists, some will want recent albums, some will want recent tracks, some will want recent pages.

If there isn't a way to do it that would satisfy most of the people then I wouldn't feel comfortable implementing it.

> I did fid the mini-player which shows after hovering over the icon a while

That is a windows feature, part of "Aero".  Nothing to do with me and I have no control over what it displays (at least from Electron's side of things)

**Comment by MarshallOfSound** [comment] 2016-09-06 15:38
So although personally I would love quite a few things you mentioned, the logistics of implementing the feature at all let alone in  a way that satisfies a majority of people makes this a `wontfix` for me

**Closed by MarshallOfSound** 2016-09-06 15:37 UTC
