### ISSUE TITLE
Windows Start Menu Shortcut

### ISSUE THREAD

**Issue by sahaskatta** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1538] opened 2016-08-26 15:37 UTC
I just installed this program on Windows 10 Anniversary Update. I realized that it did not create an entry in my start menu to launch the program. Is this intended functionality or did the installer break?

**Comment by MarshallOfSound** [comment] 2016-08-26 15:49
Have you relocated your desktop / start menu storage folder as described by this person here

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1503#issuecomment-241308656

**Comment by sahaskatta** [comment] 2016-08-26 15:53
@MarshallOfSound Nope.

I have a clean install of Windows 10 Anniversary Updated on a Surface Pro 4. I only have one 'C' drive and I have definitely not relocated any folders.

I should note that the installer did successfully create an icon on my desktop, however no start menu entries were created.

**Comment by MarshallOfSound** [comment] 2016-08-26 16:01
@sahaskatta It might sound strange but are you sure? 😆 Can you check this folder, sometimes windows doesn't reindex the apps correctly.

```bash
%APPDATA%\Microsoft\Windows\Start Menu\Programs\Samuel Attard
```

**Comment by sahaskatta** [comment] 2016-08-26 16:22
![image](https://cloud.githubusercontent.com/assets/221064/18012463/6b1f22a0-6b6e-11e6-8850-8bc32e8b0081.png)

Haha. Take a look! It's a one-click installer. I doubt I messed up that badly.

**Comment by MarshallOfSound** [comment] 2016-08-26 16:24
@sahaskatta Had to check 👍 

Can you upload your log file found at

```bash
%APPDATA%\Google Play Music Desktop Player\gpmdp.log
```

**Comment by sahaskatta** [comment] 2016-08-27 22:51
Don't think I see anything unusual in it:
```

{"level":"info","message":"Application started.","timestamp":"2016-08-25T21:51:05.074Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2016-08-25T21:51:06.037Z"}
{"level":"info","message":"Application exiting...","timestamp":"2016-08-25T21:53:50.234Z"}
{"level":"info","message":"Application started.","timestamp":"2016-08-26T02:38:16.985Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2016-08-26T02:38:17.643Z"}
{"level":"info","message":"Application exiting...","timestamp":"2016-08-26T02:39:52.797Z"}
{"level":"info","message":"Application started.","timestamp":"2016-08-26T15:27:48.252Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2016-08-26T15:27:49.123Z"}
{"level":"info","message":"Application exiting...","timestamp":"2016-08-26T15:28:55.039Z"}
{"level":"info","message":"Application started.","timestamp":"2016-08-26T15:28:59.073Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2016-08-26T15:28:59.525Z"}
{"level":"info","message":"Application exiting...","timestamp":"2016-08-26T20:01:03.771Z"}
{"level":"info","message":"Application started.","timestamp":"2016-08-27T00:07:44.215Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2016-08-27T00:07:47.065Z"}
{"level":"info","message":"Application exiting...","timestamp":"2016-08-27T00:42:36.046Z"}

```

**Comment by Viper007Bond** [comment] 2016-08-31 01:39
FWIW I didn't get a Start Menu entry either, but I did get a Desktop one.

![cortana_2016-08-30_18-39-14](https://cloud.githubusercontent.com/assets/406254/18112976/1dc5f058-6ee1-11e6-89f4-27a2e350b758.png)

**Comment by IT8055** [comment] 2016-09-02 12:30
Same machine / OS and same issue - Clean install of windows 10 anniversary edition and no desktop shortcut created.

I did find a workaround by opening task manager when the app was running, right clicking Google Play Music Desktop Player and selectiong Open File Location.  Location opened was "C:\Users\IT8055\AppData\Local\GPMDP_3\app-3.5.0" and from there made a shortcut from the application to the desktop.

**Comment by MarshallOfSound** [comment] 2016-09-02 13:12
@IT8055 The problem with doing that is that when the app updates the shortcut won't work.

The shortcuts the app makes are special and will work across updates.

**Comment by kevinhaas** [comment] 2016-09-02 18:50
Also experiencing this on a clean install of Windows 10 v1607, build 14393.105. This was literally one of the first things I installed after a format. Also happened when I installed it on two other Win10 machines before this, though.

I'm also using the version specific shortcut as of right now.

**Comment by MarshallOfSound** [comment] 2016-09-09 19:13
Closing this out as I can't reproduce on a multitude of devices so it appears to be Desktop directory location specific.  Nothing much I can do here if windows doesn't reroute the paths for us.

**Closed by MarshallOfSound** 2016-09-09 19:13 UTC
Labels: awaiting response

**Comment by jberanek** [comment] 2016-09-14 12:58
Same issue on my Windows 10 build 1607 desktop.

No Start Menu, even after my recent update to 3.6.0.

Found the app under AppData\Local but it's not ideal to create a shortcut to the individual version executable but as @MarshallOfSound points out, this will break on update

**Comment by jberanek** [comment] 2016-09-14 12:59
However, as another poster I do have a Deskop shortcut, so easy fix is to copy that to my Start Menu

**Comment by gabrieljtaylor** [comment] 2016-10-29 16:36
I'm also getting this issue on a fresh installation of Windows 10 1607 Anniversary Update. I've installed versions 3.6 and 4.0.1, both experiencing the same issue as @sahaskatta - shortcut added to the desktop but not the start menu, no folder redirections. 

This has not occurred on previous fresh installations of Win 10 1607 I've performed, but I'm logged in with the same account as always and I've installed the same other apps as always, so I'm not sure what the difference is. I've restarted my computer to see if perhaps the indexing was being weird and needed a restart to grab the program, but no such luck. The lack of any "Samuel Attard" folder in the start menu/programs folder is likely to blame, but I do not know why it didn't get created.

One thing I can add - the log file `%APPDATA%\Google Play Music Desktop Player\gpmdp.log` does not exist for me, as the location `%APPDATA%\Google Play Music Desktop Player\` does not exist. As such, I have no log to share to help determine the issue. I did expressly run the installer As Administrator, so no permission issues should have prevented the folder from being created during install.

**Comment by jaccarmac** [comment] 2016-11-09 00:24
Also getting this issue. Poking around inside the install folder I found the updater/installer executable and was able to rerun it to get a desktop shortcut at the very least. This was the end of the log after trying to install the package; Unsure whether or not this is expected.

```
2016-11-08 17:20:16> Program: Starting Squirrel Updater: --install app-4.0.2
2016-11-08 17:20:16> Program: Starting install, writing to C:\Users\jaccarmac\AppData\Local\GPMDP_3\app-4.0.2
2016-11-08 17:20:16> Program: RELEASES doesn't exist, creating it at C:\Users\jaccarmac\AppData\Local\GPMDP_3\app-4.0.2\RELEASES
2016-11-08 17:20:16> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```

**Comment by Wielding** [comment] 2017-01-23 15:42
On Windows 10 pro x64 with latest updates and I don't get a desktop shortcut or a start menu shortcut.  Even if I create a shortcut in the start menu folder Windows does not recognize it unless I pin it to the start menu and even then it does not show up when searching the start menu.

Here are the log entries:
gpmdp.log:
{"level":"info","message":"Application started.","timestamp":"2017-01-23T15:34:41.554Z"}

SquirrelSetup.log:
2017-01-23 10:34:42> Program: Starting Squirrel Updater: --download https://update.gpmdp.xyz/update/win/4.1.1
2017-01-23 10:34:42> Program: Fetching update information, downloading from https://update.gpmdp.xyz/update/win/4.1.1
2017-01-23 10:34:42> CheckForUpdateImpl: Generated new staging user ID: 87650665-c03d-5bd3-9edc-9c3d0ae14d8c
2017-01-23 10:34:42> CheckForUpdateImpl: Downloading RELEASES file from https://update.gpmdp.xyz/update/win/4.1.1
2017-01-23 10:34:42> FileDownloader: Downloading url: https://update.gpmdp.xyz/update/win/4.1.1/RELEASES?id=GPMDP_3&localVersion=4.1.1&arch=amd64
2017-01-23 10:34:43> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Remote release File is empty or corrupted
   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()<---
