### ISSUE TITLE
Disabling "Scroll Lyrics Automatically while playing" does not stick

### ISSUE THREAD

**Issue by ChaseyLain** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2603] opened 2017-06-23 16:19 UTC
OS: Windows 7, 64bit

Issue Descriptions: Hey! I have disabled the option "Scroll Lyrics Automatically while playing" as soon as I found the option for the first time - unfortunately it is not always regarded, I still get scrolling lyrics often.
Here is a screenshot of my options window (in case that is any help):
![image](https://user-images.githubusercontent.com/13875896/27490488-bafb37ba-583e-11e7-9d74-7316c7a7ea2e.png)
I was able to reproduce this in the english localisation as well, so I don't think it is down to a choice of localisation!

**Steps to Reproduce:**
1. Start GPMDP
2. Disable the Auto Scroll option in the Desktop settings
3. Play an Album
4. Open the Playlist (bottom right main window button)
5. right click current track -> show lyrics (beta)
-> the lyrics don't scroll, this is correct behaviour
6. Click on album name
7. right click on the current track in the main window album list (not the "current playlist") -> show lyrics (beta) 
-> You have 20% chance of getting scrolling now, if that is not the case, continue step 8
8. Click on the artists name, so the artist "homepage" is opened
9. open lyrics from current playlist
-> Again 20% chance, if not go to next step
10. Click Album name again, go to step 7

This sounds really stupid, as this is a never ending loop of instructions, but it is the only reliable way I found to reproduce! I'm sorry!

I have also had it happen that I have opened the Lyrics window and it was "Manually scrolling" - but after about half of the song it started to scroll automatically! but i did not find a good way to reproduce this.
Thank you guys for all your hard work.

**Comment by MarshallOfSound** [comment] 2017-06-28 00:50
I can't replicate this on the latest development version of GPMDP (and I tried really hard because it sounds like the kind of thing that could arise from my *interesting* lyrics scrolling logic).

As I can't repro it I'm going to close this issue out, if you come up with 100% repro steps I'll gladly reopen this (I can also hope it was fixed soemwhere down the line 😆 )

**Closed by MarshallOfSound** 2017-06-28 00:50 UTC

**Comment by ChaseyLain** [comment] 2017-07-09 11:19
I have not had it happen recently, so I guess you must have fixed it by accident ;) (Although I have not been using GPMDP as heavily over the last weeks)
If it comes back and I find a way to repro, I will happily share! 
Thank you for taking the time, very much appreciated! Great work!

**Comment by ChaseyLain** [comment] 2017-07-13 20:14
[capture.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1146527/capture.zip)
Okay! It has happened to me again and I have spent the last hour trying to figure out "100% repro steps" and I think I got it now. Altough it takes me 3-4 minutes every time to reproduce, it "worked" for me now 4 or 5 times in a row!

So here it goes:
1. Disable Autoscroll, restart GPMDP
2. Open best album on the planet: https://play.google.com/music/m/B5j3pb6rlqiedszypremwdtlvii?t=Ready_To_Die_-_The_Notorious_BIG
3. Play Song #9 - The What (Sorry I make you listen to my everyday music, but it was hard enough to reproduce with this one song, I was not willing to try it on other songs, too^.^ :+1: )
4. Let the song play until about 2:10 (I tried it with skipping to 2:00 and listening until 2:10 - did not work)
5. Rewind to 0:35, listen until ~0:50
6. Open Playlist, Right Click on Song #9 -> Show Lyrics (BETA)
7. Scrolling Lyrics!!! Yeeeeaaaassss!!!

---- Attaching (Very bad) screen cap, only to show im not completely full of sh**

**Comment by SicariusNoctis** [comment] 2017-08-26 10:37
**Bug Reproduction**

**Package:** [gpmdp](https://aur.archlinux.org/packages/gpmdp/) version 4.3.0-1 on Arch Linux

1. Play a song. (For example, [Dream Theater - A Change of Seasons](https://play.google.com/music/m/Txolhxfjoby5xnkcmimz7zswglq?t=A_Change_Of_Seasons_-_Dream_Theater).)
2. Let it play for some amount of time. I recommend at least 2:00. Sometimes it fails as early as 0:45. **Do not seek.**
3. Open the lyrics.

**Comment by SicariusNoctis** [comment] 2017-08-26 10:43
I have no idea if this is the issue (not a JS programmer), but `jumpDetect` is undefined in `LyricsViewer.js`:

    // Handle time progression of a song
    this.timeHandler = (e, timeObj) => {
      $(findDOMNode(this)).find('#lyrics_bar').width(`${(timeObj.total === 0 ? 0 : timeObj.current / timeObj.total) * 100}%`);
      let jumped = false;
      if (Math.abs(timeObj.current - jumpDetect) > 1000) {
        animate = true;
        jumped = true;
    }
