### ISSUE TITLE
Does not respond to media keys

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#521] opened 2016-03-12 15:34 UTC
**OS:**
OSX 10.11.2 & Windows 10 pro
**Issue Descriptions:**
Media keys (forward, previous, play/pause toggle) are not responded to by the app.  
**Steps to Reproduce:**
1. Play a album/radio station and try on of the following pressing the media forward, previous, or play/pause keys

**Notes**
This issue was not present on the windows app before the 3.0 release

**Comment by MarshallOfSound** [comment] 2016-03-12 15:39
Have you read the [FAQ](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ)

**Comment by unknownv2** [comment] 2016-03-14 05:30
I don't have the chrome extension but the media keys don't work. They work in version 2.1.1 though.

I have an ISIGNIA keyboard.

**Comment by MarshallOfSound** [comment] 2016-03-14 10:29
Closing as duplicate of #344

**Closed by MarshallOfSound** 2016-03-14 10:29 UTC
Labels: Read the FAQ...
