### ISSUE TITLE
Uncaught Exception: listen EADDRINUSE 0.0.0.0:5672

### ISSUE THREAD

**Issue by aleonb21** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#914] opened 2016-04-07 18:20 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.1.0
**Time:** Thu Apr 07 2016 14:20:00 GMT-0400 (Eastern Daylight Time)

#### Error:
*listen EADDRINUSE 0.0.0.0:5672*
```js
Error: listen EADDRINUSE 0.0.0.0:5672
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:476:9)
    at process._tickCallback (node.js:382:17)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-04-07 18:21
Closing this automatically reported issue as a duplicate of #325

**Closed by GPMDP-Magical-Unicorn** 2016-04-07 18:21 UTC
Labels: Automatic-Issue-Report, duplicate
