### ISSUE TITLE
Uncaught Exception: listen EADDRINUSE 0.0.0.0:5672

### ISSUE THREAD

**Issue by johnny88** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1243] opened 2016-06-27 11:02 UTC
Running on Ubuntu 16.04
Not sure what caused this but these are the long list of steps between what I imagine could have started the problem and when the problem happened.
- Came back from ubuntu lock state
- Process still running but window could not be seen on screen.
- Animation made it seem like the window was off screen.
- Quit through panel icon
- Process seemed to quit but music was still playing.
- Tried pausing music seemed to work
- Opened app again and saw this error.

I think this might have to do with going to a lock screen and something messing up with the way ubuntu manages windows. I am using two screens and I think coming back from lock messed something up. Not working on the project nor am I an Ubuntu developer so don't know how much water my opinion holds. Let me know if you need anymore info from me.

An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Mon Jun 27 2016 12:54:15 GMT 0200 (CEST)

#### Error:
*listen EADDRINUSE 0.0.0.0:5672*
```js
Error: listen EADDRINUSE 0.0.0.0:5672
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-06-27 11:04
Closing this automatically reported issue as a duplicate of #325

**Closed by GPMDP-Magical-Unicorn** 2016-06-27 11:04 UTC
Labels: Automatic-Issue-Report, duplicate
