### ISSUE TITLE
Issues with small UI

### ISSUE THREAD

**Issue by afollestad** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#147] opened 2016-01-15 03:44 UTC
This is on a Surface Book:

![capture](https://cloud.githubusercontent.com/assets/1820165/12344879/cf5eb8b0-bb07-11e5-8651-a95456e0b874.JPG)

When maximized, the titlebar is still very small in height and text/icon size.

**Comment by MarshallOfSound** [comment] 2016-01-15 03:46
I believe this is a duplicate of #143 and #140 

Check out the builds below:  
[x86 Build](https://ci.appveyor.com/api/buildjobs/k169oa7gx74willf/artifacts/Google%20Play%20Music.Bootstrapper/bin/x86/Release/Google%20Play%20Music%20Desktop%20Player%20x86.exe)
[x64 Build](https://ci.appveyor.com/api/buildjobs/58g0xct0kkaty6fd/artifacts/Google%20Play%20Music.Bootstrapper/bin/x64/Release/Google%20Play%20Music%20Desktop%20Player%20x64.exe)

Hopefully these builds work perfectly :+1: 

Those builds are for the latest commits on master and should contain fixes for your issues.  The fix will be pushed to release soonish

**Closed by MarshallOfSound** 2016-01-15 03:46 UTC
