### ISSUE TITLE
App can't be quit, high resource usage.  Force Quit won't work.

### ISSUE THREAD

**Issue by jaimeurteaga** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3475] opened 2019-01-23 15:35 UTC
App can't be quit, runs on screen close (killing battery very quickly), high resource usage, fan at max while no other apps open.

Force Quit won't work. Terminal kill -9 won't work.

Steps to reproduce unknown, but may been caused by installing iTunes which could have conflicted with it in some way.

Next step... hard restart (ugh).

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,2
  Processor Name:	Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB

**Comment by mattnwa** [comment] 2019-01-25 17:19
✋ I'm having the same issue. Just caught this in htop. It was much worse - around 40 CPU% and fans have been going all out for about 5 minutes. 
![screen shot 2019-01-25 at 11 18 18 am](https://user-images.githubusercontent.com/13283053/51761572-110f2f80-2093-11e9-9690-3895da0148fa.png)

**Comment by arkaus** [comment] 2019-01-28 21:40
I'm experiencing very similar issues. GPDMP is killing performance. There's prominent lag when trying to pause or exit. I'm running this on my iMac 5K (Late 2015) with MacOS Mojave. I haven't experienced this issue on my Windows 10 PC at home.

**Comment by orxon** [comment] 2019-02-06 06:06
Hi - I was experiencing similar issues and pulling my hair out until I stumbled across a similar bug report #3120 

Basically there's a problem in the codebase right now (or has it recently been fixed? I dont keep up to date) whereby rich presence to discord will send an RP update event every few milliseconds when Discord is not present.

Can you guys confirm you're using Discord Rich Presence setting in the Desktop Settings section of the sidebar? And if so - is discord actually running?

If so my bandaid fix is opening discord, counting to 3, then opening GPMDP. I'd contribute but the languages used in this app are far from my forte :(

Good luck.

**Comment by arkaus** [comment] 2019-02-06 15:37
Discord Rich Presence was turned on but I didn't have Discord open.

**Comment by dannyk08** [comment] 2019-02-08 17:45
Issue is still persistent
Just getting the song to pause took half a song ~2mins

**Comment by chrisspiegl** [comment] 2019-02-08 19:56
I am generally experiencing performance and efficiency issues as well. For me, it's on my MacBook and it just hangs up and uses 99.9% of CPU power, fans are blowing at full speed.

This is not as `Resource Efficient` and `Lightweight` as it's advertised 🙈.

I hope there can be some improvements made (especially since there was no new release over half a year.

**Comment by hpeyerl** [comment] 2019-02-10 16:19
Chiming in to report the same issue on OSX 10.13.6.  Will play for a couple of hours and then hang solid.  Force Quit reports "App not responding".  It's consuming 100% CPU.

Discord Rich Presence is not turned on in my configuration.  

Running 4.6.1.

**Comment by maetthu** [comment] 2019-02-11 14:01
I can also reproduce this with 4.6.1. running on Arch Linux., so it doesn't seem to be limited to MacOS, although a kill -9 does work for me, terminate from menu or with a TERM signal doesn't. Discord Rich Presence is turned off.

**Comment by JRileyH** [comment] 2019-02-11 20:57
Coming into report similar experience. Pretty recently started experiencing application hanging / not responding, difficult to quit, and using exorbitant amount of CPU share on Macbook pro. Thinking I'll have to switch back to official webapp soon if resolution isn't around the corner. 

Probably unrelated but coincidentally around the same time Cmd-Q for quitting started opening crash report alerts.

**Comment by pbentkowski** [comment] 2019-02-12 16:17
$ google-play-music-desktop-player 
Starting Sentry
*** WARNING *** The program 'Google Play Music Desktop Player' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player>
*** WARNING *** The program 'Google Play Music Desktop Player' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player&f=DNSServiceRegister>
*** WARNING *** The program 'Google Play Music Desktop Player' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player>
*** WARNING *** The program 'Google Play Music Desktop Player' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player&f=DNSServiceRegister>
*** WARNING *** The program 'Google Play Music Desktop Player' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player>
*** WARNING *** The program 'Google Play Music Desktop Player' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=Google Play Music Desktop Player&f=DNSServiceRegister>

**Comment by tseven** [comment] 2019-02-12 22:57
I am experiencing the same issue. Player becomes unresponsive.
Discord feature unchecked.

Issue happens whether discord is running or not.

iMac 27" (Late 2013) 3.5Ghz Core i7 32GB Ram
macOS High Sierra 10.13.6
GPMDP 4.6.1

**Comment by cjcox17** [comment] 2019-02-13 02:51
Also having this issue as well. It just started happening after I updated to MacOS Mojave 10.14.3 from the previous version after they fixed the facetime bug.

2018 15" MacBook Pro Intel Core i9 32GB Ram
macOS Mojave 10.14.3
GPMDP 4.6.1

**Comment by tseven** [comment] 2019-02-13 18:11
It looks like a fix is on it's way #3483, but for those who can't wait I've compiled a macOS version without the "lyrics" functionality. This seems to be the main issue and has solved the freezing issues I experienced.

I simply commented out `import './lyrics';` in `src/main/features/core/index.js`
and compiled.

Sorry I don't have the time to compile for the other platforms.

Download [Fixed-Google Play Music Desktop Player-darwin-x64.zip](https://drive.google.com/open?id=19fuKAEHtkb-I7cs_z-1KhZxuBr3zK-c2)

MD5: `79d4ba47b919c8bbf6b125563a900183`

[Virustotal results](https://www.virustotal.com/#/file/69858b85e76d839efd52af8c1accb21114e92750a1d65497c2e5e35f8def456f/detection)

**Comment by MarshallOfSound** [comment] 2019-02-13 18:19
Sorry @tseven we have a policy of no outside linked binary's regardless of virustotal results

Here is a link to a signed artifact built on our CI: [zip file](https://2966-40008106-gh.circle-artifacts.com/0/Users/distiller/project/dist/installers/darwin/Google%20Play%20Music%20Desktop%20Player.zip)

**Comment by tseven** [comment] 2019-02-13 18:50
I completely understand and agree. Thank you for the link to the fixed archive.

Also, thank you for organizing the code so well. It's refreshing to see clean code that is easy to digest.

**Comment by MarshallOfSound** [comment] 2019-04-23 02:48
Duplicate of #3483

**Closed by MarshallOfSound** 2019-04-23 02:48 UTC
