### ISSUE TITLE
Unable to login to GPMDP v4.6.1 on Windows 10

### ISSUE THREAD

**Issue by Wilkshire13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3715] opened 2019-12-11 00:47 UTC
**Checklist:**

* [X] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [X] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [X] I have double checked and can reproduce the issue

**OS:**
Windows 10

**GPMDP Version:** 
4.6.1 

**Issue Descriptions:**
I cannot use GPMDP. It will not load in, just sits on the "loading Music Libray" screen.
Uninstalled and reinstalled it and now it will not allow me to login and provides the following error.
"You are trying to sign in from a browser or app that doesn't allow us to keep your account secure."

**Steps to Reproduce:**
Open GPMDP - Error occurs
Uninstall and Reinstall - Attempt to Login and error occurs
![GPMDP error](https://user-images.githubusercontent.com/58755477/70581631-e4f99000-1c0b-11ea-83b8-53e7365a0991.PNG)

**Comment by halkun** [comment] 2019-12-11 01:24
Similar issue on mine too, just encountered it just now. When opening the app in Windows 10, the app also greets me with the following: "Loading Music Library".

https://i.imgur.com/pQBgcJV.jpg

**Comment by DanLauer** [comment] 2019-12-11 01:26
Same issue.

**Comment by jostrander** [comment] 2019-12-11 01:27
Duplicate of #3545

**Closed by jostrander** 2019-12-11 01:27 UTC
