### ISSUE TITLE
White Line on the Bottom When Maximized

### ISSUE THREAD

**Issue by dimalantak** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1066] opened 2016-05-11 19:02 UTC
**OS:** Windows 10

**Issue Descriptions:** Using the dark theme, when maximized there is a very obvious white line on the bottom of the application. Issue does not appear or is unnoticeable when using 100% scaling.
![image](https://cloud.githubusercontent.com/assets/18562864/15192933/5895c262-1770-11e6-960c-1d705327ba0d.png)

**Steps to Reproduce:** Have 200% display scaling, dark theme enabled, maximize the window.

**Comment by MarshallOfSound** [comment] 2016-05-12 02:06
Although not obvious this an underlying problem in electron and is a duplicate of #978

**Closed by MarshallOfSound** 2016-05-12 02:06 UTC
