### ISSUE TITLE
Request: Custom Highlight Color for "Music" text

### ISSUE THREAD

**Issue by gsingh13** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#81] opened 2015-12-05 22:01 UTC
First, love this application and the ability to turn the player black, but can you please add the "Music" part of Google Music on the top left to change with the selected highlight color i.e. if I choose red, it stays green.

- Thanks!

**Comment by MarshallOfSound** [comment] 2015-12-05 23:37
This is a duplicate of #71 and has been fixed in master.

It will be in the next release

**Closed by MarshallOfSound** 2015-12-05 23:37 UTC
