### ISSUE TITLE
Chromecast Audio Groups not working

### ISSUE THREAD

**Issue by gabestover** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1530] opened 2016-08-25 14:01 UTC
OS: Windows 10 x64

Issue Descriptions: casting to any single chromcast works perfectly.  However, any Chromecast Audio Groups do not work.  The app says that it's connected to the group, but I don't believe it connects.  The Chromecast Audio devices that I have set to make a sound on connect do not make that sound.  More importantly, when the audio group is selected, there's no audio playback.  the app thinks it's connected and is playing, but no audio whatsoever.  If I then switch back to a single chromecast or the computer's speakers, everything works fine as normal again.

Steps to Reproduce:
-make an audio group of two or more chromecast audio devices via the cast app on android or ios
-try to cast to audio group in GPMDP; GPMDP shows that it's connected, but no audio plays

Also, all chromecast audio groups show up with their name followed by "(1)", for instance if your audio group is called "House Music", it displays in GPMDP as "House Music(1)"

**Comment by MarshallOfSound** [comment] 2016-08-25 14:18
This is a duplicate of the upstream issue in our Chromecast implementation https://github.com/GPMDP/electron-chromecast/issues/8

**Closed by MarshallOfSound** 2016-08-25 14:18 UTC
