### ISSUE TITLE
Program icon on the lower left corner is "dirty" after the latest update

### ISSUE THREAD

**Issue by Jesekki** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3169] opened 2018-06-24 10:35 UTC
OS: Windows 10 64-bit
GPMDP Version: 4.6.0
Issue description: After updating to 4.6.0 the icon on the lower left side of taskbar has become "dirty" as in it has black spots on the top and little bit on the lower side of the icon. The program is pinned on my taskbar if that matters. I tried changing the icon of the shortcut that's pinned, but that doesn't fix it if I change it to the same that it was (it shows clean icon when choosing the icon but becomes dirty after clicking OK). Changing to different icon fixes it, only the default icon becomes dirty. Restarting PC didn't help.

Link to screenshot showing the icon: https://imgur.com/a/IYMPoXJ (click the pic to see it bigger)

**Comment by Alipoodle** [comment] 2018-06-24 13:34
![image](https://puu.sh/AL65b/3063cc899e.png)
Repro Windows 10 64

**Comment by ChildishGiant** [comment] 2018-06-24 18:10
![image](https://user-images.githubusercontent.com/13716824/41822082-30745076-77e2-11e8-8535-2cda06f29cc4.png)
Running windows 10 Version 1803 (17134.112)

**Comment by Stanzilla** [comment] 2018-06-24 18:29
Duplicate of https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3069

**Comment by jatk** [comment] 2018-06-24 19:50
Same issue, seems to only occur when the program is pinned to the taskbar if unpinned it looks fine.

**Comment by MarshallOfSound** [comment] 2018-06-25 11:01
@jostrander I think neither, the icon is 100% valid.  I'm pretty sure windows is for whatever reason having trouble rendering it 🤔

**Closed** 2018-06-25 11:37 UTC
Labels: type/bug

**Comment by chrisknepper** [comment] 2018-06-26 00:53
Hi there,

I am seeing this [issue in my](https://github.com/chrisknepper/android-messages-desktop/issues/3) Electron project as well. Does the package you introduce in 18738b3 seem to fix it? For both of our programs, the artifacts/corruption seem to appear when the application shortcut is pinned to the taskbar as seen in this video I took:

https://i.imgur.com/pCQ5lTx.gifv

**Comment by MarshallOfSound** [comment] 2018-06-26 01:40
@chrisknepper I'm like 99% sure this is a windows issue, but basically the trick in the past has always been make the underlying SVG as SIMPLE AS POSSIBLE then convert it to `.png`. then to `.ico`.

Just note that Windows has this annoying thing called an icon cache, so when you try test fixes locally you have to clear the icon cache and restart your computer every time.

**Comment by chrisknepper** [comment] 2018-06-26 02:28
Ah, oh boy. Thought I could avoid Windows' pitfalls by going Electron 😛 

Thanks for the tips. I'll look into it soon. Love your app btw!
