### ISSUE TITLE
MacOS Memory Leak

### ISSUE THREAD

**Issue by step1041** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2997] opened 2018-02-09 14:33 UTC
[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1711313/debug_info.zip)

**OS: MacOS X 10.13.3**

**Issue Descriptions: Memory leak of around 2-3MB/s**

**Steps to Reproduce: Opening the app. Re-downloading does not solve.**

**Comment by jostrander** [comment] 2018-02-09 16:11
Duplicate of #2969

**Closed by jostrander** 2018-02-09 16:11 UTC
