### ISSUE TITLE
Last.fm scrobbling isn't working reliably. (using Release 4.4)

### ISSUE THREAD

**Issue by ryanbr** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2671] opened 2017-07-27 09:45 UTC
**OS:**
Windows 10 64bit (New install), No 3rd party Anti-virus or firewall.

**Issue Descriptions:**
Google Play music desktop isn't reliably scrobbling, of the music I'm listening too often most won't be scrobbled.  I listened to 3 albums (seperate tracks), of which only 2 tracks were scrobbled.

**Steps to Reproduce:**
I'm not sure how to debug this, other than playing music and seeing how much is being reliable sent to last.fm. I'm going to test older versions when I get the chance

**Comment by MarshallOfSound** [comment] 2017-07-27 09:47
Duplicate of #2630

**Closed by MarshallOfSound** 2017-07-27 09:47 UTC

**Comment by nikita-nikiforov** [comment] 2017-07-29 09:18
Have this problem too.

**Comment by Maddieman** [comment] 2017-08-01 11:07
So the workaround for the time being (until the fix in #2630 is deployed) is to not minimise the player in windows, is that correct?

**Comment by jschuringa** [comment] 2017-08-10 17:58
@Maddieman does that mean it has to be focused, or just not minimized?

**Comment by nikita-nikiforov** [comment] 2017-08-11 07:55
@jschuringa not minimized

**Comment by Maddieman** [comment] 2017-08-11 09:37
@jschuringa what I'm doing for now is just using the mini-player mode (the light grey arrow icon in the bottom right hand corner), with always on top enabled in the settings.  Otherwise I'm prone to minimising it on habit.  That's worked fine so far.
