### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by CT101** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#579] opened 2016-03-14 15:58 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Mon Mar 14 2016 11:56:26 GMT-0400 (Eastern Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\CT\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\CT\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

Was trying to use play/pause media key. Currently that key doesn't seem to be working on the new version.

Thanks,
CT

**Comment by MarshallOfSound** [comment] 2016-03-14 16:00
This issue has been fixed and will be auto closed by the unicorn shortly.  In regards to the play/pause key, unfortunately until I push an update the only way to handle this is to restart the app.

Next update there will be a completely new way of handling media keys on windows anyway so this will definitely be fixed

**Comment by CT101** [comment] 2016-03-14 16:02
Thanks! I'll wait patiently for the update! Love the app!

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-14 16:07
Closing this automatically reported issue as a duplicate of #470

**Closed by GPMDP-Magical-Unicorn** 2016-03-14 16:07 UTC
Labels: Automatic-Issue-Report, duplicate
