### ISSUE TITLE
Not registering as app

### ISSUE THREAD

**Issue by JJSax** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1503] opened 2016-08-20 20:16 UTC
**OS:**
Windows 10 Home 640bit (10.0, build 14393)
**Issue Descriptions:**
The app doesn't register under the start menu.  

It seems like it's opening as a file but not a program. I don't exactly know how to describe it.  It works properly, but doesn't register in the start menu and I can't actually get it in there.  I want to be able to use my open music media key to open it since it's my favorite music app ever! :) 
**Steps to Reproduce:**
Install app.

**Comment by morbidxbean** [comment] 2016-08-21 03:09
I am going to add to this as I have experienced this problem.  I run the executable, I see the "Installing Google Play Music Desktop Player" Splash.  The application launches and functions just fine.  If I close it out and try to launch it again, I can not locate it under the start Menu, No Desktop Icon, Program Files / Program Files (x86) (though I am not sure where it would install to).  I run the exe again, it runs through the installation process fine and loads/works perfectly.

Windows 10 Pro N 64bit 1607 build 14393.51

**Comment by jostrander** [comment] 2016-08-21 15:45
I removed my install and grabbed the latest copy to test this and can't confirm.

**Comment by user0706** [comment] 2016-08-21 17:22
Same issue for me.
Running an exe installs it everytime, it doesn't add it to Start menu or something.

Windows 10 Ent N x64 1607 14393.51

**Comment by jostrander** [comment] 2016-08-21 17:41
Okay, what is the common denominator, besides windows 10. I'm on 14393.51 as well and can't reproduce. What anti-virus do you use? Can you attach your squirrel setup logs?

**Comment by MarshallOfSound** [comment] 2016-08-21 17:49
@jostrander Shortcuts are no longer handled by Squirrel.  They are handled internally by Electron API's.

Can you guys please launch launch GPMDP from Command Prompt with the following commands

```bash
cd %LOCALAPPDATA%\GPMDP_3\app-3.5.0
set ELECTRON_ENABLE_LOGGING=true
set ELECTRON_ENABLE_STACK_DUMPING=true
Google%20Play%20Music%20Desktop%20Player.exe --squirrel-install
```

**Comment by morbidxbean** [comment] 2016-08-22 02:59
I ran the commands under both a user level and elevated CMD - I also removed the GPMDP_3 folder and ran the install file again before trying to launch it in CMD.   It seems to just hang.

`Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Jimbo>cd %LOCALAPPDATA%\GPMDP_3\app-3.5.0

C:\Users\Jimbo\AppData\Local\GPMDP_3\app-3.5.0>set ELECTRON_ENABLE_LOGGING=true

C:\Users\Jimbo\AppData\Local\GPMDP_3\app-3.5.0>set ELECTRON_ENABLE_STACK_DUMPING=true

C:\Users\Jimbo\AppData\Local\GPMDP_3\app-3.5.0>Google%20Play%20Music%20Desktop%20Player.exe --squirrel-install

C:\Users\Jimbo\AppData\Local\GPMDP_3\app-3.5.0>

`

**Comment by MarshallOfSound** [comment] 2016-08-22 03:31
@morbidxbean And after running that the shortcuts weren't generated at all?

**Comment by morbidxbean** [comment] 2016-08-22 03:40
Hey!  I think we are good.   So I did not notice any icons generate in the start menu or Desktop.  However I have my actual Desktop mapped to a separate drive.  (Z:\Desktop)   The  Commands I ran (or could have been the actual installer in the first place) placed the icon in the default "Desktop" folder... (C:\Users\name\Desktop).   I looked there and sure enough the lovely Icon was there.  

Same instance / somewhat different situation with the start menu I believe... (%appdata%\Microsoft\Windows\Start Menu).  When I look under there I see an Icon.  However if I look under the start menu itself I cant see it :\

**Comment by MarshallOfSound** [comment] 2016-08-22 03:46
@morbidxbean Wait, how do you map your desktop / appdata to a different drive.

It sounds like you did it in a strange way 👍

**Comment by morbidxbean** [comment] 2016-08-22 03:54
The Default Library folders that come with windows (Documents, Downloads, Music, Pictures, VIdeos)  If you right Click > Properties on those, there is a Location tab where you can change where the files are stored.  I choose to have them on a second hard drive based on preference.  I'm just stumped on what initially happened that put my preference system off sync lol.

**Comment by MarshallOfSound** [comment] 2016-08-22 04:09
So this is likely a windows issue (remapping your folders but not updated %APPDATA%)?

**Comment by morbidxbean** [comment] 2016-08-22 04:34
I am going to say that it is a windows problem.  I installed the app just fine w/ no issues under a VM running windows w/o modifications to the folder design.  

@JJSax ;  Perhaps you have a similar configuration as myself?  Take a look in your C:\Users\name\Desktop directory to see if there is an icon.

**Comment by MarshallOfSound** [comment] 2016-08-22 04:40
It's highly likely.  If you guys want a shortcut you can just copy paste those ones.

Don't make your own as the shortcuts use a fancy trampoline launch mechanism that makes the shortcut work across updates.  If you make your own the shortcut will break after each update.

**Closed by MarshallOfSound** 2016-08-22 04:40 UTC
Labels: Unconfirmed, Windows
