### ISSUE TITLE
Defualt media keys don't work anymore

### ISSUE THREAD

**Issue by voragoth** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#714] opened 2016-03-21 15:29 UTC
**OS:** Windows 7 64 
**Issue Descriptions:**
default media keys  don't work anymore at new 3 .x.x version
**Steps to Reproduce:**
Install the new version (I even clean all the data at appdata/local-roaming, and program files)
Try to use default media keys (globally and with the app as front window)

**Comment by lucasogodoy** [comment] 2016-03-21 16:04
Same happening here. Actually, when I installed the program it showed an error (couldn't print it at the time) and then it wasn't working anymore and the message isn't showing anymore.
OS: Windows 10 64

**Comment by codyconfer** [comment] 2016-03-21 17:48
Can you guys give more information on the keyboards you are using? My media keys work fine with a Microsoft brand keyboard, while someone I work with is having issues with a Logitech keyboard.

**Comment by lucasogodoy** [comment] 2016-03-21 17:50
It's a Microsoft Wireless Keyboard 800.

**Comment by voragoth** [comment] 2016-03-21 18:27
In my case the keyboard of a Dell Latitude 5500 laptop.

**Comment by codyconfer** [comment] 2016-03-21 18:29
Awesome, thanks. I can't reproduce the issue but I will try more after work.

**Comment by MarshallOfSound** [comment] 2016-03-21 22:03
This is a duplicate of #344 

This issue has been fixed and will be pushed out in `3.1.0`

There are also workarounds in the FAQ

**Closed by MarshallOfSound** 2016-03-21 22:03 UTC
