### ISSUE TITLE
Uncaught Exception: The request timed out.: (null)

### ISSUE THREAD

**Issue by mmond21** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1181] opened 2016-06-12 11:56 UTC
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Sun Jun 12 2016 06:56:18 GMT-0500 (CDT)

#### Error:
*The request timed out.: (null)*
```js
Error: The request timed out.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-06-12 12:02
Closing this automatically reported issue as a duplicate of #235

**Closed by GPMDP-Magical-Unicorn** 2016-06-12 12:02 UTC
Labels: Automatic-Issue-Report
