### ISSUE TITLE
Stuck on "Loading Music Library…"

### ISSUE THREAD

**Issue by Mystic-Mirage** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3719] opened 2019-12-11 22:02 UTC
**OS:** Xubuntu 18.04

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Stuck on "Loading Music Library…" in Google Play Music mode. YouTube Music mode works. It worked a couple of days ago.

**Steps to Reproduce:** Start Google Play Music Desktop Player

![image](https://user-images.githubusercontent.com/1079805/70664034-405e6900-1c72-11ea-98d9-546ba74a7675.png)

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/3952782/debug_info.zip)

**Comment by KROSF** [comment] 2019-12-11 22:28
duplicate of #3660

**Closed** 2019-12-11 22:54 UTC
