### ISSUE TITLE
Hotkey for Your Mix on YT Music

### ISSUE THREAD

**Issue by TheDutchMC** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3892] opened 2020-10-07 20:04 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Win 10

**GPMDP Version:**
Version: 4.7.1

**Issue Descriptions:**
The GMDP app has an option for a hotkey for 'Im Feeling Lucky'. I would like to see the same for 'Your Mix' on the YT music app, since that is the last thing keeping me with Gmusic.

**Steps to Reproduce:**
None

**Comment by jostrander** [comment] 2020-10-15 15:22
I toyed with this for a few and I'm not 100% sure its possible yet. The Feeling lucky happened to be its own button in the GPM UI so I was able to target it specifically from anywhere. However the "Your Mix" playlist is not as easy to single out.

**Comment by CydeSwype** [comment] 2020-10-15 19:17
I don't know if it's worth a separate ticket, but thumbs up/down hotkeys seem to have the same issue.  Likely fall in the same bucket as to whether they're able to be supported or not.

**Comment by jostrander** [comment] 2020-10-15 19:25
![image](https://user-images.githubusercontent.com/760989/96176643-9f2be900-0efa-11eb-9f41-160331ab1cc8.png)
The thumbs up/down icons are always visible while playing audio, so the hotkey would always correspond to these two buttons.

**Comment by CydeSwype** [comment] 2020-10-15 22:24
@jostrander that's true but i've tried several hotkey combinations (i.e. ctrl+shift+up for thumbs up) in the settings and i can't get any of them to work for thumbs up/down.  hotkeys work fine for next/prev (i.e. i currently have ctrl+shift+right for next track).  thumbs up/down worked fine for GPM but doesn't seem to work for YTM.  if this feels unrelated, i'll break it off to a separate issue.

**Comment by jostrander** [comment] 2020-10-15 22:41
There seems to be some kind of disconnect between the hot keys and ytmusic.js, but it ytmusic.js has it implemented, so it should be fine in future builds once that's resolved. A separate issue would be fine.

**Comment by TheDutchMC** [comment] 2020-10-16 22:03
Might be a stupid suggestion, since I'm not a JS developer and usually only do backend work:

I'm not sure how the the elements are build up in YTM, but I assume every 'block' (like the My Mix block) has a common parent object (e.g a div). And I think it is safe to assume that the My Mix text is a constant. Wouldnt it then be possible to use e.g jquery's getElementById (or similar, again, im no JS dev) function to find the text, and then go to the parent object a couple times until you are able to get the element which needs to be clicked to start the playlist.

**Comment by jostrander** [comment] 2020-10-17 19:11
@TheDutchMC In vanilla browser JS it's possible to find that element using `document.querySelector('[title="My Mix"]')`, however this has two implications.
1.) "My mix" is an english string, and will change based on the users locale.
2.) This query selector breaks when the page longer contains an element containing this title. 

We had a similar issue in GPM but GPM is a little different in its implementation. On the right bar on the home page is a `customElement` powered by GPM code called `gpm-ifl-button`, so if  you put an element anywhere inside of <body> with the tag `<gpm-ifl-button>` then force a `click` to that element it fires that native application code, from anywhere, hence why we can create a hotkey for it. You can see this [here](https://github.com/gmusic-utils/gmusic.js/blob/master/src/namespaces/PlaybackNamespace.js#L40-L44) and [here](https://github.com/gmusic-utils/gmusic.js/blob/master/src/namespaces/PlaybackNamespace.js#L179-L181).

My initial research is showing that in YTM there is no specific element for "My Mix". Its just a standard playlist element. I am however still trying to figure out if the playlist ID that it calls is generic, or generic per user, or just random altogether based on some backend playlist that they've generated for "my mix". If I can narrow it down to being generic/generic per user I can probably do what I did with GPM and create a new playlist element off screen with the my mix ID, if not it's going to be trickier.

**Comment by TheDutchMC** [comment] 2020-10-21 13:34
If there were multiple, it would just return an array right? Then you should be able to just take the 0th element from that list and use that, since the button does the same regardless of where it is on the page (to my knowledge)

For the multi language thing I wouldn't know a solution straight away, if there's a specific tag or Id like you mentioned that'd be great. But if not, translation files maybe?

Again though I'm not at all familiar with how YouTube music is layed out in the code, and JS isn't my strong suit 😃

**Comment by jostrander** [comment] 2020-10-21 13:55
What if there is none? That's the problem I'm running into. On the explore and library pages as well as I'm sure multiple other pages in the UI the my mix link disappears.

**Comment by TheDutchMC** [comment] 2020-10-21 17:48
Hm that is a good point yeah. That'd cause all kinds of errors.

Is there any way to maybe switch pages, without pulling the application to the foreground? E.g when the user is not on the home page, note where they are now, switch to home, select My Mix and move back?

**Comment by jostrander** [comment] 2020-10-21 17:54
That is a potential option, however it could be jarring to someone if they are actively viewing the application when that happens. Ideally finding some kind of an internal hook for it would be ideal. I'll toy around with it some more and see if I can find anything more concrete to hook into.

**Comment by jostrander** [comment] 2020-10-21 17:58
If you can, could you run this in the console when viewing the home page with "Your mix" visible and screenshot the result?

`document.querySelector('[title="Your Mix"]').href.replace('https://music.youtube.com/', '')`

I'm curious what the playlist ID is for other accounts other than mine.

**Comment by TheDutchMC** [comment] 2020-10-21 18:21
Output of that is `watch?playlist=RDMMCOt5MibFxMs`

**Comment by jostrander** [comment] 2020-10-21 18:54
From what I can gather, all "Your mix" playlists start with RDMM, however the part after that is actually the unique ID per account. If you've never listened to music on an account the list ID is just "RDMM". The other problem I've come across is, creating a dummy dom node with that playlist ID then virtually clicking it does not actually work as intended.

**Comment by TheDutchMC** [comment] 2020-10-22 13:03
Virtually creating the element doesn't work you say, what if you (if you're able to get it) click the real element, rather than creating your own?

**Comment by jostrander** [comment] 2020-10-22 13:14
Were back to the original issue at that point, how do I access that element 100% of the time when its not available 100% of the time. If you use that JS from a couple comments back `document.querySelector('[title="Your Mix"]')` and click around the interface while trying to use it, you'll notice its blank most of the time.

**Comment by TheDutchMC** [comment] 2020-10-22 13:39
Yeah that's a good point. Only thing I could imagine doing then is either switching the tab, clicking it, and switching back. Or opening a hidden page of Home, click it, and destroy the hidden page again

**Comment by llacb47** [comment] 2020-10-22 14:18
The ID is in the source code, in some JSON. How about this?
```
let longpath = initialData[1].data.contents.singleColumnBrowseResultsRenderer.tabs[0].tabRenderer.content.sectionListRenderer.contents[0].musicCarouselShelfRenderer.contents;
for (var i = 0; i < longpath.length; i++) {
  if (longpath[i].musicTwoRowItemRenderer.thumbnailRenderer.musicThumbnailRenderer.thumbnail.thumbnails[0].url.includes("/ytm/images/pbg/my-mixtape-")) {
    console.log("My Mix Playlist ID: " + longpath[i].musicTwoRowItemRenderer.navigationEndpoint.watchPlaylistEndpoint.playlistId)
  }
}
```

**Comment by jostrander** [comment] 2020-10-22 14:22
Where does `initialData` come from?

**Comment by jostrander** [comment] 2020-12-10 21:44
I'm thinking we can close this now that YouTube has nixed the My Mix feature and turned it into a bunch of mix playlists.

**Closed** 2020-12-10 21:44 UTC
Labels: service/ytm
