### ISSUE TITLE
Desktop settings cannot be found in 1.8.0 (in french and spanish at least)

### ISSUE THREAD

**Issue by Leogiciel** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#58] opened 2015-11-26 12:26 UTC
Cannot access to desktop settings as the item cannot be found in the left panel.
![capture](https://cloud.githubusercontent.com/assets/1555868/11423026/3e86e908-9441-11e5-9bc4-af40e9f9c112.PNG)

**Comment by Javierdsv** [comment] 2015-11-26 13:34
This happened to me too. And applies to the back/forward controls.   
The problem is they are designed for English only,  I had my Google account configured in Spanish, and as soon as I changed the global Language to English, both, the settings and controls appeared and worked fine.

**Comment by Leogiciel** [comment] 2015-11-26 14:59
Thanks, I thought about it when they marked my first issue as invalid.

Title updated.

**Comment by daniel037589** [comment] 2015-11-26 17:39
I also can't find the settings in the Dutch version

**Comment by MarshallOfSound** [comment] 2015-11-26 17:47
Yup, the lanuage thing is annoying.  I'm looking into changing the JS to not care about language, but I don't know exactly what google changes from language to language

**Comment by MarshallOfSound** [comment] 2015-11-26 17:50
Issue will be a JS error somewhere on these lines.  https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/Google%20Play%20Music/Resources/custom-interface.js#L51-L90

**Comment by MarshallOfSound** [comment] 2015-11-26 18:58
All fixed, I have testing in like 5 languages (French, Spanish, Dutch, German and some version of Russian).  They all appear to work as expected, this fix will be going out ASAP with the next release (hopefully tomorrow, if not the day after).  Hang in their folks, you'll be using all the features very soon :smiley_cat:

**Comment by The2rB** [comment] 2015-11-27 10:31
This seem to still be present.
My app is using English language - and my OS is in Norwegian.
(Where does the app get its language from? Tried to set Google Chrome to English (USA) with no luck in making the settings appear.)

![tb-151127-1127-29001](https://cloud.githubusercontent.com/assets/5319973/11439143/ec0885b0-94f9-11e5-814b-7bdb32a4122a.png)

Tried both x86 and x64 versions.

**Comment by MarshallOfSound** [comment] 2015-11-27 10:42
It should no longer matter in any way what language you use.  And to prove it, I set my language to Norwegian and it still works 
![working](https://cloud.githubusercontent.com/assets/6634592/11439447/5bb9415e-9560-11e5-8c14-f4bcfcbbce95.PNG)

Can you please ensure you are up to date (1.9.0).  If you are up to date, I would suggest deleting the app and reinstalling it.  Other than that I don't really know why you can't see it

**Comment by The2rB** [comment] 2015-11-27 14:24
Strange.
As I said - I tried both the x86 and the x64.
Uninstalled, deleted, reinstalled.
Did not help.

How did you change the language? Does the language come from Chrome?
I changed my language to norwegian in Chrome and in the Google Account settings (Google Play Music on the web is now in Norwegian) - but the app is still in English - and the Desktop Settings are missing.

Well - I'll have another go at it on Monday.
Not a big deal if I'm the only one with this problem ;)

**Comment by Leogiciel** [comment] 2015-11-27 16:38
I confirm it is working for me, without having uninstalled 1.8.

**Comment by MarshallOfSound** [comment] 2015-11-27 20:22
@The2rB As I said, language should have no effect.  What I'm going to do, is build the app for you but with devtools turned on, so you can see any errors that pop up.  Gimme a few hours and I'll upload it

**Comment by The2rB** [comment] 2015-11-30 08:46
Running with devtools activated sounds interesting.
For some reason I still can not get it to work.

Total uninstall and reinstall today - did not help.
Also tried running as administrator - did not help.

Thanks for showing interest in my problem - even though it had been fixed for everyone else.
If you are interested in me trying to run with devtools - I'll do that.

Have a nice day.

**Comment by rprouse** [comment] 2015-12-01 03:14
@The2rB you are not the only one. It is happening to me on several computers, Windows 8.1 and 10. I originally installed 1.8.0, but figured it would be fixed with the first run initialization bug. I uninstalled and then installed the 64 bit version of 1.9.0 and it is still happening. Looks to me like none of the JS injections are working, I still get the notifications and app menu in the upper right.

![image](https://cloud.githubusercontent.com/assets/493828/11491357/28755ac0-97af-11e5-95a6-2433f55fd262.png)

![image](https://cloud.githubusercontent.com/assets/493828/11491362/32028784-97af-11e5-9046-80b09e8c4ad0.png)

My OS is running Canadian English.

If I get a chance, I will clone the repo and try to debug the problem. If you could point me to the place where you do the Javascript injection, it would be helpful. I probably won't be able to get to this until Wed though, I need to get the 3.0.1 release of NUnit out tomorrow.

**Comment by MarshallOfSound** [comment] 2015-12-01 03:38
@rprouse @The2rB Sorry guys, I've been quite busy at work the last couple of days and can't even work on it at lunch because we operate of macs @ work :smile_cat: 

I'll try get you guys a build from Chromium devtools enabled tonight, that should tell us if it is a JS error or if the JS isn't being injected at all.


And @rprouse the relevant injection code (although I am 99% sure the code is being injected) is [here](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/Google%20Play%20Music/ResourceHandlerFactory.cs).  
The basic logic in that file is:  Every time the user navigates to the main GPM page wait for the first javascript file to be requested via http, fetch that file with a C# WebRequest and then add our JS code to the end of the fetched file before returning it.

It's more likely that some selectors in the injected JS are failing and causing some of the functionality not to run.

**Comment by MarshallOfSound** [comment] 2015-12-01 04:23
Guys, I just noticed something.  Paging @The2rB and @rprouse 

You guys both have this "Send a Gift" option, what on earth is that????????

**Comment by MTRougeau** [comment] 2015-12-01 04:25
US only option right now, I think. Let's you gift a GPM subscription to
someone else.

**Comment by MarshallOfSound** [comment] 2015-12-01 04:26
If I had to guess, that's somehow screwing with my selectors... Goddam Google US only features :cry:

**Comment by MarshallOfSound** [comment] 2015-12-01 05:55
OK Guys, @MTRougeau @The2rB @rprouse  Here is a debug build, when you open it another window will force itself on top of everything else.  This window is the dev tools, click on console and a list of errors will appear.

Screenshot that list of errors and upload it here so I can see what's going on.  Thanks :cactus: 
https://mega.nz/#!CA0G1KqI!ipa1R60XKj6Pc6xmKRxPHlmguxiSMBmGTFVzaRetQTk

**Comment by The2rB** [comment] 2015-12-01 07:36
I'm not running the US version - and do not have the gift option available. (Just as a notice.)

**Comment by The2rB** [comment] 2015-12-01 07:37
Here is the console-log:

![tb-151201-0836-19001](https://cloud.githubusercontent.com/assets/5319973/11494855/b377f5c2-9806-11e5-9bcc-adfc9661c023.png)

Thanks for trying to figure this out.

**Comment by MarshallOfSound** [comment] 2015-12-01 08:48
OK, the last error is the one that is relevant.  That gives me the cause, now I just need to find a solution... That will be tricky given I can't replicate the issue but stay tuned and I'll keep uploading builds till one works

**Comment by MarshallOfSound** [comment] 2015-12-01 09:05
Also @The2rB the language is cached by google and the embedded browser (to lower internet usage) actually performs its own stronger caching so the language won't change till you log in and log out.  But as said before, the language shouldn't affect it, it will be some region specific code I can't see

**Comment by The2rB** [comment] 2015-12-01 09:19
Just found it strange that I were unable to change language.
But I can confirm that after signing out and in again - the language have changed and the Desktop Setting is still missing.

**Comment by MarshallOfSound** [comment] 2015-12-01 10:54
OK guys,
Same as before, here is another devtools enabled build, this one should work but only because I disabled a few things (not noticeable).  Good luck :D

https://mega.nz/#!nBlUQbrT!gjfIL20EEWnRyYHHixDaHkcvJqcr8VdZ7507WpR1r6s

**Comment by The2rB** [comment] 2015-12-01 11:38
The desktop settings are now in place:
![tb-151201-1237-55001](https://cloud.githubusercontent.com/assets/5319973/11499713/6388c204-9828-11e5-9c4b-e1386f7e0d80.png)

The new console messages:
![tb-151201-1238-24001](https://cloud.githubusercontent.com/assets/5319973/11499715/6be88b96-9828-11e5-9bef-5ee5e42954cd.png)

**Comment by rprouse** [comment] 2015-12-01 19:43
The latest debug build works for me with those two lines commented out. I am seeing the same errors as @The2rB.

FYI, I am using the Canadian Play Store.

I managed to get a breakpoint set on line 247 of gu-util.js, the outerHTML for `divs[2].querySelectorAll('div')[1]` is just `<div class="gb_kb">Rob Prouse</div>`, there is no link, so I think it is safe to do something like,

```js
var userLink = divs[2].querySelectorAll('div')[1].querySelector('a');
if (userLink !== undefined) userLink[0].setAttribute(...);
```

Forgive my JavaScript, I never use it :smile:

**Comment by MarshallOfSound** [comment] 2015-12-01 23:38
@rprouse All the errors you guys are seeing are pretty standard, its trying to find a chrome extension that isn't there :cactus: 

That JS is more or less what I am going to do, I kinda want to figure out why an element is there for me and not for you though...  Could your google account be different in any way?

But regardless as to what caused it, I'll upload another debug build when I get home today and hopefully I'll be able to push a fix into the repo.

**Comment by The2rB** [comment] 2015-12-02 07:23
Ahh.. Good question.
**I'm using an Google Apps account.**
Could that be it?

**Comment by MarshallOfSound** [comment] 2015-12-02 08:35
@The2rB That would actually be great, I'll DM you now

**Closed** 2015-12-02 09:37 UTC
Labels: breaking bug
