### ISSUE TITLE
App freezes when skipping multiple tracks

### ISSUE THREAD

**Issue by clank201** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2308] opened 2017-03-10 21:03 UTC
**OS:** Windows 10 Home Build 14393.693

**Issue Descriptions:** The app completely freezes when skipping multiple tracks too fast, requiring to close the process through taskmgr. (Maybe related to issue #1776)

**Steps to Reproduce:** Play any song from a radio/playlist/whatever, then spam the skip song button.

**Comment by erasedff** [comment] 2017-03-11 14:58
I have ~1700 songs in the library, spammed the skip button for about 30 seconds with shuffle on. 
Interface does lock up for about 15 seconds but then everything goes back to normal. It's not a complete freeze, I can still move the window around while everything else is frozen.
Though I have to say, interface of GPMDP was (and still is) always noticeably slower for me compared to the GMusic in Chrome - scrolling, animation etc.
Win 10 Pro x64 with all the latest updates.

**Comment by hassanila97** [comment] 2017-03-13 12:35
Because  Google-Play-Music-Desktop-Player-UNOFFICIAL  doesn't have any caching features....

**Comment by MarshallOfSound** [comment] 2017-03-13 12:45
> then spam the skip song button.

Although I can reproduce this after about 40-50 spam clicks I can't see any logs for what appears to be the renderer freezing.  No crash, no warnings, nothing 😢 

As far as I can tell this isn't too big of an issue because I'm not sure why anyone would ever have to spam the button that many times.

> lock up for about 10-15 seconds but then everything goes back to normal.

At least it comes back for you 👍 

> Because Google-Play-Music-Desktop-Player-UNOFFICIAL doesn't have any caching features....

I don't know what you mean by this 😕 

Closing as `wontfix` due to the random and unloggable nature, will track with Chromium versions to see if it  is fixed in later versions 👍

**Closed by MarshallOfSound** 2017-03-13 12:45 UTC
