### ISSUE TITLE
OSX:  Store button does not prompt browser (Firefox/Chrome/Safari)

### ISSUE THREAD

**Issue by stejmurphy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#334] opened 2016-03-07 13:49 UTC
Left Nav,
Sign in as a 'free' account, not premium (shop button not available on premium) 
Select shop button.
Should open the system's default browser, 

Nothing is prompted.

OS X 10.11.3

**Comment by MarshallOfSound** [comment] 2016-03-09 01:46
You you show me a screenshot, I have all access so can't see what button you are on about

**Comment by MarshallOfSound** [comment] 2016-03-09 14:08
@MightyPork Do you have this button (sorry for the ping but you seem active enough) or @chrismou?

**Comment by chrismou** [comment] 2016-03-09 14:13
I'm all access too.  Just tried to log in with another email address, and it wants a credit card to "confirm your country of residence"  :-/

**Comment by chrismou** [comment] 2016-03-09 14:16
OK did it anyway.  Confirmed - click the Shop button and nothing happens.

Is there any info I can give you to fix this easily?  Class name of the button, etc?

**Comment by MarshallOfSound** [comment] 2016-03-09 14:18
Any info about what the button actually does / is supposed to do.

From the sounds of it, it is trying to call `window.open` or maybe its a link with a target of `_blank`.  Whatever it is I need to know so I can fake the situation and then come up with a fix involving `shell.openExternal` :+1:

**Comment by chrismou** [comment] 2016-03-09 14:26
This is the entire block:

```
<a id="shop-nav" data-type="shop" class="nav-item-container tooltip" href="">
  <iron-icon icon="shop" alt="" class="x-scope iron-icon-1">
    <svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" class="style-scope iron-icon" style="pointer-events: none; display: block; width: 100%; height: 100%;">
      <g class="style-scope iron-icon">
        <path d="M16 6V4c0-1.11-.89-2-2-2h-4c-1.11 0-2 .89-2 2v2H2v13c0 1.11.89 2 2 2h16c1.11 0 2-.89 2-2V6h-6zm-6-2h4v2h-4V4zM9 18V9l7.5 4L9 18z" class="style-scope iron-icon"></path>
      </g>
    </svg>
  </iron-icon>
  Shop
  <iron-icon icon="open-in-new" class="x-scope iron-icon-1">
    <svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" class="style-scope iron-icon" style="pointer-events: none; display: block; width: 100%; height: 100%;">
      <g class="style-scope iron-icon">
        <path d="M19 19H5V5h7V3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z" class="style-scope iron-icon"></path>        
      </g>
    </svg>
  </iron-icon>
</a>
```

Opens [https://play.google.com/store/music?feature=music_general](https://play.google.com/store/music?feature=music_general) in a new window

**Comment by MarshallOfSound** [comment] 2016-03-09 14:52
@chrismou I can't test this so can you try adding this code to line 46 of `GPMInject/interface/customUI.js`

```js
const shopButton = document.querySelector('[data-type="shop"]');
  if (shopButton) {
    shopButton.addEventListener('click', (e) => {
      remote.shell.openExternal('https://play.google.com/store/music?feature=music_general');
      e.preventDefault();
      return false;
    });
  }
```

you'll also need an `import { remote } from 'electron';` at the top

**Comment by chrismou** [comment] 2016-03-09 15:07
Since I pulled from master and rebuild, it's throwing this error in a popup, so can't start the player

```
App threw an error when running { [Error: ENOENT: no such file or directory, rename '/Users/xxx/Library/Preferences/GPMDP_STORE/.settings.json' -> '/Users/xxx/Library/Application Support/Google Play Music Desktop Player/json_store/.settings.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'rename',
  path: '/Users/xxx/Library/Preferences/GPMDP_STORE/.settings.json',
  dest: '/Users/xxx/Library/Application Support/Google Play Music Desktop Player/json_store/.settings.json' }
```

**Comment by MarshallOfSound** [comment] 2016-03-09 15:13
Lol wut... Hand on. Let me start my mac up

**Comment by chrismou** [comment] 2016-03-09 15:17
I've reverted back a couple of commits, I'll test this thing you sent over while you're looking into that :wink:

**Comment by MarshallOfSound** [comment] 2016-03-09 15:21
OK, that bug was fixed.  My bad, I was trying to move an old file into a new folder without creating the folder first :+1: 

#rookiemistake

**Comment by chrismou** [comment] 2016-03-09 15:23
OK, that fix didn't work - but I've noticed that there's no Desktop Settings menu option either, which I think you're setting straight after.  So whatever it's waiting for isn't being triggered on the free account version?

**Comment by chrismou** [comment] 2016-03-09 15:27
Before you dive into that, it may have been the commit I was on. Loads more stuff was broken. Have pulled from upstream and it all works again now.  I'll try out that fix again!

**Comment by chrismou** [comment] 2016-03-09 15:32
@MarshallOfSound Woohoo, it works.  Got there in the end :+1:

**Comment by MarshallOfSound** [comment] 2016-03-09 15:34
Sweet as, can you PR that fix in and I'll just merge it.  Just want to be sure that there wasn't a code change caused in translation :+1: 

Best way to make sure it works is to PR the working version :smile: :laughing:

**Comment by chrismou** [comment] 2016-03-09 15:39
Done :smiley: 

#408

**Comment by MarshallOfSound** [comment] 2016-03-09 15:39
And merged

**Comment by MarshallOfSound** [comment] 2016-03-09 15:39
And closed

**Closed by MarshallOfSound** 2016-03-09 15:39 UTC
Labels: bug, help wanted

**Comment by MightyPork** [comment] 2016-03-09 16:55
@MarshallOfSound sorry I wasn't at home, but got all access too so I wouldn't have been off any help  anyway
