### ISSUE TITLE
Crash with 4.6.* version on Mint 19.1

### ISSUE THREAD

**Issue by lguerard** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3463] opened 2019-01-10 09:41 UTC
Hi there,

**OS:** Linux Mint 19.1

**GPMDP Version:** Both 4.6.0 and 4.6.1

**Issue Descriptions:** I tried to install the latest versions of GPMDP but it makes my whole desktop crash and I have to restart Cinnamon. Is it a problem of Electron or does it come from something else ? EDIT : Also tried through Flatpak but same problems.

**Steps to Reproduce:** I tried installing it twice each and crashes everytime. Snap package is still 4.4.1 and repo is also 4.4 or 4.5. Both works though.

**Comment by elsuzio** [comment] 2019-01-17 11:36
Works here on 19.1.

**Comment by lguerard** [comment] 2019-01-17 12:01
Which version of GPMDP ?

Is it as fast as the other ones ?

**Comment by zerkz** [comment] 2019-02-15 17:41
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3391 

@lguerard if you get the latest from master it will work. See the above thread on instructions.

**Comment by MarshallOfSound** [comment] 2019-04-23 02:49
Duplicate of #3391

**Closed by MarshallOfSound** 2019-04-23 02:49 UTC
