### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by kashleec** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#937] opened 2016-04-12 18:30 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.1.0
**Time:** Tue Apr 12 2016 13:30:34 GMT-0500 (Central Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\kcummings\AppData\Local\GPMDP_3\app-3.1.0\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:18:9.
    at BrowserWindow.callIntoRenderer (C:\Users\kcummings\AppData\Local\GPMDP_3\app-3.1.0\resources\atom.asar\browser\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-04-12 18:36
Closing this automatically reported issue as a duplicate of #847

**Closed by GPMDP-Magical-Unicorn** 2016-04-12 18:36 UTC
Labels: Automatic-Issue-Report
