### ISSUE TITLE
GPMD breaks sound when opening youtube on safari

### ISSUE THREAD

**Issue by ortegamediatasoft** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1711] opened 2016-09-30 22:09 UTC
macOS 10.12

Sound loops when opening safari.
I use chrome as main browser, so far so good no issues having many windows/accounts logged in.

Playing a playlist, when i did remember about the picture in picture of the new macOS, so i opened safari, and just when i opened it and navigated to youtube, the audio started to loop, like 1 sec or less, and stopped until i closed GPMD window, i repeated the process to check if it was related and it did the same thing

**Comment by MarshallOfSound** [comment] 2016-10-01 02:23
**Initial Reaction:**
![wat8](https://cloud.githubusercontent.com/assets/6634592/19011162/9cf0a0cc-87d1-11e6-8717-f5779dc56ad1.jpg)

But for reals, I'm just going to mark this as unconfirmed as I don't have a mac to test on at the moment.  We'll see if anyone else can reproduce

**Comment by arkon** [comment] 2016-10-08 01:04
I tried reproducing this on my rMBP (with macOS 10.12) but it didn't happen.

**Comment by MarshallOfSound** [comment] 2016-10-08 01:57
Thanks @arkon 

I'll wait for one more person to try this out before retagging

**Comment by ortegamediatasoft** [comment] 2016-10-08 02:12
Ok, i am going to test on Mac mini today

**Comment by MarshallOfSound** [comment] 2016-10-13 00:24
I found another mac to test this on and couldn't reproduce.  Closing this out as a "wut" issue 😆

**Closed by MarshallOfSound** 2016-10-13 00:24 UTC
Labels: help wanted, Unconfirmed
