### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by outraider** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#979] opened 2016-04-22 10:50 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.2.1
**Time:** Fri Apr 22 2016 13:48:34 GMT 0300 (FLE Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> ((...)\GPMDP_3\app-3.2.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:27:9.
    at BrowserWindow.callIntoRenderer ((...)\GPMDP_3\app-3.2.1\resources\electron.asar\browser\rpc-server.js:198:19)
    at emitTwo (events.js:105:20)
    at BrowserWindow.emit (events.js:185:7)
```
This issue was created automatically inside the `uncaughtException` handler

Did not cause crash thou

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-04-22 10:50
Closing this automatically reported issue as a duplicate of #971

**Closed by GPMDP-Magical-Unicorn** 2016-04-22 10:50 UTC
Labels: Automatic-Issue-Report
