### ISSUE TITLE
I can not connect to google play

### ISSUE THREAD

**Issue by cdyax** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3686] opened 2019-11-25 23:46 UTC
I can connect perfectly with the version for youtube but not for google play, it gets to say that songs load and stay there.
I'm in Spain.
version 4.6.1
Google the web of play I have no problem with my email and password
If anyone has any idea how can I fix it agradeceria.

**Comment by forrestak** [comment] 2019-11-26 02:50
I am having the same issue. US based, version 4.6.1. I know you're busy so no rush, just adding my voice to this since it applies

**Comment by jostrander** [comment] 2019-11-26 03:13
Duplicate of #3660

**Closed by jostrander** 2019-11-26 03:13 UTC
