### ISSUE TITLE
Back button visibility

### ISSUE THREAD

**Issue by mindblank** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2722] opened 2017-08-23 12:20 UTC
**OS:** Mac OS

**Issue Descriptions:** The back button using Dark theme is barely visible, is there an option to make it white in colour so it is more visible?

**Steps to Reproduce:**

**Comment by MarshallOfSound** [comment] 2017-08-23 12:31
Duplicate of #2673

**Closed by MarshallOfSound** 2017-08-23 12:31 UTC
