### ISSUE TITLE
Desktop App not loading

### ISSUE THREAD

**Issue by tbean23** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3689] opened 2019-11-27 14:54 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Mac OS Catalina - V 10.15.1
**GPMDP Version:**
Version 4.6.1 (4.6.1)
**Issue Descriptions:**
Desktop app never loads music library - Re-installed twice. Works on the web app.
**Steps to Reproduce:**

**Comment by jostrander** [comment] 2019-11-27 14:57
Duplicate of #3660

**Closed by jostrander** 2019-11-27 14:57 UTC
