### ISSUE TITLE
Stops at 'Loading Music Collection' screen

### ISSUE THREAD

**Issue by iranadavi** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3714] opened 2019-12-10 00:39 UTC
I performed the normal installation and logged in to play music. After Authenticate gets stuck on this screen.

![image](https://user-images.githubusercontent.com/14761695/70484597-1c145800-1acb-11ea-8cbe-7117872da960.png)

But when I switch to Youtube Music it works normal.

![image](https://user-images.githubusercontent.com/14761695/70484623-35b59f80-1acb-11ea-90e1-a8485a3629d8.png)

I tried to reinstall and checked if the firewall was blocking, but it is correct.

**OS:** windows 10 pro (version 1909, build 18363.476)

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Stops at 'Loading Music Collection' screen

**Steps to Reproduce:** 

1) Perform the installation.
2) Sign in to Google Play.
3) After authentication is displayed 'Loading Music Collection'

**Comment by jostrander** [comment] 2019-12-10 00:44
Duplicate of #3660

**Closed** 2019-12-10 00:43 UTC
