### ISSUE TITLE
Application crashes on load

### ISSUE THREAD

**Issue by stafio** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3453] opened 2018-12-28 01:30 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
Kubuntu 18.10

**GPMDP Version:**
4.6.1

**Issue Descriptions:**
When clicking the Google Play Music Desktop Player menu shortcut, it seems as though nothing happens. The application does not start. Running google-play-music-desktop-player results in:
`Segmentation fault (core dumped)`

**Steps to Reproduce:**
Attempt to start GPMDP either from a menu shortcut, or from the terminal

**Comment by bsberry** [comment] 2018-12-28 14:41
I saw the same behavior on Ubuntu 18.10 with Slack and GPMDP. The [fix listed here](http://ubuntuhandbook.org/index.php/2018/11/slack-app-not-launching-ubuntu-18-10/) for Slack also works for GPMDP. I ended up using vscode as the donor of a working libnode.so . 

It's only a workaround until @MarshallOfSound can update the libnode.so version, but it does seem to work!

**Comment by kkavchakHT** [comment] 2018-12-28 15:38
Thanks @bsberry I can confirm that replacing the version of libnode.so worked for me as well. I had another version from Insomnia on my machine, which crashes in different ways. Using the version from Atom beta as shown in the Slack thread you linked to worked for me.

**Comment by jostrander** [comment] 2018-12-30 20:31
This is a duplicate of the closed issue #3410. Just waiting for the release to be built and published, but the artifacts on CI should reflect this change.

**Closed by jostrander** 2018-12-30 20:31 UTC

**Comment by camdenorrb** [comment] 2019-01-17 20:09
I'm also experiencing this :C
