### ISSUE TITLE
App is stuck when start playing song "The Man Who Sold The World (2015 Remastered Version)"

### ISSUE THREAD

**Issue by XSmile2008** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3487] opened 2019-02-11 08:25 UTC
**OS:**
Solus 3.9999
**GPMDP Version:**
4.6.1
**Issue Descriptions:**
App is stuck when start playing song "The Man Who Sold The World (2015 Remastered Version)". Music was continued to play, so only UI was stuck. Only this song has caused this issue. Also there is 100% usage of one of CPU threads. Reproduced on both of my computers.
https://i.imgur.com/sEiWi1X.png
https://i.imgur.com/MJvKMmP.png
https://i.imgur.com/2T2RP7F.png
**Steps to Reproduce:**
- Open app
- Start playing song "The Man Who Sold The World (2015 Remastered Version)"

**Comment by jmaleonard** [comment] 2019-02-11 08:47
I am getting the same issue but on multiple tracks. Same issue on my Mac and Windows machines

**Comment by GhostInq** [comment] 2019-02-11 09:01
Today I also started the application to hang. When playing with youtube, the interface freezes up when opened, but the music continues to play. In this case, only the multimedia buttons on the keyboard work. But the interface itself is constantly waiting for a response.

**Comment by sigma67** [comment] 2019-02-11 09:20
My app freezes as well after playing any song. Music continues to play, goes to next song, then also freezes after a few seconds into the song. CPU usage at ~20-30% while frozen (i7-8550U)

**Comment by kode54** [comment] 2019-02-11 09:56
Confirmed to randomly occur within a moment of starting another song. CPU usage is spinning 100% of a core.

**Comment by Tune389** [comment] 2019-02-11 10:00
Same here, after 10-20 Minutes, on windows 10, which song doesn't matter. When I reopen Player from background after a while it crashes and no more reaction:
![grafik](https://user-images.githubusercontent.com/4512259/52556133-f86d7c00-2deb-11e9-9ca6-5b1f6effb65d.png)
![grafik](https://user-images.githubusercontent.com/4512259/52556139-002d2080-2dec-11e9-8a27-8ab0d903deff.png)

**Comment by alexfonseka** [comment] 2019-02-11 10:51
This issue is caused by a lyrics fetching API and is being worked on. You need to disable lyricsfreak from the app to stop it from crashing so use the fix @Tune389 mentioned for the time being.

**Comment by jostrander** [comment] 2019-02-11 12:47
duplicate of pinned issue #3483

**Closed by jostrander** 2019-02-11 12:47 UTC

**Comment by gholtslander-va** [comment] 2019-02-11 14:35
Sick song though.
