### ISSUE TITLE
Entire player freezes on listening to one specific song

### ISSUE THREAD

**Issue by Gyyyn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3494] opened 2019-02-13 11:49 UTC
**OS:** Windows 10

**GPMDP Version:** 4.6.1

**Issue Descriptions:** Entire player freezes on listening to one specific song. Probably something to do with the weird periods on the song name.

**Steps to Reproduce:** Listen to the specific song: Virtual Self - a.i.ngel (Become God)

**Comment by jostrander** [comment] 2019-02-13 12:42
Duplicate of #3483

**Closed by jostrander** 2019-02-13 12:42 UTC
