### ISSUE TITLE
This browser or app may not be secure. 

### ISSUE THREAD

**Issue by That-Marketing-Guy** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3737] opened 2019-12-18 03:30 UTC
OS: Windows 10
GPMDP Version: 4.6.1
Issue Descriptions:  See Screen snip
![image](https://user-images.githubusercontent.com/14838661/71052926-dbe05580-211a-11ea-8e53-05dfb722d373.png)
The screen is displayed after completing the login process. I can still access menu items from the icon in the taskbar (See screen snip)
![image](https://user-images.githubusercontent.com/14838661/71053209-cb7caa80-211b-11ea-8e3e-ba3be33bda5d.png)

I've tried uninstalling & reinstalling with and without anti-virus active. 

This issue is occuring on my personal laptop and the laptop I use at work.

I was not able to create a log file.

**Comment by jostrander** [comment] 2019-12-18 03:30
Please follow the issue template. Duplicate of #3545.

**Closed by jostrander** 2019-12-18 03:30 UTC
