### ISSUE TITLE
Feature Request: Choose what text is displayed on discord

### ISSUE THREAD

**Issue by Onyxx666** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3000] opened 2018-02-10 23:00 UTC
Hey!,

So thanks for adding this support as I saw Spotify and I and was jelly to see it come for GPMDP.

I was wondering if there was a way to edit what is shown in the text? I feel like showing the info like:
song 
artist
album 

Also any way you could show album artwork instead of the GPMDP logo by chance? 

Thanks ^.^!

**Comment by chinmaya1011** [comment] 2018-02-13 11:11
Discord devs have to allow the developers of the app to do special things like the album art feature that Spotify has

**Comment by ruscur** [comment] 2018-03-06 04:40
duplicate of #2975

**Comment by MarshallOfSound** [comment] 2018-04-26 04:12
#2975

**Closed by MarshallOfSound** 2018-04-26 04:12 UTC
