### ISSUE TITLE
Uncaught Exception: dns service error: unknown

### ISSUE THREAD

**Issue by frebib** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1105] opened 2016-05-22 21:29 UTC
An uncaught exception was reported.  
#### Info:
**OS:** linux
**Arch:** x64
**GPMDP Version:** 3.2.4
**Time:** Sun May 22 2016 22:28:44 GMT 0100 (BST)

#### Error:
*dns service error: unknown*
```js
Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/share/google-play-music-desktop-player/resources/app/node_modules/mdns/lib/advertisement.js:64:10)
    at Server.<anonymous> (/usr/share/google-play-music-desktop-player/resources/app/build/main/features/core/websocketAPI.js:56:25)
    at Server.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1279:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-05-22 21:31
Closing this automatically reported issue as a duplicate of #1048

**Closed by GPMDP-Magical-Unicorn** 2016-05-22 21:31 UTC
Labels: Automatic-Issue-Report
