### ISSUE TITLE
Progress not updated on taskbar icon

### ISSUE THREAD

**Issue by goszczynskip** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2659] opened 2017-07-24 13:34 UTC
**OS:**
Windows 10 ver. 1703 build 15063.483
GPMDP version: 4.4.0

**Issue Descriptions:**
Progress on taskbar icon is not updated when app is minimalized.

**Steps to Reproduce:**
Minimalize application while it is playing music.

**Comment by jostrander** [comment] 2017-07-24 13:57
Duplicate of #2630. Please track it there.

**Comment by MarshallOfSound** [comment] 2017-07-24 13:57
Merging into #2630

**Comment by MarshallOfSound** [comment] 2017-07-24 13:58
Dayum, beat me by milliseconds @jostrander 😆

**Closed by MarshallOfSound** 2017-07-24 13:58 UTC
