### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by rickwastaken** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#863] opened 2016-03-31 21:43 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Thu Mar 31 2016 14:42:57 GMT-0700 (Pacific Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\rick\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\rick\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-31 21:44
Closing this automatically reported issue as a duplicate of #470

**Closed by GPMDP-Magical-Unicorn** 2016-03-31 21:44 UTC
Labels: Automatic-Issue-Report, duplicate

**Comment by MarshallOfSound** [comment] 2016-03-31 21:46
You are not up to date.  Please accept the update notification in the player and this error will be fixed

**Comment by MarshallOfSound** [comment] 2016-04-04 17:00
@rickwastaken Could you please also upload the file found at %LOCALAPPDATA%\GPMDP_3\SquirrelSetup.log on your computer. I am trying to determine why some users aren't updating

**Comment by rickwastaken** [comment] 2016-04-04 19:21
Hello,

I've attached the document you requested.  Is there a manual way to update
the app? Or should I just uninstall and reinstall a newer version?

Thanks,
Rick

**Comment by jostrander** [comment] 2016-04-04 19:24
I don't think email attachments work with Github, could you post it to https://gist.github.com?

**Comment by rickwastaken** [comment] 2016-04-04 22:54
Here's a link to the log file:
https://gist.github.com/rickwastaken/c659c5a9fe75ecb3db274222bf6c288c

**Comment by MarshallOfSound** [comment] 2016-04-05 00:30
@rickwastaken You can manually update the app by simply running the `3.1.0` installer (you can download it from the website).

Can you try accessing http://update.googleplaymusicdesktopplayer.com/api/versions and tell me what you get.

**Comment by MarshallOfSound** [comment] 2016-04-05 00:35
Also @rickwastaken do you use a proxy of any kind or a VPN?
