### ISSUE TITLE
Uncaught Exception: The request timed out.: (null)

### ISSUE THREAD

**Issue by eboye** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#770] opened 2016-03-25 16:00 UTC
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Fri Mar 25 2016 17:00:29 GMT 0100 (CET)

#### Error:
*The request timed out.: (null)*
```js
Error: The request timed out.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-25 16:10
Closing this automatically reported issue as a duplicate of #235

**Closed by GPMDP-Magical-Unicorn** 2016-03-25 16:10 UTC
Labels: Automatic-Issue-Report, duplicate
