### ISSUE TITLE
Allow changing of install path on Win32 (currently breaks Roaming Profiles)

### ISSUE THREAD

**Issue by alexthefifth** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3517] opened 2019-03-07 19:25 UTC
**OS:** Windows 7 64bit

**GPMDP Version:** 4.6.1

**Issue Descriptions:** 

GPMDP on Windows currently installs to the default Electron path, %localappdata%, which ends up being this for most people:
C:\Users\<Username>\AppData\Roaming

This becomes a big problem in corporate environments that use Roaming Profiles, since GPMDP stores their Cache files in this location too, which can be hundreds of megabytes, even gigabytes in size. In a corporate environment, every time a user logs off/signs on to a new device this folder synchronized by Windows via Active Directory (and often periodically in the background at set intervals). Thus the impact is:
- lots of storage is needlessly consumed on the AD server for the GPMDP Cache
- lots of bandwidth is consumed through the network constantly synchronizing this Cache as it changes often
- long log-in/log-off wait times for users while this synchronization is performed with AD, especially when they are working remote over low-bandwidth connections

Large roaming profiles cause a lot of headaches for sysadmins and they often restrict the size of the roaming profiles for this reason, which wreaks havoc on the user's end, with fun error messages like these:
![](https://cdn-wlvacuk.terminalfour.net/its/media/departments/it-services/images/selfhelp/storage-and-profiles/roamingprofile1.png)

There's really no good reason to keep GPMDP Cache in a roaming folder. Cache should be stored in the %appdata% folder, which does not roam/get synchronized. For most people it would be:
C:\Users\<Username>\AppData\Local

If it's not possible to keep just the cache in \Local, why not just keep the entire app in \Local?

Yes, the **default** for Electron is %localappdata%, but they admitted **this was the wrong decision**, and developers can easily **overwrite the default** using app.SetPath (as per https://github.com/electron/electron/issues/1404#issuecomment-212756838)

I understand this may be a difficult change/migration for existing installations, but why not at least give them the option (and a FAQ entry)? Ideally during installation/first run. Bugs of this nature typically go through a deprecation process, where it starts out as an opt-in feature, then eventually becomes an opt-out feature, with maybe checking on start-up for existing installations and taking an educated guess.

Relevant: "Why are there directories called Local, LocalLow, and Roaming under \Users\<username>\AppData" https://superuser.com/questions/21458/why-are-there-directories-called-local-locallow-and-roaming-under-users-user

**Comment by MarshallOfSound** [comment] 2019-03-07 21:05
@alexthefifth You can override the app data directory yourself in the Squirrel trampoline that we use to launch the app.  Edit the shortcut on your desktop / in your taskbar and add the `--app-data-dir` CLI flag.

I'm going to close this as a duplicate of #2493 (which I can see you've already found).  If someone wants to take a shot at implementing this in a backwards compatible-with-migration way then I'd review a PR.  But this is not something that we can deal with here.

**Closed by MarshallOfSound** 2019-03-07 21:05 UTC
