### ISSUE TITLE
GPMDM not loading in Mac OS Catalina (10.15)

### ISSUE THREAD

**Issue by joseeantonior** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3676] opened 2019-11-14 14:30 UTC
**OS:** MacOS Catalina (10.15)

**GPMDP Version:** 4.6.1

**Issue Descriptions:** GPMDP is not loading any pages. I've tried opening GPM in Chrome without issues. Within the debug logs, the only error I can see is the following: ```{"level":"error","message":"################### !! Update server down !! ##################","timestamp":"2019-11-05T21:14:36.410Z"}```

Screenshot of the error below (it gets stuck there, without progress)

<img width="1506" alt="Screen Shot 2019-11-14 at 9 29 42 AM" src="https://user-images.githubusercontent.com/6580208/68865769-5a337d00-06c1-11ea-9d9e-302064485703.png">

This suddenly started happening without any prior issues. It was working fine yesterday.

**Steps to Reproduce:**
1.- Open GPMDP
2.- Screen will show

**Comment by qbunt** [comment] 2019-11-14 18:43
seeing the same behavior on 10.15.1

**Comment by LSouthwell** [comment] 2019-11-14 22:42
I am seeing this in Windows 10 as well.

**Comment by jostrander** [comment] 2019-11-14 22:43
Duplicate of #3660

**Closed by jostrander** 2019-11-14 22:43 UTC
