### ISSUE TITLE
App not working since last update (OS X Yosemite)

### ISSUE THREAD

**Issue by gklarenberg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2679] opened 2017-07-30 19:31 UTC
Since the last update, the app is not working anymore, gets stuck on "Loading Music Library". Have tried re-installing, didn't help. Google Play through Chrome works fine.
I am running OS X Yosemite, 10.10.5
Any ideas on what the issue could be? Player was working fine before the update.

**Comment by Daxtattack** [comment] 2017-08-01 15:04
Thank you for the great app. 
Since recent update it has not been working.
Windows 7.
Upon opening the background is white... it appears that google play music is not loading into app.

**Comment by MarshallOfSound** [comment] 2017-08-03 00:33
These issues are normally caused by a/b testing, the "since recent update" is more than likely to just be a coincidence.  Are you still experiencing this @gklarenberg ?

**Comment by jostrander** [comment] 2017-08-07 13:21
Closing due to staleness.

**Closed by jostrander** 2017-08-07 13:21 UTC
