### ISSUE TITLE
Google refuses to log me in; app "may not be secure"

### ISSUE THREAD

**Issue by Teslahaha** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3742] opened 2019-12-20 01:40 UTC
Even after putting in the right password and everything, Google will not log me in to use Google Play, rendering the entire app useless.

**Comment by richardkentgates** [comment] 2019-12-20 02:00
Same. Pretty sure this is a result of tighter security in chrome and just got overlooked.

Operating System: KDE neon 5.17
KDE Plasma Version: 5.17.4
KDE Frameworks Version: 5.65.0
Qt Version: 5.13.2

**Comment by GodTamIt** [comment] 2019-12-20 03:25
+1, I'm also experiencing this issue on Windows 10, version 1909.

**Comment by terroreek** [comment] 2019-12-20 04:25
Same problem here as well.
OS: Siduction (Debian Sid)
gnome 3.34.2
running 4.6.1 after logging on successfully and passing my 2fa I get the following message.  

![googleplaymusicdesktopplayer](https://user-images.githubusercontent.com/7308768/71230226-cb64e200-22b6-11ea-8fce-25ed22d509dc.png)

**Comment by terroreek** [comment] 2019-12-20 04:32
I believe this is a duplicate of this issue;
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3545

**Comment by Teslahaha** [comment] 2019-12-20 04:34
I guess, but isn't it still relevant?

**Comment by terroreek** [comment] 2019-12-20 04:53
that issue has links to installers that people are reporting fixes their issue.  I was able to use the use the installer from here;

https://3751-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_amd64.deb

and it fixed the problem for me.  I am running a debian based distro so it should fix it for richardkentgates running KDE neon.  Not sure what OS you are running but a newer build may fix the issue for you.

**Closed** 2019-12-20 18:43 UTC

**Comment by Teslahaha** [comment] 2019-12-25 08:00
> that issue has links to installers that people are reporting fixes their issue. I was able to use the use the installer from here;
> 
> https://3751-40008106-gh.circle-artifacts.com/0/home/circleci/project/dist/installers/debian/google-play-music-desktop-player_4.6.1_amd64.deb
> 
> and it fixed the problem for me. I am running a debian based distro so it should fix it for richardkentgates running KDE neon. Not sure what OS you are running but a newer build may fix the issue for you.

Dumb question, but what do I do with a file? Do I just put it into the GPMDP's directory?
