### ISSUE TITLE
The program is often hangs when trying to choose the artist and needed to be reload

### ISSUE THREAD

**Issue by Tranquillit** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3515] opened 2019-03-06 08:38 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**

**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by Enigma0** [comment] 2019-03-07 16:24
Having the same issue 10-15+ times a day. Frequently when thumbs downing a song, it hangs completely and needs to be killed and restarted.

(Using YouTube Music)

**Comment by jostrander** [comment] 2019-03-07 17:48
This sounds a lot like #3483.

**Comment by MarshallOfSound** [comment] 2019-04-23 02:35
Duplicate of #3483

**Closed by MarshallOfSound** 2019-04-23 02:35 UTC
