### ISSUE TITLE
[Linux] No image for the taskbar icon

### ISSUE THREAD

**Issue by nanohard** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1057] opened 2016-05-09 14:18 UTC
OS: Linux - Debian 8, KDE
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

Issue Descriptions: The taskbar icon is just a white square.

Steps to Reproduce: Start the program.

Snapshot (the blank white square is the Google Play program):
![google_play_taskbar_icon](https://cloud.githubusercontent.com/assets/10169206/15119597/9e59b85e-15df-11e6-9969-504f4a501907.png)

**Comment by berryelectronics** [comment] 2016-05-09 15:57
Can you maybe post a picture of it?

**Comment by MarshallOfSound** [comment] 2016-05-09 16:00
This sounds like an issue with Electron, can you post a link to an ISO of your exact distro

**Comment by nanohard** [comment] 2016-05-09 16:19
Here is a link to the install ISO of my distro. I may not have used this one (8.4), it may have been any from 8.0 - 8.4 since Debian has rolling releases.

http://cdimage.debian.org/debian-cd/8.4.0/amd64/iso-dvd/debian-8.4.0-amd64-DVD-1.iso

**Comment by jostrander** [comment] 2016-05-10 00:51
If were using a tray icon that is hi-res this could be only showing the top left corner similar to how the windows sound menu was screwing up. We can test this by switching out for a low res icon and seeing if that fixes it.

**Comment by berryelectronics** [comment] 2016-05-10 16:15
Maybe its centering it?

**Comment by andreykapanda** [comment] 2016-05-11 13:46
Similar problem. Kubuntu 16.04. kde 5.18.0

**Comment by rgavs** [comment] 2016-05-19 17:41
I'm just going to say that the tray is functioning properly on my Linux machine(s), both running Arch. The tray being `tint2`; image: [here](https://drive.google.com/file/d/0B0dYf6aWRkwVSkViblVaWHgyQ1k/edit)

**Comment by berryelectronics** [comment] 2016-05-19 17:52
Soo its maybe a KDE thing?

**Comment by sylmarien** [comment] 2016-05-29 22:06
Hi, somewhat similar problem on a clean install of Ubuntu 16.04 (only thing installed before this was Google Chrome).

There is an icon but it isn't the right one (it is the last icon in the dock on the left, the _google_ one) :
![screenshot from 2016-05-29 18-05-44](https://cloud.githubusercontent.com/assets/8776275/15636295/003ee812-25c8-11e6-9437-d9eebf4bb332.png)


It works fine on my other computers (2 other Ubuntu 16.04 and 2 Windows 10 ones) and the only difference that comes to mind is the way I arrived to this specific version (3.2.4) is that I installed it directly with this one while I updated from previous versions for the other computers (may not be related though).

**Comment by MarshallOfSound** [comment] 2016-05-30 02:47
@sylmarien Different issue, that's actually Ubuntu's fault.  It thinks it is being clever but it isn't :laughing:

**Comment by justinwilliamsx** [comment] 2016-06-03 18:47
Hi I'm having the same problem in the latest Manjaro release. I created a github account to report this. Here's the info you requested from OP.

`DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=16.06-rc2
DISTRIB_CODENAME=Daniella
DISTRIB_DESCRIPTION="Manjaro Linux"
Manjaro Linux
NAME="Manjaro Linux"
ID=manjaro
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="http://www.manjaro.org/"
SUPPORT_URL="http://www.manjaro.org/"
BUG_REPORT_URL="http://bugs.manjaro.org/"
`
http://sourceforge.net/projects/manjarolinux/files/release/16.06-rc2/kde/manjaro-kde-16.06-rc2-x86_64.iso

![screenshot_20160603_113314](https://cloud.githubusercontent.com/assets/19735762/15789379/ad98ba5e-2980-11e6-9b82-69625e67dcd6.png)

**Comment by nanohard** [comment] 2016-06-03 19:00
Okay, so this seems to only be affecting KDE users.

**Comment by jostrander** [comment] 2016-06-04 23:49
That's exactly the case @nanohard. @MarshallOfSound unfortunately the fix for this is to reduce the icon  dimensions. 24x24 seems to be the magic number, however we can probably use the `@Nx` syntax to implement larger logos where needed.

**Comment by MarshallOfSound** [comment] 2016-06-05 00:26
@Nx doesn't work on Linux and in high DPI Linux environments the icon needs to be larger.  To be honest, icon scaling is actually an issue with the OS as literally every other OS (including other Linux based ones) scales the icon correctly.

I mean, even windows scales it correctly :laughing: 

Is there official docs / reasoning behind the lack of icon scaling

**Comment by jostrander** [comment] 2016-06-05 00:32
Nothing official, just looking at other electron apps:

https://github.com/sindresorhus/caprine/issues/58

Nylas n1 uses the `icon@2x.png` as seen here:

https://github.com/nylas/N1/tree/master/internal_packages/system-tray/assets/linux

I'm currently looking in other electron apps at the moment to see how they handle linux DPI tray icons.

**Comment by jostrander** [comment] 2016-06-05 00:45
On second thought, KDE appears be the exception to the norm here. Can we do a check for KDE and give them a special icon?

**Comment by joergi77** [comment] 2016-06-30 09:08
I can't confirm the problem of @sylmarien on Ubuntu
latest install on Ubuntu 14.04 64 bit, showing both correct symbols
![gpdapp](https://cloud.githubusercontent.com/assets/1439809/16483020/c9701fa0-3eb2-11e6-9dec-11f26b17b641.png)

**Comment by sylmarien** [comment] 2016-06-30 14:19
@joergi77 : Yes, I couldn't reproduce it either (had to reinstall a few times my computer and this problem never showed up again). Let's consider my case closed for now.

**Comment by jostrander** [comment] 2016-06-30 22:28
These were two separate issues really, the white icon issue, and the wrong icon issue. The white icon issue can be solved by checking for kde and using the lowest res icon available (unless kde fixes it themselves). The other issue is sort of sporadic and has nothing to do with the white icon issue.

**Comment by MarshallOfSound** [comment] 2016-06-30 22:36
@jostrander Do you have any idea how we would identify KDE?

**Comment by jostrander** [comment] 2016-06-30 22:40
```GDMSESSION=kde-plasma``` 

As seen here, not sure it will be the same for Manjaro, one of theme will need to reply with their environment variables to confirm.

http://askubuntu.com/questions/72549/how-to-determine-which-window-manager-is-running

**Comment by 24mu13** [comment] 2016-07-01 11:33
+1
I tried to write a multi resolution PNG (using "convert" ImageMagick) but still does not work.
Overwriting /usr/share/pixmaps/google-play-music-desktop-player.png

So, the problem should be something different

Debian 8 + KDE

**Comment by MarshallOfSound** [comment] 2016-07-01 11:40
@24mu13 That's the wrong image file 😆 

The actual file should be in a `......../build/assets/img/main.png` style path

**Comment by 24mu13** [comment] 2016-07-01 11:56
@MarshallOfSound :+1: 
So I confirm the opposite: changing the png with a multi-resolution png works fine also in KDE !

See also: [http://www.imagemagick.org/Usage/thumbnails/#favicon](http://www.imagemagick.org/Usage/thumbnails/#favicon)

**Comment by MarshallOfSound** [comment] 2016-07-02 01:46
@24mu13 Can you please confirm that the fix I just pushed works on KDE 👍

**Comment by 24mu13** [comment] 2016-07-04 07:57
No, I'm sorry.
Is it the icon multi-res ?

![image](https://cloud.githubusercontent.com/assets/14576296/16554209/92c4323e-41cd-11e6-96c7-a6cee83229e3.png)

**Comment by MarshallOfSound** [comment] 2016-07-04 08:16
@24mu13 Yeah, it contains 16, 32, 128 and 256

**Comment by 24mu13** [comment] 2016-07-04 08:33
Ok, so most probably the issue is checking the environment.

```
> echo $XDG_CURRENT_DESKTOP
KDE
```
You can check for KDE only in the first 3 chars. In this way you are KDE 4/5 compliant...
S.

**Comment by MarshallOfSound** [comment] 2016-07-04 08:36
@24mu13 What is your `$GDMSESSION` env var

**Comment by 24mu13** [comment] 2016-07-04 08:39
empty :-o

**Closed** 2016-07-09 03:25 UTC
Labels: Linux, Unconfirmed
