### ISSUE TITLE
Crash every time you play a song.

### ISSUE THREAD

**Issue by deathspawn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3422] opened 2018-11-18 05:12 UTC
I am on Manjaro Linux and have gpmdp installed through AUR. I keep getting an error every time I play a song.

Trace/breakpoint trap (core dumped)

It also happens on another computer. It was working fine for a while.

**Comment by Circuitsoft** [comment] 2019-02-12 16:21
I've started seeing this lately, but I'm just getting a hard lockup, not a segfault. When I play a song, CPU usage goes to 100% and the UI stops responding, but the song continues to play.

**Comment by Yamthief** [comment] 2019-02-12 17:14
I'm having the same issue on a Mac. I've only noticed it happening very recently (over the past week or so).

**Comment by ayhoung** [comment] 2019-02-13 12:17
same issue here!

**Comment by jostrander** [comment] 2019-02-13 12:43
Duplicate of #3483

**Closed by jostrander** 2019-02-13 12:43 UTC
