### ISSUE TITLE
Windows keep losing focus

### ISSUE THREAD

**Issue by miaulalala** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2920] opened 2017-12-19 10:54 UTC
**OS**: Windows 10 Pro x64 Build 10.0.16299

**Issue Descriptions:** Other open windows are losing focus when the Player is running in the background. I might be in the middle of typing in Outlook, Chrome, etc... and the window just stops taking my input. Might be related to [this issue](https://github.com/electron/electron/pull/10783) in Electron. I did not have this issue before installing the player.

Unfortunately I can't really put down when it happens, it's not on changing a song. It might be when a window update happens, since it seems to be connected to when Win10 reloads some windows (Outlook, System windows, Skype).

**Steps to Reproduce:** Randomly happens and is thus not really reproducible. I have attached the [debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/1571320/debug_info.zip)

**Comment by MarshallOfSound** [comment] 2017-12-24 09:56
> Randomly happens and is thus not really reproducible

This means I can't really help, it doesn't even sound like you can pinpoint this as being GPMDP and not something else.

> https://github.com/electron/electron/pull/10783

This is a PR that we never merged, this can't be the cause of your issue.

**Closed by MarshallOfSound** 2017-12-24 09:56 UTC
