### ISSUE TITLE
Both 32bit and 64bit version of the installers use the same "Program Files (x86)" folder

### ISSUE THREAD

**Issue by TheHaf** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#107] opened 2015-12-24 08:56 UTC
I downloaded the latest 64 bit release and started to install it but was confused initially, as the installer suggested the installation path "C:\Program Files (x86)\GPMDP". Normally only installers for 32 bit applications pre-select the "Program Files (x86)" folder. So I thought maybe the installers were mixed up. I downloaded the other one as well and got the same suggestion. Then I decided to install the initial 64 bit download anyway and check the running application. It is indeed identified as a 64 bit process by my Windows 10 Pro system. So I see this only as a minor issue in the installer, but I thought you might want to know about it.

**Comment by MarshallOfSound** [comment] 2015-12-24 10:05
Duplicate of #75

**Closed by MarshallOfSound** 2015-12-24 10:05 UTC

**Comment by TheHaf** [comment] 2015-12-24 12:55
Oh, sorry about that, somehow I didn't spot the previous issue.
