### ISSUE TITLE
Windows: Media Keys can't get hotkey'd 

### ISSUE THREAD

**Issue by adajan** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#502] opened 2016-03-11 18:20 UTC
Hey,

I've been trying to set the hotkeys to my media keys on my keyboard, yet it won't set. Any normal keyboard key gets set. Previous version worked.

**Comment by LovedByTheLord** [comment] 2016-03-11 19:20
This is probably a duplicate of https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/344.

**Closed** 2016-03-11 20:04 UTC
