### ISSUE TITLE
Mini Player Constantly expands.

### ISSUE THREAD

**Issue by StockForStudentLoans** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2665] opened 2017-07-26 12:45 UTC
For some reason every time I open the mini player it enlarges infinitely... making it completely unusable. It used to work great, now it doesn't work at all.

**Comment by MarshallOfSound** [comment] 2017-07-26 13:20
Duplicate of #2269

**Closed by MarshallOfSound** 2017-07-26 13:20 UTC

**Comment by jvl59** [comment] 2017-07-29 16:45
This happens to me also. What version will this be released in?
