### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by AndrewJPOConnor** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#734] opened 2016-03-23 01:58 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Tue Mar 22 2016 21:56:22 GMT-0400 (US Eastern Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\andre\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\andre\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by AndrewJPOConnor** [comment] 2016-03-23 02:00
Submitted as requested by the GPMDP built-in bug reporter.
This only began happening after the 3.0.1 update.
It appears to occur when I switch back into GPMDP after using another window; I don't even have to interact with GPMDP--the bug report is already in a pop-up.

**Comment by AndrewJPOConnor** [comment] 2016-03-23 02:01
Also, there's no time-out on this error window; so I have to let GPMDP open a new internet tab to report the bug in order for the notification to go away.

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-23 02:07
Closing this automatically reported issue as a duplicate of #470

**Closed by GPMDP-Magical-Unicorn** 2016-03-23 02:07 UTC
Labels: Automatic-Issue-Report
