### ISSUE TITLE
Google will deny login to application

### ISSUE THREAD

**Issue by mayoralink** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3746] opened 2019-12-22 07:22 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Windows 10

**GPMDP Version:**

v.4.6.1

**Issue Descriptions:**

After attempting to sign in, a Google notification claims that the "browser" is unsafe and denies me the ability to login

**Steps to Reproduce:**

After install, entering credentials, confirming password and a "browser is unsafe" message will appear, denying login and asking to try again.

**Comment by Xernium** [comment] 2019-12-22 15:08
Have this issue too. Is not linked to me being enrolled in the APP with Google.

**Comment by Xernium** [comment] 2019-12-22 15:09
<img width="1312" alt="Bildschirmfoto 2019-12-22 um 16 00 35" src="https://user-images.githubusercontent.com/10787350/71323610-5f13f980-24d5-11ea-9664-17ad18542874.png">

**Comment by jostrander** [comment] 2019-12-22 15:20
Duplicate of #3545

**Closed by jostrander** 2019-12-22 15:20 UTC
