### ISSUE TITLE
Window Border colour keeps reverting to orange.

### ISSUE THREAD

**Issue by Sp4rkR4t** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#953] opened 2016-04-17 18:08 UTC
**OS:** Windows 10 x64

**Issue Descriptions:** 

As the title really, After the update I started the client and the window border was orange do went into the setting and turned dark mode off and on, that fixed it but then after a while the border went back to orange.

**Comment by jostrander** [comment] 2016-04-18 00:30
Can you pinpoint a particular action that switches back? I haven't been able to reproduce this yet.

**Comment by adifbbk1** [comment] 2016-04-18 09:31
This is a small bug
If you don't like it, just use windows borders

**Comment by SehWho** [comment] 2016-04-18 23:06
Having the same issue, except I can't get the border to _ever_ be anything but orange.

**Comment by MarshallOfSound** [comment] 2016-04-19 07:14
@jostrander I eventually managed to replicate this, but only on my friends rubbish laptop :+1:   It looks like in the latest version of electron something changed in chromium in regards to DOM rendering so some of our inject code was running before the DOM was ready.  It has been fixed in master in 5c24c63d78761dde80c69de7e4bb5f500b4ae496

**Closed by MarshallOfSound** 2016-04-19 07:14 UTC
