### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by alecholmez** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1289] opened 2016-07-08 15:03 UTC
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.3.0
**Time:** Fri Jul 08 2016 11:02:58 GMT-0400 (EDT)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: mouseButtonNavigation.js:9:1249.
    at BrowserWindow.callIntoRenderer (/Applications/Google Play Music Desktop Player.app/Contents/Resources/electron.asar/browser/rpc-server.js:186:19)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-07-08 15:10
Closing this automatically reported issue as a duplicate of #1287

**Closed by GPMDP-Magical-Unicorn** 2016-07-08 15:10 UTC
Labels: Automatic-Issue-Report, duplicate
