### ISSUE TITLE
Set up Google Play Music for Chrome

### ISSUE THREAD

**Issue by jacobslusser** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2921] opened 2017-12-22 00:48 UTC
**OS:**
Windows 10, 64-bit

**Issue Descriptions:**
After launching the app, it opens to the screen in the screenshot attached and I can't go beyond that. If I try to click INSTALL, it just spins forever.

**Steps to Reproduce:**
Start app

![image](https://user-images.githubusercontent.com/345183/34280722-bf1c1ee0-e66e-11e7-81a2-61e44dbf8243.png)

**Comment by jostrander** [comment] 2017-12-22 00:55
Duplicate of #706. Currently we don't have a fix for this as you'll see in that issue.

**Closed** 2017-12-22 00:54 UTC
