### ISSUE TITLE
couldnt sign you in.....

### ISSUE THREAD

**Issue by PandarenrRubio** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3733] opened 2019-12-17 19:47 UTC
ive been using this app for mnonths and just now icant get past the couldnt sign you in
![23dc8627476c13bef4479e22e2654e92](https://user-images.githubusercontent.com/58993691/71028813-a7957680-20d3-11ea-8b7e-830dbe22f927.png)

any way i can get thru it? i really would love to keep using it

**Comment by jostrander** [comment] 2019-12-17 20:17
Duplicate of #3545, please check that issue for temporary resolutions.

**Closed by jostrander** 2019-12-17 20:17 UTC
