### ISSUE TITLE
Can no longer log in

### ISSUE THREAD

**Issue by flyingmongoose** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3704] opened 2019-12-06 18:18 UTC
Google has changed their login method policies, embedded logins are no longer allowed on any application, they enforce that logins must communicate through opening up a web browser on desktop applications. This means this application effectively does not, and can not work right now.

**Comment by jostrander** [comment] 2019-12-06 18:21
Duplicate of #3545

**Closed by jostrander** 2019-12-06 18:21 UTC

**Comment by flyingmongoose** [comment] 2019-12-06 18:49
These are not the same issue, it loads fine and here are the two other parts.

1: I am on Windows

2: This was publicized by Google in April
Ref: https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html

Logins are not allowed in embedded browser frameworks **at all** anymore.

This means the actual login to the Google Services, can't be inside of the application, as of right now it provides this
![image](https://user-images.githubusercontent.com/399379/70347688-17337800-182f-11ea-8855-3f05da5a2b16.png)

The system detects the embedded framework and blocks the login outright.

Even google's own desktop applications, such as Chat for their paid-for tiers actually push you to opening a web browser to trigger your login.
