### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by ShaneK** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#587] opened 2016-03-14 17:29 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Mon Mar 14 2016 12:28:05 GMT-0500 (Central Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\sking\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\sking\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
    at Function.<anonymous> (C:\Users\sking\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\index.js:59:48)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by ShaneK** [comment] 2016-03-14 17:31
I don't actually know how this happened. I use windows 10 virtual desktops and it was open for a while on a different desktop (desktop 2), and I tried to open it from my task bar on desktop 1 (forgetting it was on desktop 2) and windows took me to desktop 2 and this error was visible there.

Thought I'd report it just in case. I think this way of error reporting is super rad, by the way :+1:

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-14 17:37
Closing this automatically reported issue as a duplicate of #470

**Closed by GPMDP-Magical-Unicorn** 2016-03-14 17:37 UTC
Labels: Automatic-Issue-Report
