### ISSUE TITLE
Stuck on Loading Music Library - Mac

### ISSUE THREAD

**Issue by phshromn** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3734] opened 2019-12-17 20:14 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:** Mac OSX Catalina 10.15.2

**GPMDP Version:** 4.6.1

**Issue Descriptions:** As of Monday 12/16 I can no longer get into play music from this app. It is stuck on the loading music library screen. I have looked over other articles and none of the suggested fixes work. I have loaded Youtube and logged out and back in and have done the same on my online accounts. I'd also be happy to send you the bug report if you tell me how to run it. 

**Steps to Reproduce:** Just open the app.

**Comment by jostrander** [comment] 2019-12-17 20:16
Duplicate of #3660. This is fixed in master. You'll have to use a build from master in order for it to appear fixed. There are links to the official CI in the README and in the comments in that issue.

**Comment by phshromn** [comment] 2019-12-17 20:17
How do I do that? I've read over it and didn't understand what I am supposed to do.

**Closed by jostrander** 2019-12-17 20:16 UTC

**Comment by phshromn** [comment] 2019-12-17 20:20
Nevermind, got it. Thank you and sorry for the duplicate. I promise I tried first.
