### ISSUE TITLE
"Show track progress in the taskbar" implementation shouldn't use indeterminate download animation.

### ISSUE THREAD

**Issue by ItchScratcher** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2801] opened 2017-10-03 17:55 UTC
**OS:**
Windows 10
**Issue Descriptions:**
When the "Show track progress in the taskbar" option is enabled, it constantly shows an animated, indeterminate status bar animation.  This happens even when the music is paused.  This makes it so you cannot tell the % completion of the song, or whether or not it's playing (assuming the PC is musted).  The Foobar2000 music player implements this feature in such a way that it shows progress without a constant pulsing animation, and turns yellow when playback is paused.  This seems like the correct behavior to me.  It should look like this when paused:
![image](https://user-images.githubusercontent.com/26801891/31140324-4ee5b602-a831-11e7-8a39-1849dd7c01d5.png)

**Steps to Reproduce:**
1. Enable "Show track progress in the taskbar" option in desktop settings.
2. Play a song, seek to about halfway.
3. Behold the pulsating taskbar icon, and the lack of progress it shows.
4. Pause the song.
5. Behold the pulsating taskbar icon.

**Comment by MarshallOfSound** [comment] 2017-10-03 23:45
This is a issue caused by the timing issues in the last release. The issue has been fixed in master

**Closed by MarshallOfSound** 2017-10-03 23:45 UTC

**Comment by francislavoie** [comment] 2017-10-19 04:48
Sorry to bump this issue, but when do you plan to make a new release including this fix? This bug has been really bothering me. Constant motion happening from the sidebar, very distracting.
