### ISSUE TITLE
Bluetooth headset commands not working

### ISSUE THREAD

**Issue by osandroribeiro** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#664] opened 2016-03-18 12:27 UTC
I have a Sony DR-BTN200 bluetooth headset, and the Play / Pause / Next Track / Previous Track headset commands are not working (running Ubuntu 15.10 at work).

I have been using this headset successfully with other streaming clients, like Spotify and Nuvola Player (Google Play Music and Deezer integrations).

**Comment by MarshallOfSound** [comment] 2016-03-18 14:02
This is either a duplicate of #626 or #638 

(Don't know which but one of them will cover it)

**Closed by MarshallOfSound** 2016-03-18 14:02 UTC
