### ISSUE TITLE
Uncaught Exception: EBUSY: resource busy or locked, open 'C:\Users\Jamie\AppData\Roaming\Google Play Music Desktop Playe

### ISSUE THREAD

**Issue by livejamie** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1284] opened 2016-07-07 01:30 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.3.0
**Time:** Wed Jul 06 2016 18:30:06 GMT-0700 (Pacific Daylight Time)

#### Error:
*EBUSY: resource busy or locked, open 'C:\Users\Jamie\AppData\Roaming\Google Play Music Desktop Playe*
```js
Error: EBUSY: resource busy or locked, open 'C:\Users\Jamie\AppData\Roaming\Google Play Music Desktop Player\json_store\playback.json'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.writeFileSync (fs.js:1337:33)
    at t.value (C:\Users\Jamie\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\main\utils\PlaybackAPI.js:9:2417)
    at t.value (C:\Users\Jamie\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\main\utils\PlaybackAPI.js:9:4016)
    at EventEmitter.<anonymous> (C:\Users\Jamie\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\main\utils\PlaybackAPI.js:9:1362)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (C:\Users\Jamie\AppData\Local\GPMDP_3\app-3.3.0\resources\electron.asar\browser\api\web-contents.js:156:13)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-07-07 01:40
Closing this automatically reported issue as a duplicate of #1260

**Closed by GPMDP-Magical-Unicorn** 2016-07-07 01:40 UTC
Labels: Automatic-Issue-Report, duplicate
