### ISSUE TITLE
Youtube Music: Undefined track name and artist on macos

### ISSUE THREAD

**Issue by EugeneTheDev** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3888] opened 2020-09-17 11:04 UTC
**Checklist:**

* [x] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES AS WELL**
* [x] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [x] I have double checked and can reproduce the issue

**OS:**
macOS Catalina 10.15.6 

**GPMDP Version:**
4.7.1 (YouTube Music)

**Issue Descriptions:**
Track name and artist shows "undefined" in window title and in Now playing widget when using youtube music

**Steps to Reproduce:**
Just launch app and play any track

**Comment by Landen13** [comment] 2020-09-17 14:04
Same on Windows 10

**Comment by manuelhe** [comment] 2020-09-17 19:57
Same on Linux. And related to this issue, last.fm tracking also stopped working

**Comment by KingDestructo** [comment] 2020-09-18 03:30
Same issue here as well

MacOS Catalina Version 10.15.3

**Comment by Hank3** [comment] 2020-09-18 15:24
I have two separate W10 PCs with a similar issue.  With the app open, it shows "Unknown Song - Unknown Artist" in the taskbar

![image](https://user-images.githubusercontent.com/24571086/93615483-73701e80-f9a1-11ea-9d9c-c3134cf352f1.png)

**Comment by calebmeyer** [comment] 2020-09-18 18:35
A few more details:
If you switch back to google play music, the track title/artist/album do display in the touchbar (macOS). If you then switch back to YTM again, the last track will be stuck there (at least for me, using better touch tool).

This was working at one point for me (on YTM), so I believe it is a regression.

**Comment by Hank3** [comment] 2020-09-18 18:51
> A few more details:
> If you switch back to google play music, the track title/artist/album do display in the touchbar (macOS). If you then switch back to YTM again, the last track will be stuck there (at least for me, using better touch tool).
> 
> This was working at one point for me (on YTM) as late as last week, so I believe it is a regression.

I noticed the same thing the other day when this started happening.  At one point, the player was changing title and artist and then it just stopped updating and remained on one song.  Ever since then, it's just been unknown title and artist.

Windows 10 Taskbar

**Comment by returnvisit** [comment] 2020-09-20 22:32
me too windows10

**Comment by mapoman** [comment] 2020-09-22 14:39
Bump for this issue, observed on Windows 10 when using YTM.

**Comment by roryhewitt** [comment] 2020-09-23 17:32
Me too on Windows 10, using YTM - in Windows taskbar, hovering over the icon shows "Unknown Song - Unknown Artist". Clicking on the taskbar icon brings up GPMDP with the correct values, obviously.

**Comment by MageMaster** [comment] 2020-09-25 20:54
![image](https://user-images.githubusercontent.com/8620621/94315005-130c4e80-ff58-11ea-961e-3b3503509697.png)
Me too, every information about the song currently playing is empty

**Comment by goodfella1978** [comment] 2020-09-29 11:17
Same here on Windows 10, the icon in the system tray was useful for a quick peek at what is playing, now shows this on YTM:

![image](https://user-images.githubusercontent.com/72078333/94551686-a80b9200-024d-11eb-928f-55bd284b080e.png)

P.S. Still **love** this player!!

**Comment by tom-james-watson** [comment] 2020-10-13 14:26
Looks like the fix upstream has been merged https://github.com/gmusic-utils/ytmusic.js/issues/14

I've opened https://github.com/gmusic-utils/ytmusic.js/issues/20 to release a new version of the ytmusic.js lib, which I believe this app can then pull to fix this issue.

**Comment by returnvisit** [comment] 2020-10-13 14:37
Thanks!

Marco F

**Comment by jostrander** [comment] 2020-10-13 14:44
Published 6.2.2 in ytmusic.js, If someone wants to PR in that upgrade here.

**Comment by lesthack** [comment] 2020-10-13 17:45
> Published 6.2.2 in ytmusic.js, If someone wants to PR in that upgrade here.

Thank you, work for me.

**Comment by Hank3** [comment] 2020-10-13 17:54
So the issue is fixed?  Sorry I'm not too familiar with with the verbiage being used here.  Do I need to go somewhere to download an updated version?

**Comment by manuelhe** [comment] 2020-10-13 17:57
> So the issue is fixed? Sorry I'm not too familiar with with the verbiage being used here. Do I need to go somewhere to download an updated version?

No, the issue it's not yet fixed in the player, but the origin of the problem was already patched. We need to wait a time until an "official" version be released

**Comment by Hank3** [comment] 2020-10-13 17:59
> > So the issue is fixed? Sorry I'm not too familiar with with the verbiage being used here. Do I need to go somewhere to download an updated version?
> 
> No, the issue it's not yet fixed in the player, but the origin of the problem was already patched. We need to wait a time until an "official" version be released

Thank you for the info!

**Closed** 2020-10-13 18:53 UTC

**Comment by lesthack** [comment] 2020-10-13 19:11
Toc toc @MarshallOfSound, I think that we need a new oficial release :D

**Comment by Nithindanday** [comment] 2020-10-17 01:13
Yes im not able to build it keeps erroring

**Comment by c4naan** [comment] 2020-10-26 19:33
> ~Yes im not able to build it keeps erroring~
> I just downloaded the auto build artifact from [here](https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/branch/master/artifacts)
> Edit2: Discord RPC still doesnt work


this worked for me, thanks for taking the time to post the link

**Comment by shpaggin** [comment] 2020-10-26 19:44
> ~Yes im not able to build it keeps erroring~
> I just downloaded the auto build artifact from [here](https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/branch/master/artifacts)
> Edit2: Discord RPC still doesnt work

Is there a way to get a MacOS build this way? 

Or does anyone know if a patched official release is in the works?

**Comment by jamgregory** [comment] 2020-10-29 15:01
It looks like the Linux build is currently failing, so there's no updated packages for us currently. I've tried building it locally but am now encountering the issue flagged up in #3889 - basically there appear to be some image assets that are not being correctly built.

@MarshallOfSound @lesthack - I don't suppose you know if a new release is coming soon to fix these issues? :pray:

**Comment by minipasila** [comment] 2020-10-31 12:01
I tried that new build but for whatever reason last.fm still isn't working properly. It doesn't like scrobble any of my songs though last.fm does know I'm listening to a song but it won't scrobble it and at first it didn't even see me listening to a song either and so I tried liking something so it would add it to my loved tracks which worked and now it shows that I'm listening to the song that I really was but once it moved on to the next song it showed that I was listening to it and it also loved that track which I didn't click like on. And it also didn't actually scrobble the last song either. So I guess I still have to use it on the browser if I want to track my songs.. Discord Rich Presence worked like it should though.

**Comment by mdonoughe** [comment] 2020-11-01 20:07
With the latest master build, the API returns track information again, but the album art is coming up as "https://music.youtube.com/" for me.

**Comment by domoritz** [comment] 2020-11-02 00:47
Same as @mdonoughe for me. I built my own bundle off of master. 

<img width="301" alt="Screen Shot 2020-11-01 at 16 45 25" src="https://user-images.githubusercontent.com/589034/97820204-eab3f600-1c61-11eb-996e-a8502014fd3e.png">

**Comment by roryhewitt** [comment] 2020-11-03 19:15
I have to revert my previous "It's fixed" comment above (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3888#issuecomment-717590885) :(

Running on Windows 10 Enterprise (1803, 17134.1667), using the "Fix #3888: Upgrade ytmusic to 6.2.2 (#3897)" version I downloaded from https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/branch/master/artifacts, I see the following errors:

* App always starts in 'Google Play' mode, even though I have completely migrated to YT Music. I guess this is just a minor buglet - just means I have to click the 'Transfer to YouTube Music' button each time
* Once opened, if I minimize the player by clicking the Minimize button on the player itself, then the aero tooltip will subsequently not display on mouse hover. However, If I click the tooltip icon to minimize the player, the aero popup WILL show
* When the aero popup does appear on mouse hover, the play/pause button **always** shows as Play, even though the music is already playing. Clicking the button doesn't do anything. The song title always shows as "Google Play Music Desktop Player"

I know it's an unofficial branch build, but it's actually worse than before...

**Comment by quangkieu** [comment] 2020-11-06 08:21
I use the same artifact but I do not see any of your error, @roryhewitt 
I am on Windows Insider build
Edition	Windows 10 Education
Version	20H2
OS build	19042.610
Experience	Windows Feature Experience Pack 120.2212.31.0

**Comment by coagmano** [comment] 2020-11-09 22:34
just tested a local build of master on OSX (10.15.7) and last.fm didn't scrobble for YTM

**Comment by KveRa** [comment] 2020-12-08 10:51
@quangkieu im also using the same build artifact here, without any issues by now, @roryhewitt. Have u tried a clean install?

---
Windows 10 Enterprise
Version 20H2
OS Build 19042.662
Windows Feature Experience Pack 120.2212.551.0

**Comment by curtisgibby** [comment] 2020-12-10 17:49
> This is fixed in master. Unfortunately unless @MarshallOfSound produces a release, there isn't anything to "download" to fix this problem

What's the point of fixing the bug if you're not going to get it out to people? Why make users try to hack their own build? Is there something specific preventing an official release?

**Comment by tom-james-watson** [comment] 2020-12-10 17:54
The person who merged it does not have control over the builds. @MarshallOfSound has produced an application for free on his own time and clearly is a very busy person with lots of other priorities. You need to bear in mind that these people are working for free and are not at our beck and call. We'll just need to have some patience here.

**Comment by anton-khodak** [comment] 2020-12-10 18:02
They may not be at our beck and call, but @MarshallOfSound is not responsive for at least two months already. It is irresponsible to abandon a project used by so many people without any explicit aknowledgement or handover to someone who would like to maintain it or at least without initiating such a discussion.

**Comment by curtisgibby** [comment] 2020-12-10 21:12
> We'll just need to have some patience here.

Patience is what the last two months has been. We all agree that @MarshallOfSound has created an excellent program -- that's why we're here. We just want the latest and greatest version of that program. The hard work's already been done, so I would like to understand why the build-and-release script hasn't been run.

**Comment by jostrander** [comment] 2020-12-10 21:39
> What's the point of fixing the bug if you're not going to get it out to people? Why make users try to hack their own build? Is there something specific preventing an official release?

I can only do so much :slightly_frowning_face:. I don't have access to sign releases, but at least by merging in fixes people who utilize the source such as AUR users can benefit from them.

> Patience is what the last two months has been.

Unfortunately, this project has been floating for much longer than two months. If you notice there have only been 2 releases in the last 18 months. 

> The hard work's already been done, so I would like to understand why the build-and-release script hasn't been run.

There is no script. The build-and-release process is mostly manual and takes a fair amount of time, and once it rolls out someone has to make sure there are no major bugs and be ready to hotfix anything that might be broken. The only person who can do this doesn't have the time to do it.

**Comment by matthew-sharp** [comment] 2020-12-28 22:53
> handover to someone who would like to maintain it

It's MIT licensed and on github. Anyone is free to fork this project and maintain it.

**Comment by mesmerx** [comment] 2021-01-23 21:07
if anyone have this problem still this build resolves the problem
https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/builds/36495361/artifacts

**Comment by Chrysalairus** [comment] 2021-01-31 17:47
> 
> 
> if anyone have this problem still this build resolves the problem
> https://ci.appveyor.com/project/MarshallOfSound/google-play-music-desktop-player-unofficial/builds/36495361/artifacts

Great, thanks. The only problem this build has is the album art shows the previous song's album art, not the current. Not a huge deal and doesn't really affect me. I just thought I'd let you know.
![Screenshot_2](https://user-images.githubusercontent.com/78316287/106392955-ce873880-63b9-11eb-914c-cb3fbaeef351.png)
