### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by korich** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#695] opened 2016-03-20 20:39 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Mon Mar 21 2016 09:39:24 GMT 1300 (New Zealand Summer Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\matt.corich\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\matt.corich\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by korich** [comment] 2016-03-20 20:40
I think this was because i had the player in the mini player mode, you can probably swallow this exception

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-20 20:52
Closing this automatically reported issue as a duplicate of #470

**Closed by GPMDP-Magical-Unicorn** 2016-03-20 20:52 UTC
Labels: Automatic-Issue-Report, duplicate
