### ISSUE TITLE
Duplicate switches in Labs section of settings

### ISSUE THREAD

**Issue by hndmrsh** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#22] opened 2015-11-01 00:18 UTC
Some Labs options have duplicated switches. See attached screenshot:
<img width="322" alt="capture" src="https://cloud.githubusercontent.com/assets/2135075/10866597/b0a909f4-809a-11e5-8df3-ba70731557b9.PNG">

**Comment by MTRougeau** [comment] 2015-11-01 00:20
I believe this is a duplicate of Issue 13, which has been fixed.

**Comment by hndmrsh** [comment] 2015-11-01 00:22
Correct, didn't notice that - thanks for the heads up!

**Closed** 2015-11-01 00:22 UTC
