### ISSUE TITLE
Mouse button 4 still not working for back

### ISSUE THREAD

**Issue by ThurnisH41ey** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#878] opened 2016-04-02 16:57 UTC
**OS: Arch Linux 4.4.5**

**Issue Descriptions: Though the changelog said that mouse button back should be working, I am still experiencing no response when pressing mouse button 4 to go back.**

**Steps to Reproduce: Open gpmdp, click on an album, press mouse button 4.**

**Comment by jostrander** [comment] 2016-04-02 17:02
Mouse button 4? Can you open `xev` and send me the output of your back button?

**Comment by davorb** [comment] 2016-04-02 21:01
https://gist.github.com/davorb/aa1fce1678e49b4abd8ab312cc0b8bc4

**Comment by jostrander** [comment] 2016-04-02 21:06
@davorb Is your back button not working either? Are you using the master build?

**Comment by jostrander** [comment] 2016-04-03 20:15
Okay I need some more input from either of you before I can fix anything here.  @davorb You are registering key 8 as back, which is the correct key so everything should be working. @ThurnisH41ey If you have mouse button 4 registered as the back button, what mouse are you using? Buttons 4 and 5 are usually the scroll wheel.

**Comment by ThurnisH41ey** [comment] 2016-04-04 04:03
ButtonPress event, serial 32, synthetic NO, window 0x1800001,
    root 0x1d1, subw 0x0, time 7961025, (577,684), root:(591,740),
    state 0x10, button 8, same_screen YES

ButtonRelease event, serial 32, synthetic NO, window 0x1800001,
    root 0x1d1, subw 0x0, time 7961149, (577,684), root:(591,740),
    state 0x10, button 8, same_screen YES

**Comment by ThurnisH41ey** [comment] 2016-04-04 04:03
Maybe it's not MB4 then. I'm using a Mionix Naos 7000

**Comment by jostrander** [comment] 2016-04-04 04:50
I'm not sure how the package system works on arch, etc, but is it possible for you to run this from shell and capture the output? The native module should be spitting out an error if the window is failing to register. Other than that I'm not sure specifically what would be causing the issue, as you both have mouse button 8 triggering xev.

**Comment by jostrander** [comment] 2016-04-04 19:47
Stable builds should fix this in the future, aka `gpmdp-git` in AUR because it's pre-built by Circle CI. The current non-stable branch on the AUR (aka `google-play-music-desktop-player-git`) won't build correctly until all the dependencies have been met, which are not present in PKGBUILD.

**Comment by BrianAllred** [comment] 2016-04-05 01:02
@jostrander I maintain both AUR packages. Could you specify what I'm missing in the non-stable package? It builds, installs, and runs for me, though I don't have enough mouse buttons to test this functionality.

**Comment by jostrander** [comment] 2016-04-05 01:45
Currently in order for the mouse functionality to be built, the libx11-dev (ubuntu) package equivalent needs to be present, or at the very least the X11 headers for both 32 and 64 bit. I tried searching but I'll be honest my Arch knowledge is pretty slim. The stable build as I said is fine because you're pulling the pre-built deb which is built with all the dependencies. 

This is the build error I was receiving on Arch this morning when I tried downloading the PKGBUILD and building/installing:

![image](https://cloud.githubusercontent.com/assets/760989/14268742/76ca0cb0-faac-11e5-8826-765cf4a64cc4.png)

It looks like it may be related to not having the equivalent of multiarch libs installed (ia32-libs/debian). 
I would like to separate the build tooling out so that you can build a better package for arch, or independently build each package in general for linux to avoid issues like this in the future.

**Comment by BrianAllred** [comment] 2016-04-05 02:01
Yep, looks like it won't build on a fully 32-bit or 64-bit system due to the build process building both by default. If you're running on a 64-bit Arch installation, edit /etc/pacman.conf, uncomment the multilib repository, and install gcc-multilib. This should allow you to build and install.

Sadly, because of the way Arch works, this effectively limits the package's compatibility to the subset of 64-bit Arch users that have multilib enabled (since 32-bit Arch can't build 64-bit packages period). If the build tools could be managed in such as a way that allowed building only a specific architecture at a time, then this problem would be solved. Until that time, I'll add gcc-multilib as a build dependency for the unstable package.

All of that being said, this shouldn't have anything to do with mouse buttons issues. :confused:

**Comment by jostrander** [comment] 2016-04-05 02:05
Well unfortunately the mouse uses my custom built node native module to capture buttons 8 and 9 for the gpm window because electron doesn't capture them, and if that fails to build the deb will still continue because its only an optional dependency, but the buttons won't work. I was able to get the master branch to build from master and work with my mouse, but couldn't get you're pkgbuild to build correctly and work with the mouse buttons (I'm assuming) from the errors above.

**Comment by BrianAllred** [comment] 2016-04-05 02:09
Gotcha. If you uncomment the multilib repository and run `sudo pacman -Syy gcc-multilib`, you should be good to go to use my PKGBUILD. Would you then be able to see if your module is being built?

**Comment by jostrander** [comment] 2016-04-05 02:32
I will spin up the VM and see what I can do, if you don't mind, where am I uncommented multilib?

**Comment by BrianAllred** [comment] 2016-04-05 02:35
in `/etc/pacman.conf` there should be two lines that look like 

```
#[multilib]
#Include = /etc/pacman.d/mirrorlist
```

Uncomment those, then run `sudo pacman -Syy gcc-multilib`. Should be good. Note that I've not ever combined -Syy with a package name, so if that doesn't work, try `pacman -Syy` and then `pacman -S gcc-multilib`.

**Comment by jostrander** [comment] 2016-04-05 03:58
Still missing X11 dev headers in the master build processes:

```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libX11.so when searching for -lX11
/usr/bin/ld: skipping incompatible /usr/lib/libX11.so when searching for -lX11
/usr/bin/ld: cannot find -lX11
collect2: error: ld returned 1 exit status
```

**Comment by jostrander** [comment] 2016-04-05 04:07
However mouse buttons are working without issue for me now via AUR.

@ThurnisH41ey @davorb can you update your packages and see if it fixes the issue?

**Comment by davorb** [comment] 2016-04-05 20:40
Hey, 

Sorry for the late reply @jostrander. I just built it on my machine (Ubuntu 15.10) and it works great. 

Thanks!

**Comment by BrianAllred** [comment] 2016-04-05 22:48
@jostrander 

Little late, but wanted to let you know I added libx11 dependencies to the unstable pkgbuild as make dependencies.

**Comment by MarshallOfSound** [comment] 2016-04-06 01:34
@BrianAllred @jostrander Can I close this issue now considering the AUR's packages now build?

We can watch #894 for further progress

**Comment by BrianAllred** [comment] 2016-04-06 01:51
@MarshallOfSound Yes, I can confirm the back and forward shortcuts work using the AUR package. Found a mouse with enough buttons, lol.

**Comment by jostrander** [comment] 2016-04-06 01:58
I think it would be safe to close this issue and track #894 for future updates as the mouse buttons were only a side effect.

**Closed** 2016-04-06 02:05 UTC
