### ISSUE TITLE
Can't install GPMDPU on Fedora 29

### ISSUE THREAD

**Issue by marquesarthur** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3527] opened 2019-03-14 16:56 UTC
Hi all, 

I migrated from Fedora 28 to 29 and now, I can't install the app through its package bundle Fedora-64 bit

![image](https://user-images.githubusercontent.com/1497480/54375918-2f2ef000-463f-11e9-98f5-631aa5aea62a.png)

I get the above error

ENV:
Fedora - 29
Gnome - 3.30.2

**Comment by yerbestpal** [comment] 2019-03-16 00:54
@marquesarthur There is also Flatpak, which is not maintained by the developer but is up-to-date.
https://flathub.org/apps/details/com.googleplaymusicdesktopplayer.GPMDP

**Comment by choephel** [comment] 2019-03-16 20:28
It seems that there's an issue with electron not being up-to-date in 4.6.1 stable that's causing issues with the latest versions of Ubuntu and Fedora.

See #3391 and specifically [this comment](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3391#issuecomment-460723068) for more information and an .rpm that I can confirm is working for me on Fedora 29

**Comment by yerbestpal** [comment] 2019-03-17 21:37
@choephel This is what I was looking for, thanks. Are you involved in development? If so, are there any plans for this to make it into the main release?

**Comment by MarshallOfSound** [comment] 2019-03-17 21:56
Closing as duplicate of #3391

**Closed by MarshallOfSound** 2019-03-17 21:56 UTC

**Comment by choephel** [comment] 2019-03-18 00:43
@yerbestpal Not involved in development, but I feel certain that it will be incorporated into the main release as it both fixes a major problem that multiple users have reported and it's currently an element of the latest unreleased builds.
