### ISSUE TITLE
Player randomly freezes and only a reboot will fix it.

### ISSUE THREAD

**Issue by IrishMash** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2742] opened 2017-09-03 04:46 UTC
**OS:**
Windows 10
**Issue Descriptions:**
Sometimes when searching for an artist or song the player will randomly freeze. Have tried quitting everything from quitting the program to ending the task all together. The only way I have found to fix this is to reboot my system. I submitted this issue just the other day to have it be closed out with a message saying that I can just quit the program and it will work. If it did I would never have gone as far as rebooting to attempt to fix the issue.
**Steps to Reproduce:**
Cannot reproduce. It will just randomly happen every now and then.

**Comment by MarshallOfSound** [comment] 2017-09-03 04:50
Please **do not** raise duplicate issues, especially when it's a duplicate of your own issue you raised literally 24 hours ago.

Duplicate of #2739

**Closed by MarshallOfSound** 2017-09-03 04:50 UTC
