### ISSUE TITLE
Player UI freezes when switching songs, but song continues playing

### ISSUE THREAD

**Issue by NoahHamlen** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2002] opened 2016-12-10 02:33 UTC
**OS:** Windows 10 

**Issue Descriptions:** Player freezes at random, and can be momentarily unfrozen by right clicking the tray icon. Music still continues playing, but cannot be paused or controlled.

**Steps to Reproduce:** The issue usually presents itself when it switches songs, and I believe it to somehow be related to the Windows 10 notifications.

[debug_info.zip](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/files/643524/debug_info.zip)

**Comment by MarshallOfSound** [comment] 2016-12-10 14:55
This is a duplicate of a duplicate of a duplicate (see where this is going).  Please check closed issues for similar problems.

Basically there is *something* going on with new*ish* windows installs that is causing certain calls to the Toast API to freeze for a long amount of time.  Until either Windows or Electron fixes this please just disable notifications.

**Closed by MarshallOfSound** 2016-12-10 14:55 UTC
