### ISSUE TITLE
Reordering songs in a playlist causes the page to refresh. 

### ISSUE THREAD

**Issue by ntowl24** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2657] opened 2017-07-24 09:39 UTC
**OS: Windows 10**

**Issue Descriptions: Reordering songs using drag/drop in a playlist causes the whole page to refresh. This issue is not present in the browser version of Play Music.**

**Steps to Reproduce: See above**

**Comment by jostrander** [comment] 2017-07-30 19:57
I can't reproduce this using latest release. What version are you using?

**Comment by snhardin** [comment] 2017-07-31 23:47
This is happening for me as well. I am running version 4.4.0 of GPMDP on Windows 10 64-bit and I'm logged into an account that is currently subscribed to Google Play Music. Let me know what other information I can provide to help narrow down this issue.

**Comment by MarshallOfSound** [comment] 2017-08-22 00:26
This issue came up in another thread somewhere and was declared as being a google issue as it happened in Chrome as well, I think people got hit with some A/B testing.  Closing this out until it becomes clear it's a problem on our end of things

**Closed by MarshallOfSound** 2017-08-22 00:26 UTC
Labels: Unconfirmed
