### ISSUE TITLE
Buggy minimize, maximize, and close buttons

### ISSUE THREAD

**Issue by FISHunderscore** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#66] opened 2015-11-30 01:20 UTC
Note: I'm running the x64 version on win7.

* The minimize button will not do anything (fullscreen or not)
* The maximize button will make the program fullscreen, but will not restore it back down
* Clicking near the three buttons (min, max, and close) in the top bar of the player can sometimes show Windows Classic-like icons for the buttons (as shown below)
![image](https://cloud.githubusercontent.com/assets/11418203/11461686/0902b270-96bd-11e5-80dd-99e43471255b.png)

**Comment by FISHunderscore** [comment] 2015-11-30 01:32
The minimize button seems to work if you click in the top 1/3 of the minimize icon. Maybe something to do with scaling?

**Comment by FISHunderscore** [comment] 2015-11-30 01:36
Sorry, accidentally closed issue when I commented.

**Comment by MarshallOfSound** [comment] 2015-11-30 01:44
The 1/3 thing you mention is due to the windows min, max and close icons being rendered (sometimes invisibly) on top of my custom border.  I have no explanation for this, and no idea how to fix it.  This is no doubt an exact duplicate of #31 so I'll mark this as a duplicate and try figure it out over there.  There is a debug build in that other issue thread if you want to try that out, it was just me mucking around trying to fix it.

But yeah, the only known solution at the moment is to not use Windows 7 :smile: 
I keep looking for a nice fix for this, but I am not convinced one exists

**Comment by MarshallOfSound** [comment] 2015-11-30 01:45
Duplicate: #31

**Closed by MarshallOfSound** 2015-11-30 01:44 UTC

**Comment by Meegooo** [comment] 2015-12-06 14:23
Had similar issue on windows 10. I pressed maximize button and player just closed (like i pressed "close" button). It happened like 3 times in a row. 
However, after i used "aero snap" to make it fullscreen (it's not aero anymore, but anyway :smile: ) it was fixed and I can't reproduce it anymore.
