### ISSUE TITLE
Feature Request: "Quit" menu button

### ISSUE THREAD

**Issue by WhiteGOSHAN** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1577] opened 2016-09-03 19:04 UTC
It would be nice to see the "Quit" button in app menu (next to "Desktop Settings" one). When app is open it more convenient to close app from menu, without need of going to tray.

**Comment by MarshallOfSound** [comment] 2016-09-09 19:22
This issue has been added to the `4.0.0` milestone.

**What does this mean?**
It means that the next major release *should* contain this feature / bugfix.  If you are responsible for this issue please ensure that it is fully up to date to give me the best change of implementing / fixing what needs to be done.

**What do you need to do?**
If the issue is tagged with "Awaiting Response" it means that I need something from you, be that more information or in some cases a PR with the issue resolution 👍 .  Just do whatever you can to help me sort it out.

**So when will this glorious `4.0.0` release come out?**
Who knows... 😆  The major component of `4.0.0` is a rewrite of **ALL** the renderer process code and logic into a React based toolkit that I am creating from scratch over in #1581 .  Subscribe there for more updates as `4.0.0` will not be released until that is merged.

**Closed** 2016-09-11 18:23 UTC
Labels: Easy First Issue, enhancement
