### ISSUE TITLE
Windows: Prev/Next media controls double-fire

### ISSUE THREAD

**Issue by intel352** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3512] opened 2019-03-03 07:25 UTC
When using Win10, if I enable the Win10 System Media Service setting, whenever I go to Prev or Next track using keyboard hotkeys (the default media hotkeys, nothing is bound explicitly in GPMDP), the player skips one extra song for every key press.

So instead of going from 1 -> 2 when pressing Next, player goes from 1 -> 2 (briefly shows) -> 3.
If I disable the media service integration, prev/next works correctly.

Version 4.6.1

**Comment by jespersh** [comment] 2019-03-03 09:43
Dupe of #2364

**Comment by jostrander** [comment] 2019-03-03 17:35
Correct. Duplicate of #2364.

**Closed by jostrander** 2019-03-03 17:35 UTC
