### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by nilsjha** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#861] opened 2016-03-31 15:45 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.1.0
**Time:** Thu Mar 31 2016 17:41:11 GMT 0200 (Vest-Europa (sommertid))

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\%USERDIR%\AppData\Local\GPMDP_3\app-3.1.0\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:18:9.
    at BrowserWindow.callIntoRenderer (C:\Users\%USERDIR%\AppData\Local\GPMDP_3\app-3.1.0\resources\atom.asar\browser\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

The issue occurs when I'm adjusting the audio level with the volume keys on my HP multimedia keyboard. The level then adjusts accordlingly ( as normal ) - I think it's more likely a user interface issue then a real problem.

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-31 15:59
Closing this automatically reported issue as a duplicate of #847

**Closed by GPMDP-Magical-Unicorn** 2016-03-31 15:59 UTC
Labels: Automatic-Issue-Report, duplicate
