### ISSUE TITLE
Uncaught Exception: The Internet connection appears to be offline.: (null)

### ISSUE THREAD

**Issue by spencertoyama** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#541] opened 2016-03-13 09:42 UTC
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.0.0
**Time:** Sat Mar 12 2016 23:41:32 GMT-1000 (HST)

#### Error:
*The Internet connection appears to be offline.: (null)*
```js
Error: The Internet connection appears to be offline.: (null)
    at Error (native)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-13 09:51
Closing this automatically reported issue as a duplicate of #269

**Closed by GPMDP-Magical-Unicorn** 2016-03-13 09:51 UTC
Labels: Automatic-Issue-Report
