### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by bryan1545** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1366] opened 2016-07-28 22:23 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.3.0
**Time:** Thu Jul 28 2016 16:22:46 GMT-0600 (Mountain Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\Bryan\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\inject\GPMWebView\interface\customNavigation\mouseButtonNavigation.js:9:1167.
    at BrowserWindow.callIntoRenderer (C:\Users\Bryan\AppData\Local\GPMDP_3\app-3.3.0\resources\electron.asar\browser\rpc-server.js:186:19)
    at emitTwo (events.js:111:20)
    at BrowserWindow.emit (events.js:191:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-07-28 22:26
Closing this automatically reported issue as a duplicate of #1286

**Closed by GPMDP-Magical-Unicorn** 2016-07-28 22:26 UTC
Labels: Automatic-Issue-Report, duplicate
