### ISSUE TITLE
Uncaught Exception: Attempting to call a function in a renderer window that has been closed or released. Function provid

### ISSUE THREAD

**Issue by merlynmg** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#738] opened 2016-03-23 10:03 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.0.1
**Time:** Wed Mar 23 2016 03:02:41 GMT-0700 (Pacific Daylight Time)

#### Error:
*Attempting to call a function in a renderer window that has been closed or released. Function provid*
```js
Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: Object.<anonymous> (C:\Users\...\AppData\Local\GPMDP_3\app-3.0.1\resources\app\build\inject\GPMInject\interface\mouseButtonNavigation.js:8:8.
    at BrowserWindow.callIntoRenderer (C:\Users\...\AppData\Local\GPMDP_3\app-3.0.1\resources\atom.asar\browser\lib\rpc-server.js:201:19)
    at emitTwo (events.js:92:20)
    at BrowserWindow.emit (events.js:172:7)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by merlynmg** [comment] 2016-03-23 10:04
Specifically seems to happen after I restore it from being minimized

**Comment by merlynmg** [comment] 2016-03-23 10:06
I am on Windows 10. I downloaded it, ran it from the downloaded folder. The installer completed. I pinned the running program to the taskbar. I logged in. I played some songs. I minimized while it was playing. I came back to the window and saw that error pop up at the bottom.

I never experienced a UAC prompt when "installing". I haven't relaunched the app yet - this is still the first run.

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-03-23 10:08
Closing this automatically reported issue as a duplicate of #470

**Closed by GPMDP-Magical-Unicorn** 2016-03-23 10:08 UTC
Labels: Automatic-Issue-Report
