### ISSUE TITLE
Uncaught Exception: Could not get code signature for running application

### ISSUE THREAD

**Issue by knlin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#888] opened 2016-04-04 00:27 UTC
An uncaught exception was reported.  
#### Info:
**OS:** darwin
**Arch:** x64
**GPMDP Version:** 3.1.0
**Time:** Sun Apr 03 2016 20:26:56 GMT-0400 (EDT)

#### Error:
*Could not get code signature for running application*
```js
Error: Could not get code signature for running application
    at Error (native)
    at /Applications/Google Play Music Desktop Player.app/Contents/Resources/app/build/main/features/core/autoUpdater.js:20:29
    at setUpAutoUpdate (/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/build/main/features/core/autoUpdater.js:59:7)
    at ClientRequest.<anonymous> (/Applications/Google Play Music Desktop Player.app/Contents/Resources/app/build/main/features/core/autoUpdater.js:67:5)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:421:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_client.js:311:20)
```
This issue was created automatically inside the `uncaughtException` handler

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-04-04 00:31
Closing this automatically reported issue as a duplicate of #370

**Closed by GPMDP-Magical-Unicorn** 2016-04-04 00:31 UTC
Labels: Automatic-Issue-Report, duplicate
