### ISSUE TITLE
Voice Controls enabled, doesn't respond to commands

### ISSUE THREAD

**Issue by JegorRysskin** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#2996] opened 2018-02-08 20:16 UTC
**OS:** Windows 10

**Issue Descriptions:** I can't get Voice Controls feature to work. I turned on the option in the settings but when I speak it doesn't respond to any of my voice commands.

**Steps to Reproduce:** 1. Enable Voice Controls in settings
2. Restart the client just to be sure
3. Issue a voice command and wait for response
4. Nothing happens

**Comment by nicusorflorin** [comment] 2018-02-09 06:22
duplicate #2408

**Comment by jostrander** [comment] 2018-02-09 16:12
Agreed, duplicate of #2408

**Closed by jostrander** 2018-02-09 16:12 UTC
