### ISSUE TITLE
GPMDP not loading past "Loading Music Library.."

### ISSUE THREAD

**Issue by Zazool** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3684] opened 2019-11-25 16:42 UTC
**OS:**

Windows 10 1903 - OS build 18362.476

**GPMDP Version:**

V4.6.1

**Issue Descriptions:**

I was changing some settings within GPMDP itself, GPMDP crashed and now it won't load at home or on my work computer, (I think I need to do some kind of profile reset to revert the changes i made) - does anyone know if/how I might be able to do this?

the application just gets stuck at "Loading Music Library..."

gpmdp.log has this in after each time i attempt to load GPMDP:

{"level":"info","message":"Application started.","timestamp":"2019-11-25T14:33:47.043Z"}
{"level":"error","message":"Failed to load bonjour with error: {}","timestamp":"2019-11-25T14:33:50.423Z"}

**Steps to Reproduce:**

change a lot of settings in GPMDP

**Comment by jostrander** [comment] 2019-11-25 16:46
Duplicate of #3660

**Closed by jostrander** 2019-11-25 16:46 UTC
