### ISSUE TITLE
Uncaught Exception: Cannot read property '1' of null

### ISSUE THREAD

**Issue by tf2manu994** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#1315] opened 2016-07-14 06:28 UTC
An uncaught exception was reported.  
#### Info:
**OS:** win32
**Arch:** ia32
**GPMDP Version:** 3.3.0
**Time:** Thu Jul 14 2016 16:26:36 GMT 1000 (AUS Eastern Standard Time)

#### Error:
*Cannot read property '1' of null*
```js
TypeError: Cannot read property '1' of null
    at Request._callback (C:\Users\Manu\AppData\Local\GPMDP_3\app-3.3.0\resources\app\build\main\features\core\lyrics\source_lyricsFreak.js:9:1201)
    at Request.self.callback (C:\Users\Manu\AppData\Local\GPMDP_3\app-3.3.0\resources\app\node_modules\request\request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Manu\AppData\Local\GPMDP_3\app-3.3.0\resources\app\node_modules\request\request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Manu\AppData\Local\GPMDP_3\app-3.3.0\resources\app\node_modules\request\request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```
This issue was created automatically inside the `uncaughtException` handler

For reference, it happened when I pushed the media play/pause key while nothing was playing (I think).

**Comment by GPMDP-Magical-Unicorn** [comment] 2016-07-14 06:40
Closing this automatically reported issue as a duplicate of #1281

**Closed by GPMDP-Magical-Unicorn** 2016-07-14 06:40 UTC
Labels: Automatic-Issue-Report
