### ISSUE TITLE
Google Play Not Loading

### ISSUE THREAD

**Issue by thecuban** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3674] opened 2019-11-13 20:57 UTC
**Checklist:**

* [ ] I have checked that there are no issues with similar or the same content

  **YOU SHOULD CHECK CLOSED ISSUES ASWELL**
* [ ] I have checked the FAQ (https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/FAQ) and the answer I am looking for is not there
* [ ] I have double checked and can reproduce the issue

**OS:**

**GPMDP Version:**

**Issue Descriptions:**

**Steps to Reproduce:**

**Comment by jostrander** [comment] 2019-11-13 20:58
Duplicate of #3660

**Closed by jostrander** 2019-11-13 20:58 UTC

**Comment by thecuban** [comment] 2019-11-13 21:02
Opps, I only saw #2548 and that didnt solve my issue, didnt see #3660. My bad
