### ISSUE TITLE
Music continues to play but UI freezes

### ISSUE THREAD

**Issue by mpelley92** [MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-#3495] opened 2019-02-13 21:20 UTC
**OS:** Windows 7 x64

**GPMDP Version:** 4.6.1

**Issue Descriptions:** I can see from another post that there may be an issue with lyrics or something? I'm not sure so I'm posting my own thread to deal with my issue. It happens randomly. Sometimes 2 minutes after opening the program, and sometimes after hours of playing music. I have a new, fresh install of Windows 7 x64, and on my instance of Windows before my refresh, I had a previous version of GPMDP that did not lock-up or crash, whatsoever.

This latest string of lock-ups made me post here, since I do not want to give up and just stop using this program. The last three lock-ups were caused by one song in particular, "The Appeal & The Mindsweep (Metrik remix)" by Enter Shikari. I reproduced this lock-up three times in a row. Not only that, but the song would finish, and the audio would cut off somewhere in the middle of the second song.

Desktop notifications is turned off. I tried changing other settings with no avail. The SSD this operating system and program is installed on is fine, no errors, 100% life. No other programs are crashing or locking up.

**Steps to Reproduce:** End task in Task Manager, restart program, look for specific song, UI locks up a few seconds after pressing play.

**Comment by jostrander** [comment] 2019-02-13 21:40
This is definitely a duplicate of #3483.

**Closed by jostrander** 2019-02-13 21:40 UTC
